// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `zx` — `GateRef`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use zx::GateRef;

audit_case!(gate_h_0, {
    let g = GateRef::new("h", vec![0]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_1, {
    let g = GateRef::new("h", vec![1]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_2, {
    let g = GateRef::new("h", vec![2]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_3, {
    let g = GateRef::new("h", vec![3]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_4, {
    let g = GateRef::new("h", vec![4]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_5, {
    let g = GateRef::new("h", vec![5]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_6, {
    let g = GateRef::new("h", vec![6]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_h_7, {
    let g = GateRef::new("h", vec![7]);
    assert_eq!(g.name, "h");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_0, {
    let g = GateRef::new("x", vec![0]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_1, {
    let g = GateRef::new("x", vec![1]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_2, {
    let g = GateRef::new("x", vec![2]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_3, {
    let g = GateRef::new("x", vec![3]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_4, {
    let g = GateRef::new("x", vec![4]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_5, {
    let g = GateRef::new("x", vec![5]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_6, {
    let g = GateRef::new("x", vec![6]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_x_7, {
    let g = GateRef::new("x", vec![7]);
    assert_eq!(g.name, "x");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_0, {
    let g = GateRef::new("z", vec![0]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_1, {
    let g = GateRef::new("z", vec![1]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_2, {
    let g = GateRef::new("z", vec![2]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_3, {
    let g = GateRef::new("z", vec![3]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_4, {
    let g = GateRef::new("z", vec![4]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_5, {
    let g = GateRef::new("z", vec![5]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_6, {
    let g = GateRef::new("z", vec![6]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_z_7, {
    let g = GateRef::new("z", vec![7]);
    assert_eq!(g.name, "z");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_0, {
    let g = GateRef::new("cx", vec![0]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_1, {
    let g = GateRef::new("cx", vec![1]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_2, {
    let g = GateRef::new("cx", vec![2]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_3, {
    let g = GateRef::new("cx", vec![3]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_4, {
    let g = GateRef::new("cx", vec![4]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_5, {
    let g = GateRef::new("cx", vec![5]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_6, {
    let g = GateRef::new("cx", vec![6]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_cx_7, {
    let g = GateRef::new("cx", vec![7]);
    assert_eq!(g.name, "cx");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_0, {
    let g = GateRef::new("rz", vec![0]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_1, {
    let g = GateRef::new("rz", vec![1]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_2, {
    let g = GateRef::new("rz", vec![2]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_3, {
    let g = GateRef::new("rz", vec![3]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_4, {
    let g = GateRef::new("rz", vec![4]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_5, {
    let g = GateRef::new("rz", vec![5]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_6, {
    let g = GateRef::new("rz", vec![6]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_rz_7, {
    let g = GateRef::new("rz", vec![7]);
    assert_eq!(g.name, "rz");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_0, {
    let g = GateRef::new("swap", vec![0]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![0]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_1, {
    let g = GateRef::new("swap", vec![1]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![1]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_2, {
    let g = GateRef::new("swap", vec![2]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![2]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_3, {
    let g = GateRef::new("swap", vec![3]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![3]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_4, {
    let g = GateRef::new("swap", vec![4]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![4]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_5, {
    let g = GateRef::new("swap", vec![5]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![5]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_6, {
    let g = GateRef::new("swap", vec![6]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![6]);
    assert!(g.angle.is_none());
});
audit_case!(gate_swap_7, {
    let g = GateRef::new("swap", vec![7]);
    assert_eq!(g.name, "swap");
    assert_eq!(g.qubits, vec![7]);
    assert!(g.angle.is_none());
});
audit_case!(rot_0, {
    let g = GateRef::rotation("rz", 0, 0.0);
    assert_eq!(g.angle, Some(0.0));
});
audit_case!(rot_1, {
    let g = GateRef::rotation("rz", 1, 0.1);
    assert_eq!(g.angle, Some(0.1));
});
audit_case!(rot_2, {
    let g = GateRef::rotation("rz", 2, 0.2);
    assert_eq!(g.angle, Some(0.2));
});
audit_case!(rot_3, {
    let g = GateRef::rotation("rz", 3, 0.30000000000000004);
    assert_eq!(g.angle, Some(0.30000000000000004));
});
audit_case!(rot_4, {
    let g = GateRef::rotation("rz", 4, 0.4);
    assert_eq!(g.angle, Some(0.4));
});
audit_case!(rot_5, {
    let g = GateRef::rotation("rz", 5, 0.5);
    assert_eq!(g.angle, Some(0.5));
});
audit_case!(rot_6, {
    let g = GateRef::rotation("rz", 6, 0.6000000000000001);
    assert_eq!(g.angle, Some(0.6000000000000001));
});
audit_case!(rot_7, {
    let g = GateRef::rotation("rz", 7, 0.7000000000000001);
    assert_eq!(g.angle, Some(0.7000000000000001));
});
audit_case!(rot_8, {
    let g = GateRef::rotation("rz", 8, 0.8);
    assert_eq!(g.angle, Some(0.8));
});
audit_case!(rot_9, {
    let g = GateRef::rotation("rz", 9, 0.9);
    assert_eq!(g.angle, Some(0.9));
});
audit_case!(rot_10, {
    let g = GateRef::rotation("rz", 10, 1.0);
    assert_eq!(g.angle, Some(1.0));
});
audit_case!(rot_11, {
    let g = GateRef::rotation("rz", 11, 1.1);
    assert_eq!(g.angle, Some(1.1));
});
audit_case!(rot_12, {
    let g = GateRef::rotation("rz", 12, 1.2000000000000002);
    assert_eq!(g.angle, Some(1.2000000000000002));
});
audit_case!(rot_13, {
    let g = GateRef::rotation("rz", 13, 1.3);
    assert_eq!(g.angle, Some(1.3));
});
audit_case!(rot_14, {
    let g = GateRef::rotation("rz", 14, 1.4000000000000001);
    assert_eq!(g.angle, Some(1.4000000000000001));
});
audit_case!(rot_15, {
    let g = GateRef::rotation("rz", 15, 1.5);
    assert_eq!(g.angle, Some(1.5));
});
