// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `quon_core` — `depth parse`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use quon_core::{DepthExpr, DepthParseError};

audit_case!(depth_nat_0000, {
    assert_eq!(DepthExpr::parse("0").unwrap(), DepthExpr::Nat(0));
});
audit_case!(depth_nat_0001, {
    assert_eq!(DepthExpr::parse("1").unwrap(), DepthExpr::Nat(1));
});
audit_case!(depth_nat_0002, {
    assert_eq!(DepthExpr::parse("2").unwrap(), DepthExpr::Nat(2));
});
audit_case!(depth_nat_0003, {
    assert_eq!(DepthExpr::parse("3").unwrap(), DepthExpr::Nat(3));
});
audit_case!(depth_nat_0004, {
    assert_eq!(DepthExpr::parse("4").unwrap(), DepthExpr::Nat(4));
});
audit_case!(depth_nat_0005, {
    assert_eq!(DepthExpr::parse("5").unwrap(), DepthExpr::Nat(5));
});
audit_case!(depth_nat_0006, {
    assert_eq!(DepthExpr::parse("6").unwrap(), DepthExpr::Nat(6));
});
audit_case!(depth_nat_0007, {
    assert_eq!(DepthExpr::parse("7").unwrap(), DepthExpr::Nat(7));
});
audit_case!(depth_nat_0008, {
    assert_eq!(DepthExpr::parse("8").unwrap(), DepthExpr::Nat(8));
});
audit_case!(depth_nat_0009, {
    assert_eq!(DepthExpr::parse("9").unwrap(), DepthExpr::Nat(9));
});
audit_case!(depth_nat_0010, {
    assert_eq!(DepthExpr::parse("10").unwrap(), DepthExpr::Nat(10));
});
audit_case!(depth_nat_0011, {
    assert_eq!(DepthExpr::parse("11").unwrap(), DepthExpr::Nat(11));
});
audit_case!(depth_nat_0012, {
    assert_eq!(DepthExpr::parse("12").unwrap(), DepthExpr::Nat(12));
});
audit_case!(depth_nat_0013, {
    assert_eq!(DepthExpr::parse("13").unwrap(), DepthExpr::Nat(13));
});
audit_case!(depth_nat_0014, {
    assert_eq!(DepthExpr::parse("14").unwrap(), DepthExpr::Nat(14));
});
audit_case!(depth_nat_0015, {
    assert_eq!(DepthExpr::parse("15").unwrap(), DepthExpr::Nat(15));
});
audit_case!(depth_nat_0016, {
    assert_eq!(DepthExpr::parse("16").unwrap(), DepthExpr::Nat(16));
});
audit_case!(depth_nat_0017, {
    assert_eq!(DepthExpr::parse("17").unwrap(), DepthExpr::Nat(17));
});
audit_case!(depth_nat_0018, {
    assert_eq!(DepthExpr::parse("18").unwrap(), DepthExpr::Nat(18));
});
audit_case!(depth_nat_0019, {
    assert_eq!(DepthExpr::parse("19").unwrap(), DepthExpr::Nat(19));
});
audit_case!(depth_nat_0020, {
    assert_eq!(DepthExpr::parse("20").unwrap(), DepthExpr::Nat(20));
});
audit_case!(depth_nat_0021, {
    assert_eq!(DepthExpr::parse("21").unwrap(), DepthExpr::Nat(21));
});
audit_case!(depth_nat_0022, {
    assert_eq!(DepthExpr::parse("22").unwrap(), DepthExpr::Nat(22));
});
audit_case!(depth_nat_0023, {
    assert_eq!(DepthExpr::parse("23").unwrap(), DepthExpr::Nat(23));
});
audit_case!(depth_nat_0024, {
    assert_eq!(DepthExpr::parse("24").unwrap(), DepthExpr::Nat(24));
});
audit_case!(depth_nat_0025, {
    assert_eq!(DepthExpr::parse("25").unwrap(), DepthExpr::Nat(25));
});
audit_case!(depth_nat_0026, {
    assert_eq!(DepthExpr::parse("26").unwrap(), DepthExpr::Nat(26));
});
audit_case!(depth_nat_0027, {
    assert_eq!(DepthExpr::parse("27").unwrap(), DepthExpr::Nat(27));
});
audit_case!(depth_nat_0028, {
    assert_eq!(DepthExpr::parse("28").unwrap(), DepthExpr::Nat(28));
});
audit_case!(depth_nat_0029, {
    assert_eq!(DepthExpr::parse("29").unwrap(), DepthExpr::Nat(29));
});
audit_case!(depth_nat_0030, {
    assert_eq!(DepthExpr::parse("30").unwrap(), DepthExpr::Nat(30));
});
audit_case!(depth_nat_0031, {
    assert_eq!(DepthExpr::parse("31").unwrap(), DepthExpr::Nat(31));
});
audit_case!(depth_nat_0032, {
    assert_eq!(DepthExpr::parse("32").unwrap(), DepthExpr::Nat(32));
});
audit_case!(depth_nat_0033, {
    assert_eq!(DepthExpr::parse("33").unwrap(), DepthExpr::Nat(33));
});
audit_case!(depth_nat_0034, {
    assert_eq!(DepthExpr::parse("34").unwrap(), DepthExpr::Nat(34));
});
audit_case!(depth_nat_0035, {
    assert_eq!(DepthExpr::parse("35").unwrap(), DepthExpr::Nat(35));
});
audit_case!(depth_nat_0036, {
    assert_eq!(DepthExpr::parse("36").unwrap(), DepthExpr::Nat(36));
});
audit_case!(depth_nat_0037, {
    assert_eq!(DepthExpr::parse("37").unwrap(), DepthExpr::Nat(37));
});
audit_case!(depth_nat_0038, {
    assert_eq!(DepthExpr::parse("38").unwrap(), DepthExpr::Nat(38));
});
audit_case!(depth_nat_0039, {
    assert_eq!(DepthExpr::parse("39").unwrap(), DepthExpr::Nat(39));
});
audit_case!(depth_nat_0040, {
    assert_eq!(DepthExpr::parse("40").unwrap(), DepthExpr::Nat(40));
});
audit_case!(depth_nat_0041, {
    assert_eq!(DepthExpr::parse("41").unwrap(), DepthExpr::Nat(41));
});
audit_case!(depth_nat_0042, {
    assert_eq!(DepthExpr::parse("42").unwrap(), DepthExpr::Nat(42));
});
audit_case!(depth_nat_0043, {
    assert_eq!(DepthExpr::parse("43").unwrap(), DepthExpr::Nat(43));
});
audit_case!(depth_nat_0044, {
    assert_eq!(DepthExpr::parse("44").unwrap(), DepthExpr::Nat(44));
});
audit_case!(depth_nat_0045, {
    assert_eq!(DepthExpr::parse("45").unwrap(), DepthExpr::Nat(45));
});
audit_case!(depth_nat_0046, {
    assert_eq!(DepthExpr::parse("46").unwrap(), DepthExpr::Nat(46));
});
audit_case!(depth_nat_0047, {
    assert_eq!(DepthExpr::parse("47").unwrap(), DepthExpr::Nat(47));
});
audit_case!(depth_nat_0048, {
    assert_eq!(DepthExpr::parse("48").unwrap(), DepthExpr::Nat(48));
});
audit_case!(depth_nat_0049, {
    assert_eq!(DepthExpr::parse("49").unwrap(), DepthExpr::Nat(49));
});
audit_case!(depth_nat_0050, {
    assert_eq!(DepthExpr::parse("50").unwrap(), DepthExpr::Nat(50));
});
audit_case!(depth_nat_0051, {
    assert_eq!(DepthExpr::parse("51").unwrap(), DepthExpr::Nat(51));
});
audit_case!(depth_nat_0052, {
    assert_eq!(DepthExpr::parse("52").unwrap(), DepthExpr::Nat(52));
});
audit_case!(depth_nat_0053, {
    assert_eq!(DepthExpr::parse("53").unwrap(), DepthExpr::Nat(53));
});
audit_case!(depth_nat_0054, {
    assert_eq!(DepthExpr::parse("54").unwrap(), DepthExpr::Nat(54));
});
audit_case!(depth_nat_0055, {
    assert_eq!(DepthExpr::parse("55").unwrap(), DepthExpr::Nat(55));
});
audit_case!(depth_nat_0056, {
    assert_eq!(DepthExpr::parse("56").unwrap(), DepthExpr::Nat(56));
});
audit_case!(depth_nat_0057, {
    assert_eq!(DepthExpr::parse("57").unwrap(), DepthExpr::Nat(57));
});
audit_case!(depth_nat_0058, {
    assert_eq!(DepthExpr::parse("58").unwrap(), DepthExpr::Nat(58));
});
audit_case!(depth_nat_0059, {
    assert_eq!(DepthExpr::parse("59").unwrap(), DepthExpr::Nat(59));
});
audit_case!(depth_nat_0060, {
    assert_eq!(DepthExpr::parse("60").unwrap(), DepthExpr::Nat(60));
});
audit_case!(depth_nat_0061, {
    assert_eq!(DepthExpr::parse("61").unwrap(), DepthExpr::Nat(61));
});
audit_case!(depth_nat_0062, {
    assert_eq!(DepthExpr::parse("62").unwrap(), DepthExpr::Nat(62));
});
audit_case!(depth_nat_0063, {
    assert_eq!(DepthExpr::parse("63").unwrap(), DepthExpr::Nat(63));
});
audit_case!(depth_nat_0064, {
    assert_eq!(DepthExpr::parse("64").unwrap(), DepthExpr::Nat(64));
});
audit_case!(depth_nat_0065, {
    assert_eq!(DepthExpr::parse("65").unwrap(), DepthExpr::Nat(65));
});
audit_case!(depth_nat_0066, {
    assert_eq!(DepthExpr::parse("66").unwrap(), DepthExpr::Nat(66));
});
audit_case!(depth_nat_0067, {
    assert_eq!(DepthExpr::parse("67").unwrap(), DepthExpr::Nat(67));
});
audit_case!(depth_nat_0068, {
    assert_eq!(DepthExpr::parse("68").unwrap(), DepthExpr::Nat(68));
});
audit_case!(depth_nat_0069, {
    assert_eq!(DepthExpr::parse("69").unwrap(), DepthExpr::Nat(69));
});
audit_case!(depth_nat_0070, {
    assert_eq!(DepthExpr::parse("70").unwrap(), DepthExpr::Nat(70));
});
audit_case!(depth_nat_0071, {
    assert_eq!(DepthExpr::parse("71").unwrap(), DepthExpr::Nat(71));
});
audit_case!(depth_nat_0072, {
    assert_eq!(DepthExpr::parse("72").unwrap(), DepthExpr::Nat(72));
});
audit_case!(depth_nat_0073, {
    assert_eq!(DepthExpr::parse("73").unwrap(), DepthExpr::Nat(73));
});
audit_case!(depth_nat_0074, {
    assert_eq!(DepthExpr::parse("74").unwrap(), DepthExpr::Nat(74));
});
audit_case!(depth_nat_0075, {
    assert_eq!(DepthExpr::parse("75").unwrap(), DepthExpr::Nat(75));
});
audit_case!(depth_nat_0076, {
    assert_eq!(DepthExpr::parse("76").unwrap(), DepthExpr::Nat(76));
});
audit_case!(depth_nat_0077, {
    assert_eq!(DepthExpr::parse("77").unwrap(), DepthExpr::Nat(77));
});
audit_case!(depth_nat_0078, {
    assert_eq!(DepthExpr::parse("78").unwrap(), DepthExpr::Nat(78));
});
audit_case!(depth_nat_0079, {
    assert_eq!(DepthExpr::parse("79").unwrap(), DepthExpr::Nat(79));
});
audit_case!(depth_nat_0080, {
    assert_eq!(DepthExpr::parse("80").unwrap(), DepthExpr::Nat(80));
});
audit_case!(depth_nat_0081, {
    assert_eq!(DepthExpr::parse("81").unwrap(), DepthExpr::Nat(81));
});
audit_case!(depth_nat_0082, {
    assert_eq!(DepthExpr::parse("82").unwrap(), DepthExpr::Nat(82));
});
audit_case!(depth_nat_0083, {
    assert_eq!(DepthExpr::parse("83").unwrap(), DepthExpr::Nat(83));
});
audit_case!(depth_nat_0084, {
    assert_eq!(DepthExpr::parse("84").unwrap(), DepthExpr::Nat(84));
});
audit_case!(depth_nat_0085, {
    assert_eq!(DepthExpr::parse("85").unwrap(), DepthExpr::Nat(85));
});
audit_case!(depth_nat_0086, {
    assert_eq!(DepthExpr::parse("86").unwrap(), DepthExpr::Nat(86));
});
audit_case!(depth_nat_0087, {
    assert_eq!(DepthExpr::parse("87").unwrap(), DepthExpr::Nat(87));
});
audit_case!(depth_nat_0088, {
    assert_eq!(DepthExpr::parse("88").unwrap(), DepthExpr::Nat(88));
});
audit_case!(depth_nat_0089, {
    assert_eq!(DepthExpr::parse("89").unwrap(), DepthExpr::Nat(89));
});
audit_case!(depth_nat_0090, {
    assert_eq!(DepthExpr::parse("90").unwrap(), DepthExpr::Nat(90));
});
audit_case!(depth_nat_0091, {
    assert_eq!(DepthExpr::parse("91").unwrap(), DepthExpr::Nat(91));
});
audit_case!(depth_nat_0092, {
    assert_eq!(DepthExpr::parse("92").unwrap(), DepthExpr::Nat(92));
});
audit_case!(depth_nat_0093, {
    assert_eq!(DepthExpr::parse("93").unwrap(), DepthExpr::Nat(93));
});
audit_case!(depth_nat_0094, {
    assert_eq!(DepthExpr::parse("94").unwrap(), DepthExpr::Nat(94));
});
audit_case!(depth_nat_0095, {
    assert_eq!(DepthExpr::parse("95").unwrap(), DepthExpr::Nat(95));
});
audit_case!(depth_nat_0096, {
    assert_eq!(DepthExpr::parse("96").unwrap(), DepthExpr::Nat(96));
});
audit_case!(depth_nat_0097, {
    assert_eq!(DepthExpr::parse("97").unwrap(), DepthExpr::Nat(97));
});
audit_case!(depth_nat_0098, {
    assert_eq!(DepthExpr::parse("98").unwrap(), DepthExpr::Nat(98));
});
audit_case!(depth_nat_0099, {
    assert_eq!(DepthExpr::parse("99").unwrap(), DepthExpr::Nat(99));
});
audit_case!(depth_nat_0100, {
    assert_eq!(DepthExpr::parse("100").unwrap(), DepthExpr::Nat(100));
});
audit_case!(depth_nat_0101, {
    assert_eq!(DepthExpr::parse("101").unwrap(), DepthExpr::Nat(101));
});
audit_case!(depth_nat_0102, {
    assert_eq!(DepthExpr::parse("102").unwrap(), DepthExpr::Nat(102));
});
audit_case!(depth_nat_0103, {
    assert_eq!(DepthExpr::parse("103").unwrap(), DepthExpr::Nat(103));
});
audit_case!(depth_nat_0104, {
    assert_eq!(DepthExpr::parse("104").unwrap(), DepthExpr::Nat(104));
});
audit_case!(depth_nat_0105, {
    assert_eq!(DepthExpr::parse("105").unwrap(), DepthExpr::Nat(105));
});
audit_case!(depth_nat_0106, {
    assert_eq!(DepthExpr::parse("106").unwrap(), DepthExpr::Nat(106));
});
audit_case!(depth_nat_0107, {
    assert_eq!(DepthExpr::parse("107").unwrap(), DepthExpr::Nat(107));
});
audit_case!(depth_nat_0108, {
    assert_eq!(DepthExpr::parse("108").unwrap(), DepthExpr::Nat(108));
});
audit_case!(depth_nat_0109, {
    assert_eq!(DepthExpr::parse("109").unwrap(), DepthExpr::Nat(109));
});
audit_case!(depth_nat_0110, {
    assert_eq!(DepthExpr::parse("110").unwrap(), DepthExpr::Nat(110));
});
audit_case!(depth_nat_0111, {
    assert_eq!(DepthExpr::parse("111").unwrap(), DepthExpr::Nat(111));
});
audit_case!(depth_nat_0112, {
    assert_eq!(DepthExpr::parse("112").unwrap(), DepthExpr::Nat(112));
});
audit_case!(depth_nat_0113, {
    assert_eq!(DepthExpr::parse("113").unwrap(), DepthExpr::Nat(113));
});
audit_case!(depth_nat_0114, {
    assert_eq!(DepthExpr::parse("114").unwrap(), DepthExpr::Nat(114));
});
audit_case!(depth_nat_0115, {
    assert_eq!(DepthExpr::parse("115").unwrap(), DepthExpr::Nat(115));
});
audit_case!(depth_nat_0116, {
    assert_eq!(DepthExpr::parse("116").unwrap(), DepthExpr::Nat(116));
});
audit_case!(depth_nat_0117, {
    assert_eq!(DepthExpr::parse("117").unwrap(), DepthExpr::Nat(117));
});
audit_case!(depth_nat_0118, {
    assert_eq!(DepthExpr::parse("118").unwrap(), DepthExpr::Nat(118));
});
audit_case!(depth_nat_0119, {
    assert_eq!(DepthExpr::parse("119").unwrap(), DepthExpr::Nat(119));
});
audit_case!(depth_nat_0120, {
    assert_eq!(DepthExpr::parse("120").unwrap(), DepthExpr::Nat(120));
});
audit_case!(depth_nat_0121, {
    assert_eq!(DepthExpr::parse("121").unwrap(), DepthExpr::Nat(121));
});
audit_case!(depth_nat_0122, {
    assert_eq!(DepthExpr::parse("122").unwrap(), DepthExpr::Nat(122));
});
audit_case!(depth_nat_0123, {
    assert_eq!(DepthExpr::parse("123").unwrap(), DepthExpr::Nat(123));
});
audit_case!(depth_nat_0124, {
    assert_eq!(DepthExpr::parse("124").unwrap(), DepthExpr::Nat(124));
});
audit_case!(depth_nat_0125, {
    assert_eq!(DepthExpr::parse("125").unwrap(), DepthExpr::Nat(125));
});
audit_case!(depth_nat_0126, {
    assert_eq!(DepthExpr::parse("126").unwrap(), DepthExpr::Nat(126));
});
audit_case!(depth_nat_0127, {
    assert_eq!(DepthExpr::parse("127").unwrap(), DepthExpr::Nat(127));
});
audit_case!(depth_nat_0128, {
    assert_eq!(DepthExpr::parse("128").unwrap(), DepthExpr::Nat(128));
});
audit_case!(depth_nat_0129, {
    assert_eq!(DepthExpr::parse("129").unwrap(), DepthExpr::Nat(129));
});
audit_case!(depth_nat_0130, {
    assert_eq!(DepthExpr::parse("130").unwrap(), DepthExpr::Nat(130));
});
audit_case!(depth_nat_0131, {
    assert_eq!(DepthExpr::parse("131").unwrap(), DepthExpr::Nat(131));
});
audit_case!(depth_nat_0132, {
    assert_eq!(DepthExpr::parse("132").unwrap(), DepthExpr::Nat(132));
});
audit_case!(depth_nat_0133, {
    assert_eq!(DepthExpr::parse("133").unwrap(), DepthExpr::Nat(133));
});
audit_case!(depth_nat_0134, {
    assert_eq!(DepthExpr::parse("134").unwrap(), DepthExpr::Nat(134));
});
audit_case!(depth_nat_0135, {
    assert_eq!(DepthExpr::parse("135").unwrap(), DepthExpr::Nat(135));
});
audit_case!(depth_nat_0136, {
    assert_eq!(DepthExpr::parse("136").unwrap(), DepthExpr::Nat(136));
});
audit_case!(depth_nat_0137, {
    assert_eq!(DepthExpr::parse("137").unwrap(), DepthExpr::Nat(137));
});
audit_case!(depth_nat_0138, {
    assert_eq!(DepthExpr::parse("138").unwrap(), DepthExpr::Nat(138));
});
audit_case!(depth_nat_0139, {
    assert_eq!(DepthExpr::parse("139").unwrap(), DepthExpr::Nat(139));
});
audit_case!(depth_nat_0140, {
    assert_eq!(DepthExpr::parse("140").unwrap(), DepthExpr::Nat(140));
});
audit_case!(depth_nat_0141, {
    assert_eq!(DepthExpr::parse("141").unwrap(), DepthExpr::Nat(141));
});
audit_case!(depth_nat_0142, {
    assert_eq!(DepthExpr::parse("142").unwrap(), DepthExpr::Nat(142));
});
audit_case!(depth_nat_0143, {
    assert_eq!(DepthExpr::parse("143").unwrap(), DepthExpr::Nat(143));
});
audit_case!(depth_nat_0144, {
    assert_eq!(DepthExpr::parse("144").unwrap(), DepthExpr::Nat(144));
});
audit_case!(depth_nat_0145, {
    assert_eq!(DepthExpr::parse("145").unwrap(), DepthExpr::Nat(145));
});
audit_case!(depth_nat_0146, {
    assert_eq!(DepthExpr::parse("146").unwrap(), DepthExpr::Nat(146));
});
audit_case!(depth_nat_0147, {
    assert_eq!(DepthExpr::parse("147").unwrap(), DepthExpr::Nat(147));
});
audit_case!(depth_nat_0148, {
    assert_eq!(DepthExpr::parse("148").unwrap(), DepthExpr::Nat(148));
});
audit_case!(depth_nat_0149, {
    assert_eq!(DepthExpr::parse("149").unwrap(), DepthExpr::Nat(149));
});
audit_case!(depth_nat_0150, {
    assert_eq!(DepthExpr::parse("150").unwrap(), DepthExpr::Nat(150));
});
audit_case!(depth_nat_0151, {
    assert_eq!(DepthExpr::parse("151").unwrap(), DepthExpr::Nat(151));
});
audit_case!(depth_nat_0152, {
    assert_eq!(DepthExpr::parse("152").unwrap(), DepthExpr::Nat(152));
});
audit_case!(depth_nat_0153, {
    assert_eq!(DepthExpr::parse("153").unwrap(), DepthExpr::Nat(153));
});
audit_case!(depth_nat_0154, {
    assert_eq!(DepthExpr::parse("154").unwrap(), DepthExpr::Nat(154));
});
audit_case!(depth_nat_0155, {
    assert_eq!(DepthExpr::parse("155").unwrap(), DepthExpr::Nat(155));
});
audit_case!(depth_nat_0156, {
    assert_eq!(DepthExpr::parse("156").unwrap(), DepthExpr::Nat(156));
});
audit_case!(depth_nat_0157, {
    assert_eq!(DepthExpr::parse("157").unwrap(), DepthExpr::Nat(157));
});
audit_case!(depth_nat_0158, {
    assert_eq!(DepthExpr::parse("158").unwrap(), DepthExpr::Nat(158));
});
audit_case!(depth_nat_0159, {
    assert_eq!(DepthExpr::parse("159").unwrap(), DepthExpr::Nat(159));
});
audit_case!(depth_nat_0160, {
    assert_eq!(DepthExpr::parse("160").unwrap(), DepthExpr::Nat(160));
});
audit_case!(depth_nat_0161, {
    assert_eq!(DepthExpr::parse("161").unwrap(), DepthExpr::Nat(161));
});
audit_case!(depth_nat_0162, {
    assert_eq!(DepthExpr::parse("162").unwrap(), DepthExpr::Nat(162));
});
audit_case!(depth_nat_0163, {
    assert_eq!(DepthExpr::parse("163").unwrap(), DepthExpr::Nat(163));
});
audit_case!(depth_nat_0164, {
    assert_eq!(DepthExpr::parse("164").unwrap(), DepthExpr::Nat(164));
});
audit_case!(depth_nat_0165, {
    assert_eq!(DepthExpr::parse("165").unwrap(), DepthExpr::Nat(165));
});
audit_case!(depth_nat_0166, {
    assert_eq!(DepthExpr::parse("166").unwrap(), DepthExpr::Nat(166));
});
audit_case!(depth_nat_0167, {
    assert_eq!(DepthExpr::parse("167").unwrap(), DepthExpr::Nat(167));
});
audit_case!(depth_nat_0168, {
    assert_eq!(DepthExpr::parse("168").unwrap(), DepthExpr::Nat(168));
});
audit_case!(depth_nat_0169, {
    assert_eq!(DepthExpr::parse("169").unwrap(), DepthExpr::Nat(169));
});
audit_case!(depth_nat_0170, {
    assert_eq!(DepthExpr::parse("170").unwrap(), DepthExpr::Nat(170));
});
audit_case!(depth_nat_0171, {
    assert_eq!(DepthExpr::parse("171").unwrap(), DepthExpr::Nat(171));
});
audit_case!(depth_nat_0172, {
    assert_eq!(DepthExpr::parse("172").unwrap(), DepthExpr::Nat(172));
});
audit_case!(depth_nat_0173, {
    assert_eq!(DepthExpr::parse("173").unwrap(), DepthExpr::Nat(173));
});
audit_case!(depth_nat_0174, {
    assert_eq!(DepthExpr::parse("174").unwrap(), DepthExpr::Nat(174));
});
audit_case!(depth_nat_0175, {
    assert_eq!(DepthExpr::parse("175").unwrap(), DepthExpr::Nat(175));
});
audit_case!(depth_nat_0176, {
    assert_eq!(DepthExpr::parse("176").unwrap(), DepthExpr::Nat(176));
});
audit_case!(depth_nat_0177, {
    assert_eq!(DepthExpr::parse("177").unwrap(), DepthExpr::Nat(177));
});
audit_case!(depth_nat_0178, {
    assert_eq!(DepthExpr::parse("178").unwrap(), DepthExpr::Nat(178));
});
audit_case!(depth_nat_0179, {
    assert_eq!(DepthExpr::parse("179").unwrap(), DepthExpr::Nat(179));
});
audit_case!(depth_nat_0180, {
    assert_eq!(DepthExpr::parse("180").unwrap(), DepthExpr::Nat(180));
});
audit_case!(depth_nat_0181, {
    assert_eq!(DepthExpr::parse("181").unwrap(), DepthExpr::Nat(181));
});
audit_case!(depth_nat_0182, {
    assert_eq!(DepthExpr::parse("182").unwrap(), DepthExpr::Nat(182));
});
audit_case!(depth_nat_0183, {
    assert_eq!(DepthExpr::parse("183").unwrap(), DepthExpr::Nat(183));
});
audit_case!(depth_nat_0184, {
    assert_eq!(DepthExpr::parse("184").unwrap(), DepthExpr::Nat(184));
});
audit_case!(depth_nat_0185, {
    assert_eq!(DepthExpr::parse("185").unwrap(), DepthExpr::Nat(185));
});
audit_case!(depth_nat_0186, {
    assert_eq!(DepthExpr::parse("186").unwrap(), DepthExpr::Nat(186));
});
audit_case!(depth_nat_0187, {
    assert_eq!(DepthExpr::parse("187").unwrap(), DepthExpr::Nat(187));
});
audit_case!(depth_nat_0188, {
    assert_eq!(DepthExpr::parse("188").unwrap(), DepthExpr::Nat(188));
});
audit_case!(depth_nat_0189, {
    assert_eq!(DepthExpr::parse("189").unwrap(), DepthExpr::Nat(189));
});
audit_case!(depth_nat_0190, {
    assert_eq!(DepthExpr::parse("190").unwrap(), DepthExpr::Nat(190));
});
audit_case!(depth_nat_0191, {
    assert_eq!(DepthExpr::parse("191").unwrap(), DepthExpr::Nat(191));
});
audit_case!(depth_nat_0192, {
    assert_eq!(DepthExpr::parse("192").unwrap(), DepthExpr::Nat(192));
});
audit_case!(depth_nat_0193, {
    assert_eq!(DepthExpr::parse("193").unwrap(), DepthExpr::Nat(193));
});
audit_case!(depth_nat_0194, {
    assert_eq!(DepthExpr::parse("194").unwrap(), DepthExpr::Nat(194));
});
audit_case!(depth_nat_0195, {
    assert_eq!(DepthExpr::parse("195").unwrap(), DepthExpr::Nat(195));
});
audit_case!(depth_nat_0196, {
    assert_eq!(DepthExpr::parse("196").unwrap(), DepthExpr::Nat(196));
});
audit_case!(depth_nat_0197, {
    assert_eq!(DepthExpr::parse("197").unwrap(), DepthExpr::Nat(197));
});
audit_case!(depth_nat_0198, {
    assert_eq!(DepthExpr::parse("198").unwrap(), DepthExpr::Nat(198));
});
audit_case!(depth_nat_0199, {
    assert_eq!(DepthExpr::parse("199").unwrap(), DepthExpr::Nat(199));
});
audit_case!(depth_nat_0200, {
    assert_eq!(DepthExpr::parse("200").unwrap(), DepthExpr::Nat(200));
});
audit_case!(depth_nat_0201, {
    assert_eq!(DepthExpr::parse("201").unwrap(), DepthExpr::Nat(201));
});
audit_case!(depth_nat_0202, {
    assert_eq!(DepthExpr::parse("202").unwrap(), DepthExpr::Nat(202));
});
audit_case!(depth_nat_0203, {
    assert_eq!(DepthExpr::parse("203").unwrap(), DepthExpr::Nat(203));
});
audit_case!(depth_nat_0204, {
    assert_eq!(DepthExpr::parse("204").unwrap(), DepthExpr::Nat(204));
});
audit_case!(depth_nat_0205, {
    assert_eq!(DepthExpr::parse("205").unwrap(), DepthExpr::Nat(205));
});
audit_case!(depth_nat_0206, {
    assert_eq!(DepthExpr::parse("206").unwrap(), DepthExpr::Nat(206));
});
audit_case!(depth_nat_0207, {
    assert_eq!(DepthExpr::parse("207").unwrap(), DepthExpr::Nat(207));
});
audit_case!(depth_nat_0208, {
    assert_eq!(DepthExpr::parse("208").unwrap(), DepthExpr::Nat(208));
});
audit_case!(depth_nat_0209, {
    assert_eq!(DepthExpr::parse("209").unwrap(), DepthExpr::Nat(209));
});
audit_case!(depth_nat_0210, {
    assert_eq!(DepthExpr::parse("210").unwrap(), DepthExpr::Nat(210));
});
audit_case!(depth_nat_0211, {
    assert_eq!(DepthExpr::parse("211").unwrap(), DepthExpr::Nat(211));
});
audit_case!(depth_nat_0212, {
    assert_eq!(DepthExpr::parse("212").unwrap(), DepthExpr::Nat(212));
});
audit_case!(depth_nat_0213, {
    assert_eq!(DepthExpr::parse("213").unwrap(), DepthExpr::Nat(213));
});
audit_case!(depth_nat_0214, {
    assert_eq!(DepthExpr::parse("214").unwrap(), DepthExpr::Nat(214));
});
audit_case!(depth_nat_0215, {
    assert_eq!(DepthExpr::parse("215").unwrap(), DepthExpr::Nat(215));
});
audit_case!(depth_nat_0216, {
    assert_eq!(DepthExpr::parse("216").unwrap(), DepthExpr::Nat(216));
});
audit_case!(depth_nat_0217, {
    assert_eq!(DepthExpr::parse("217").unwrap(), DepthExpr::Nat(217));
});
audit_case!(depth_nat_0218, {
    assert_eq!(DepthExpr::parse("218").unwrap(), DepthExpr::Nat(218));
});
audit_case!(depth_nat_0219, {
    assert_eq!(DepthExpr::parse("219").unwrap(), DepthExpr::Nat(219));
});
audit_case!(depth_nat_0220, {
    assert_eq!(DepthExpr::parse("220").unwrap(), DepthExpr::Nat(220));
});
audit_case!(depth_nat_0221, {
    assert_eq!(DepthExpr::parse("221").unwrap(), DepthExpr::Nat(221));
});
audit_case!(depth_nat_0222, {
    assert_eq!(DepthExpr::parse("222").unwrap(), DepthExpr::Nat(222));
});
audit_case!(depth_nat_0223, {
    assert_eq!(DepthExpr::parse("223").unwrap(), DepthExpr::Nat(223));
});
audit_case!(depth_nat_0224, {
    assert_eq!(DepthExpr::parse("224").unwrap(), DepthExpr::Nat(224));
});
audit_case!(depth_nat_0225, {
    assert_eq!(DepthExpr::parse("225").unwrap(), DepthExpr::Nat(225));
});
audit_case!(depth_nat_0226, {
    assert_eq!(DepthExpr::parse("226").unwrap(), DepthExpr::Nat(226));
});
audit_case!(depth_nat_0227, {
    assert_eq!(DepthExpr::parse("227").unwrap(), DepthExpr::Nat(227));
});
audit_case!(depth_nat_0228, {
    assert_eq!(DepthExpr::parse("228").unwrap(), DepthExpr::Nat(228));
});
audit_case!(depth_nat_0229, {
    assert_eq!(DepthExpr::parse("229").unwrap(), DepthExpr::Nat(229));
});
audit_case!(depth_nat_0230, {
    assert_eq!(DepthExpr::parse("230").unwrap(), DepthExpr::Nat(230));
});
audit_case!(depth_nat_0231, {
    assert_eq!(DepthExpr::parse("231").unwrap(), DepthExpr::Nat(231));
});
audit_case!(depth_nat_0232, {
    assert_eq!(DepthExpr::parse("232").unwrap(), DepthExpr::Nat(232));
});
audit_case!(depth_nat_0233, {
    assert_eq!(DepthExpr::parse("233").unwrap(), DepthExpr::Nat(233));
});
audit_case!(depth_nat_0234, {
    assert_eq!(DepthExpr::parse("234").unwrap(), DepthExpr::Nat(234));
});
audit_case!(depth_nat_0235, {
    assert_eq!(DepthExpr::parse("235").unwrap(), DepthExpr::Nat(235));
});
audit_case!(depth_nat_0236, {
    assert_eq!(DepthExpr::parse("236").unwrap(), DepthExpr::Nat(236));
});
audit_case!(depth_nat_0237, {
    assert_eq!(DepthExpr::parse("237").unwrap(), DepthExpr::Nat(237));
});
audit_case!(depth_nat_0238, {
    assert_eq!(DepthExpr::parse("238").unwrap(), DepthExpr::Nat(238));
});
audit_case!(depth_nat_0239, {
    assert_eq!(DepthExpr::parse("239").unwrap(), DepthExpr::Nat(239));
});
audit_case!(depth_nat_0240, {
    assert_eq!(DepthExpr::parse("240").unwrap(), DepthExpr::Nat(240));
});
audit_case!(depth_nat_0241, {
    assert_eq!(DepthExpr::parse("241").unwrap(), DepthExpr::Nat(241));
});
audit_case!(depth_nat_0242, {
    assert_eq!(DepthExpr::parse("242").unwrap(), DepthExpr::Nat(242));
});
audit_case!(depth_nat_0243, {
    assert_eq!(DepthExpr::parse("243").unwrap(), DepthExpr::Nat(243));
});
audit_case!(depth_nat_0244, {
    assert_eq!(DepthExpr::parse("244").unwrap(), DepthExpr::Nat(244));
});
audit_case!(depth_nat_0245, {
    assert_eq!(DepthExpr::parse("245").unwrap(), DepthExpr::Nat(245));
});
audit_case!(depth_nat_0246, {
    assert_eq!(DepthExpr::parse("246").unwrap(), DepthExpr::Nat(246));
});
audit_case!(depth_nat_0247, {
    assert_eq!(DepthExpr::parse("247").unwrap(), DepthExpr::Nat(247));
});
audit_case!(depth_nat_0248, {
    assert_eq!(DepthExpr::parse("248").unwrap(), DepthExpr::Nat(248));
});
audit_case!(depth_nat_0249, {
    assert_eq!(DepthExpr::parse("249").unwrap(), DepthExpr::Nat(249));
});
audit_case!(depth_nat_0250, {
    assert_eq!(DepthExpr::parse("250").unwrap(), DepthExpr::Nat(250));
});
audit_case!(depth_nat_0251, {
    assert_eq!(DepthExpr::parse("251").unwrap(), DepthExpr::Nat(251));
});
audit_case!(depth_nat_0252, {
    assert_eq!(DepthExpr::parse("252").unwrap(), DepthExpr::Nat(252));
});
audit_case!(depth_nat_0253, {
    assert_eq!(DepthExpr::parse("253").unwrap(), DepthExpr::Nat(253));
});
audit_case!(depth_nat_0254, {
    assert_eq!(DepthExpr::parse("254").unwrap(), DepthExpr::Nat(254));
});
audit_case!(depth_nat_0255, {
    assert_eq!(DepthExpr::parse("255").unwrap(), DepthExpr::Nat(255));
});
audit_case!(depth_var_n, {
    assert_eq!(DepthExpr::parse("n").unwrap(), DepthExpr::Var("n".into()));
});
audit_case!(depth_var_m, {
    assert_eq!(DepthExpr::parse("m").unwrap(), DepthExpr::Var("m".into()));
});
audit_case!(depth_var_k, {
    assert_eq!(DepthExpr::parse("k").unwrap(), DepthExpr::Var("k".into()));
});
audit_case!(depth_var_depth, {
    assert_eq!(
        DepthExpr::parse("depth").unwrap(),
        DepthExpr::Var("depth".into())
    );
});
audit_case!(depth_var_foo, {
    assert_eq!(
        DepthExpr::parse("foo").unwrap(),
        DepthExpr::Var("foo".into())
    );
});
audit_case!(depth_var_bar_baz, {
    assert_eq!(
        DepthExpr::parse("bar_baz").unwrap(),
        DepthExpr::Var("bar_baz".into())
    );
});
audit_case!(depth_var_x1, {
    assert_eq!(DepthExpr::parse("x1").unwrap(), DepthExpr::Var("x1".into()));
});
audit_case!(depth_var_qft_depth, {
    assert_eq!(
        DepthExpr::parse("qft_depth").unwrap(),
        DepthExpr::Var("qft_depth".into())
    );
});
audit_case!(depth_bin_0000, {
    let got = DepthExpr::parse("(+ 0 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0001, {
    let got = DepthExpr::parse("(* 0 0)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0002, {
    let got = DepthExpr::parse("(max 0 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0003, {
    let got = DepthExpr::parse("(+ 0 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0004, {
    let got = DepthExpr::parse("(* 0 1)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0005, {
    let got = DepthExpr::parse("(max 0 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0006, {
    let got = DepthExpr::parse("(+ 0 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0007, {
    let got = DepthExpr::parse("(* 0 2)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0008, {
    let got = DepthExpr::parse("(max 0 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0009, {
    let got = DepthExpr::parse("(+ 0 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0010, {
    let got = DepthExpr::parse("(* 0 3)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0011, {
    let got = DepthExpr::parse("(max 0 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0012, {
    let got = DepthExpr::parse("(+ 0 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0013, {
    let got = DepthExpr::parse("(* 0 4)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0014, {
    let got = DepthExpr::parse("(max 0 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0015, {
    let got = DepthExpr::parse("(+ 0 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0016, {
    let got = DepthExpr::parse("(* 0 5)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0017, {
    let got = DepthExpr::parse("(max 0 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0018, {
    let got = DepthExpr::parse("(+ 0 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0019, {
    let got = DepthExpr::parse("(* 0 6)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0020, {
    let got = DepthExpr::parse("(max 0 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0021, {
    let got = DepthExpr::parse("(+ 0 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0022, {
    let got = DepthExpr::parse("(* 0 7)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0023, {
    let got = DepthExpr::parse("(max 0 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0024, {
    let got = DepthExpr::parse("(+ 0 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0025, {
    let got = DepthExpr::parse("(* 0 8)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0026, {
    let got = DepthExpr::parse("(max 0 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0027, {
    let got = DepthExpr::parse("(+ 0 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0028, {
    let got = DepthExpr::parse("(* 0 9)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0029, {
    let got = DepthExpr::parse("(max 0 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0030, {
    let got = DepthExpr::parse("(+ 0 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0031, {
    let got = DepthExpr::parse("(* 0 10)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0032, {
    let got = DepthExpr::parse("(max 0 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0033, {
    let got = DepthExpr::parse("(+ 0 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0034, {
    let got = DepthExpr::parse("(* 0 11)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0035, {
    let got = DepthExpr::parse("(max 0 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0036, {
    let got = DepthExpr::parse("(+ 0 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0037, {
    let got = DepthExpr::parse("(* 0 12)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0038, {
    let got = DepthExpr::parse("(max 0 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0039, {
    let got = DepthExpr::parse("(+ 0 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0040, {
    let got = DepthExpr::parse("(* 0 13)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0041, {
    let got = DepthExpr::parse("(max 0 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0042, {
    let got = DepthExpr::parse("(+ 0 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0043, {
    let got = DepthExpr::parse("(* 0 14)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0044, {
    let got = DepthExpr::parse("(max 0 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0045, {
    let got = DepthExpr::parse("(+ 0 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).seq(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0046, {
    let got = DepthExpr::parse("(* 0 15)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0047, {
    let got = DepthExpr::parse("(max 0 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(0).par(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0048, {
    let got = DepthExpr::parse("(+ 1 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0049, {
    let got = DepthExpr::parse("(* 1 0)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0050, {
    let got = DepthExpr::parse("(max 1 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0051, {
    let got = DepthExpr::parse("(+ 1 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0052, {
    let got = DepthExpr::parse("(* 1 1)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0053, {
    let got = DepthExpr::parse("(max 1 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0054, {
    let got = DepthExpr::parse("(+ 1 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0055, {
    let got = DepthExpr::parse("(* 1 2)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0056, {
    let got = DepthExpr::parse("(max 1 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0057, {
    let got = DepthExpr::parse("(+ 1 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0058, {
    let got = DepthExpr::parse("(* 1 3)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0059, {
    let got = DepthExpr::parse("(max 1 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0060, {
    let got = DepthExpr::parse("(+ 1 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0061, {
    let got = DepthExpr::parse("(* 1 4)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0062, {
    let got = DepthExpr::parse("(max 1 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0063, {
    let got = DepthExpr::parse("(+ 1 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0064, {
    let got = DepthExpr::parse("(* 1 5)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0065, {
    let got = DepthExpr::parse("(max 1 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0066, {
    let got = DepthExpr::parse("(+ 1 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0067, {
    let got = DepthExpr::parse("(* 1 6)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0068, {
    let got = DepthExpr::parse("(max 1 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0069, {
    let got = DepthExpr::parse("(+ 1 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0070, {
    let got = DepthExpr::parse("(* 1 7)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0071, {
    let got = DepthExpr::parse("(max 1 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0072, {
    let got = DepthExpr::parse("(+ 1 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0073, {
    let got = DepthExpr::parse("(* 1 8)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0074, {
    let got = DepthExpr::parse("(max 1 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0075, {
    let got = DepthExpr::parse("(+ 1 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0076, {
    let got = DepthExpr::parse("(* 1 9)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0077, {
    let got = DepthExpr::parse("(max 1 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0078, {
    let got = DepthExpr::parse("(+ 1 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0079, {
    let got = DepthExpr::parse("(* 1 10)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0080, {
    let got = DepthExpr::parse("(max 1 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0081, {
    let got = DepthExpr::parse("(+ 1 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0082, {
    let got = DepthExpr::parse("(* 1 11)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0083, {
    let got = DepthExpr::parse("(max 1 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0084, {
    let got = DepthExpr::parse("(+ 1 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0085, {
    let got = DepthExpr::parse("(* 1 12)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0086, {
    let got = DepthExpr::parse("(max 1 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0087, {
    let got = DepthExpr::parse("(+ 1 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0088, {
    let got = DepthExpr::parse("(* 1 13)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0089, {
    let got = DepthExpr::parse("(max 1 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0090, {
    let got = DepthExpr::parse("(+ 1 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0091, {
    let got = DepthExpr::parse("(* 1 14)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0092, {
    let got = DepthExpr::parse("(max 1 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0093, {
    let got = DepthExpr::parse("(+ 1 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).seq(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0094, {
    let got = DepthExpr::parse("(* 1 15)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0095, {
    let got = DepthExpr::parse("(max 1 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(1).par(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0096, {
    let got = DepthExpr::parse("(+ 2 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0097, {
    let got = DepthExpr::parse("(* 2 0)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0098, {
    let got = DepthExpr::parse("(max 2 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0099, {
    let got = DepthExpr::parse("(+ 2 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0100, {
    let got = DepthExpr::parse("(* 2 1)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0101, {
    let got = DepthExpr::parse("(max 2 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0102, {
    let got = DepthExpr::parse("(+ 2 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0103, {
    let got = DepthExpr::parse("(* 2 2)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0104, {
    let got = DepthExpr::parse("(max 2 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0105, {
    let got = DepthExpr::parse("(+ 2 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0106, {
    let got = DepthExpr::parse("(* 2 3)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0107, {
    let got = DepthExpr::parse("(max 2 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0108, {
    let got = DepthExpr::parse("(+ 2 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0109, {
    let got = DepthExpr::parse("(* 2 4)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0110, {
    let got = DepthExpr::parse("(max 2 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0111, {
    let got = DepthExpr::parse("(+ 2 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0112, {
    let got = DepthExpr::parse("(* 2 5)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0113, {
    let got = DepthExpr::parse("(max 2 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0114, {
    let got = DepthExpr::parse("(+ 2 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0115, {
    let got = DepthExpr::parse("(* 2 6)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0116, {
    let got = DepthExpr::parse("(max 2 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0117, {
    let got = DepthExpr::parse("(+ 2 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0118, {
    let got = DepthExpr::parse("(* 2 7)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0119, {
    let got = DepthExpr::parse("(max 2 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0120, {
    let got = DepthExpr::parse("(+ 2 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0121, {
    let got = DepthExpr::parse("(* 2 8)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0122, {
    let got = DepthExpr::parse("(max 2 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0123, {
    let got = DepthExpr::parse("(+ 2 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0124, {
    let got = DepthExpr::parse("(* 2 9)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0125, {
    let got = DepthExpr::parse("(max 2 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0126, {
    let got = DepthExpr::parse("(+ 2 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0127, {
    let got = DepthExpr::parse("(* 2 10)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0128, {
    let got = DepthExpr::parse("(max 2 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0129, {
    let got = DepthExpr::parse("(+ 2 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0130, {
    let got = DepthExpr::parse("(* 2 11)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0131, {
    let got = DepthExpr::parse("(max 2 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0132, {
    let got = DepthExpr::parse("(+ 2 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0133, {
    let got = DepthExpr::parse("(* 2 12)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0134, {
    let got = DepthExpr::parse("(max 2 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0135, {
    let got = DepthExpr::parse("(+ 2 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0136, {
    let got = DepthExpr::parse("(* 2 13)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0137, {
    let got = DepthExpr::parse("(max 2 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0138, {
    let got = DepthExpr::parse("(+ 2 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0139, {
    let got = DepthExpr::parse("(* 2 14)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0140, {
    let got = DepthExpr::parse("(max 2 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0141, {
    let got = DepthExpr::parse("(+ 2 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).seq(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0142, {
    let got = DepthExpr::parse("(* 2 15)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0143, {
    let got = DepthExpr::parse("(max 2 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(2).par(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0144, {
    let got = DepthExpr::parse("(+ 3 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0145, {
    let got = DepthExpr::parse("(* 3 0)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0146, {
    let got = DepthExpr::parse("(max 3 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0147, {
    let got = DepthExpr::parse("(+ 3 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0148, {
    let got = DepthExpr::parse("(* 3 1)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0149, {
    let got = DepthExpr::parse("(max 3 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0150, {
    let got = DepthExpr::parse("(+ 3 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0151, {
    let got = DepthExpr::parse("(* 3 2)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0152, {
    let got = DepthExpr::parse("(max 3 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0153, {
    let got = DepthExpr::parse("(+ 3 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0154, {
    let got = DepthExpr::parse("(* 3 3)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0155, {
    let got = DepthExpr::parse("(max 3 3)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(3))));
});
audit_case!(depth_bin_0156, {
    let got = DepthExpr::parse("(+ 3 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0157, {
    let got = DepthExpr::parse("(* 3 4)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0158, {
    let got = DepthExpr::parse("(max 3 4)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(4))));
});
audit_case!(depth_bin_0159, {
    let got = DepthExpr::parse("(+ 3 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0160, {
    let got = DepthExpr::parse("(* 3 5)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0161, {
    let got = DepthExpr::parse("(max 3 5)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(5))));
});
audit_case!(depth_bin_0162, {
    let got = DepthExpr::parse("(+ 3 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0163, {
    let got = DepthExpr::parse("(* 3 6)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0164, {
    let got = DepthExpr::parse("(max 3 6)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(6))));
});
audit_case!(depth_bin_0165, {
    let got = DepthExpr::parse("(+ 3 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0166, {
    let got = DepthExpr::parse("(* 3 7)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0167, {
    let got = DepthExpr::parse("(max 3 7)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(7))));
});
audit_case!(depth_bin_0168, {
    let got = DepthExpr::parse("(+ 3 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0169, {
    let got = DepthExpr::parse("(* 3 8)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0170, {
    let got = DepthExpr::parse("(max 3 8)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(8))));
});
audit_case!(depth_bin_0171, {
    let got = DepthExpr::parse("(+ 3 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0172, {
    let got = DepthExpr::parse("(* 3 9)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0173, {
    let got = DepthExpr::parse("(max 3 9)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(9))));
});
audit_case!(depth_bin_0174, {
    let got = DepthExpr::parse("(+ 3 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0175, {
    let got = DepthExpr::parse("(* 3 10)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0176, {
    let got = DepthExpr::parse("(max 3 10)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(10))));
});
audit_case!(depth_bin_0177, {
    let got = DepthExpr::parse("(+ 3 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0178, {
    let got = DepthExpr::parse("(* 3 11)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0179, {
    let got = DepthExpr::parse("(max 3 11)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(11))));
});
audit_case!(depth_bin_0180, {
    let got = DepthExpr::parse("(+ 3 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0181, {
    let got = DepthExpr::parse("(* 3 12)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0182, {
    let got = DepthExpr::parse("(max 3 12)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(12))));
});
audit_case!(depth_bin_0183, {
    let got = DepthExpr::parse("(+ 3 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0184, {
    let got = DepthExpr::parse("(* 3 13)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0185, {
    let got = DepthExpr::parse("(max 3 13)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(13))));
});
audit_case!(depth_bin_0186, {
    let got = DepthExpr::parse("(+ 3 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0187, {
    let got = DepthExpr::parse("(* 3 14)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0188, {
    let got = DepthExpr::parse("(max 3 14)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(14))));
});
audit_case!(depth_bin_0189, {
    let got = DepthExpr::parse("(+ 3 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).seq(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0190, {
    let got = DepthExpr::parse("(* 3 15)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0191, {
    let got = DepthExpr::parse("(max 3 15)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(3).par(DepthExpr::Nat(15))));
});
audit_case!(depth_bin_0192, {
    let got = DepthExpr::parse("(+ 4 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(4).seq(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0193, {
    let got = DepthExpr::parse("(* 4 0)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0194, {
    let got = DepthExpr::parse("(max 4 0)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(4).par(DepthExpr::Nat(0))));
});
audit_case!(depth_bin_0195, {
    let got = DepthExpr::parse("(+ 4 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(4).seq(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0196, {
    let got = DepthExpr::parse("(* 4 1)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0197, {
    let got = DepthExpr::parse("(max 4 1)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(4).par(DepthExpr::Nat(1))));
});
audit_case!(depth_bin_0198, {
    let got = DepthExpr::parse("(+ 4 2)").unwrap();
    assert!(got.equiv(&DepthExpr::Nat(4).seq(DepthExpr::Nat(2))));
});
audit_case!(depth_bin_0199, {
    let got = DepthExpr::parse("(* 4 2)").unwrap();
    assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(2))));
});
audit_case!(depth_err_0000, {
    assert!(DepthExpr::parse("").is_err());
});
audit_case!(depth_err_0001, {
    assert!(DepthExpr::parse(" ").is_err());
});
audit_case!(depth_err_0002, {
    assert!(DepthExpr::parse("(").is_err());
});
audit_case!(depth_err_0003, {
    assert!(DepthExpr::parse("(+ 1").is_err());
});
audit_case!(depth_err_0004, {
    assert!(DepthExpr::parse("(+ 1 2 3)").is_err());
});
audit_case!(depth_err_0005, {
    assert!(DepthExpr::parse("(foo 1 2)").is_err());
});
audit_case!(depth_err_0006, {
    assert!(DepthExpr::parse("(+ a b) extra").is_err());
});
audit_case!(depth_err_0007, {
    assert!(DepthExpr::parse("(max)").is_err());
});
audit_case!(depth_err_0008, {
    assert!(DepthExpr::parse("(+)").is_err());
});
audit_case!(depth_err_0009, {
    assert!(DepthExpr::parse("(1 2)").is_err());
});
audit_case!(depth_err_0010, {
    assert!(DepthExpr::parse("(unknown 1 2)").is_err());
});
audit_case!(depth_div_by_zero_parses, {
    assert_eq!(
        DepthExpr::parse("(/ 1 0)"),
        Ok(DepthExpr::Nat(1).quot(DepthExpr::Nat(0)))
    );
});
audit_case!(depth_trail_0000, {
    assert_eq!(
        DepthExpr::parse("1 2"),
        Err(DepthParseError::TrailingTokens)
    );
});
audit_case!(depth_trail_0001, {
    assert_eq!(
        DepthExpr::parse("n n"),
        Err(DepthParseError::TrailingTokens)
    );
});
audit_case!(depth_trail_0002, {
    assert_eq!(
        DepthExpr::parse("(+ 1 2) 3"),
        Err(DepthParseError::TrailingTokens)
    );
});
audit_case!(depth_trail_0003, {
    assert_eq!(
        DepthExpr::parse("42 junk"),
        Err(DepthParseError::TrailingTokens)
    );
});
