// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `quon_core` — `depth as_const`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use quon_core::DepthExpr;

audit_case!(const_add_00_00, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(0)).as_const(), Some(0));
});
audit_case!(const_add_00_01, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(1)).as_const(), Some(1));
});
audit_case!(const_add_00_02, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(2)).as_const(), Some(2));
});
audit_case!(const_add_00_03, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(3)).as_const(), Some(3));
});
audit_case!(const_add_00_04, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_add_00_05, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_add_00_06, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_add_00_07, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_add_00_08, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_add_00_09, {
    assert_eq!(DepthExpr::Nat(0).seq(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_add_00_10, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_00_11, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_00_12, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(12)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_00_13, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(13)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_00_14, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(14)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_00_15, {
    assert_eq!(
        DepthExpr::Nat(0).seq(DepthExpr::Nat(15)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_01_00, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(0)).as_const(), Some(1));
});
audit_case!(const_add_01_01, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(1)).as_const(), Some(2));
});
audit_case!(const_add_01_02, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(2)).as_const(), Some(3));
});
audit_case!(const_add_01_03, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(3)).as_const(), Some(4));
});
audit_case!(const_add_01_04, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(4)).as_const(), Some(5));
});
audit_case!(const_add_01_05, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(5)).as_const(), Some(6));
});
audit_case!(const_add_01_06, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(6)).as_const(), Some(7));
});
audit_case!(const_add_01_07, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(7)).as_const(), Some(8));
});
audit_case!(const_add_01_08, {
    assert_eq!(DepthExpr::Nat(1).seq(DepthExpr::Nat(8)).as_const(), Some(9));
});
audit_case!(const_add_01_09, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(9)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_01_10, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(10)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_01_11, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(11)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_01_12, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(12)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_01_13, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(13)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_01_14, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(14)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_01_15, {
    assert_eq!(
        DepthExpr::Nat(1).seq(DepthExpr::Nat(15)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_02_00, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(0)).as_const(), Some(2));
});
audit_case!(const_add_02_01, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(1)).as_const(), Some(3));
});
audit_case!(const_add_02_02, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(2)).as_const(), Some(4));
});
audit_case!(const_add_02_03, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(3)).as_const(), Some(5));
});
audit_case!(const_add_02_04, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(4)).as_const(), Some(6));
});
audit_case!(const_add_02_05, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(5)).as_const(), Some(7));
});
audit_case!(const_add_02_06, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(6)).as_const(), Some(8));
});
audit_case!(const_add_02_07, {
    assert_eq!(DepthExpr::Nat(2).seq(DepthExpr::Nat(7)).as_const(), Some(9));
});
audit_case!(const_add_02_08, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(8)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_02_09, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(9)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_02_10, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(10)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_02_11, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(11)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_02_12, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(12)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_02_13, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(13)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_02_14, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(14)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_02_15, {
    assert_eq!(
        DepthExpr::Nat(2).seq(DepthExpr::Nat(15)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_03_00, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(0)).as_const(), Some(3));
});
audit_case!(const_add_03_01, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(1)).as_const(), Some(4));
});
audit_case!(const_add_03_02, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(2)).as_const(), Some(5));
});
audit_case!(const_add_03_03, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(3)).as_const(), Some(6));
});
audit_case!(const_add_03_04, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(4)).as_const(), Some(7));
});
audit_case!(const_add_03_05, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(5)).as_const(), Some(8));
});
audit_case!(const_add_03_06, {
    assert_eq!(DepthExpr::Nat(3).seq(DepthExpr::Nat(6)).as_const(), Some(9));
});
audit_case!(const_add_03_07, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(7)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_03_08, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(8)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_03_09, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(9)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_03_10, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(10)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_03_11, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(11)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_03_12, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(12)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_03_13, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(13)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_03_14, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(14)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_03_15, {
    assert_eq!(
        DepthExpr::Nat(3).seq(DepthExpr::Nat(15)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_04_00, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(0)).as_const(), Some(4));
});
audit_case!(const_add_04_01, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(1)).as_const(), Some(5));
});
audit_case!(const_add_04_02, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(2)).as_const(), Some(6));
});
audit_case!(const_add_04_03, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(3)).as_const(), Some(7));
});
audit_case!(const_add_04_04, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(4)).as_const(), Some(8));
});
audit_case!(const_add_04_05, {
    assert_eq!(DepthExpr::Nat(4).seq(DepthExpr::Nat(5)).as_const(), Some(9));
});
audit_case!(const_add_04_06, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(6)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_04_07, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(7)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_04_08, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(8)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_04_09, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(9)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_04_10, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(10)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_04_11, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(11)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_04_12, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(12)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_04_13, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(13)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_04_14, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(14)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_04_15, {
    assert_eq!(
        DepthExpr::Nat(4).seq(DepthExpr::Nat(15)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_05_00, {
    assert_eq!(DepthExpr::Nat(5).seq(DepthExpr::Nat(0)).as_const(), Some(5));
});
audit_case!(const_add_05_01, {
    assert_eq!(DepthExpr::Nat(5).seq(DepthExpr::Nat(1)).as_const(), Some(6));
});
audit_case!(const_add_05_02, {
    assert_eq!(DepthExpr::Nat(5).seq(DepthExpr::Nat(2)).as_const(), Some(7));
});
audit_case!(const_add_05_03, {
    assert_eq!(DepthExpr::Nat(5).seq(DepthExpr::Nat(3)).as_const(), Some(8));
});
audit_case!(const_add_05_04, {
    assert_eq!(DepthExpr::Nat(5).seq(DepthExpr::Nat(4)).as_const(), Some(9));
});
audit_case!(const_add_05_05, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(5)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_05_06, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(6)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_05_07, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(7)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_05_08, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(8)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_05_09, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(9)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_05_10, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(10)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_05_11, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(11)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_05_12, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(12)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_05_13, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(13)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_05_14, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(14)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_05_15, {
    assert_eq!(
        DepthExpr::Nat(5).seq(DepthExpr::Nat(15)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_06_00, {
    assert_eq!(DepthExpr::Nat(6).seq(DepthExpr::Nat(0)).as_const(), Some(6));
});
audit_case!(const_add_06_01, {
    assert_eq!(DepthExpr::Nat(6).seq(DepthExpr::Nat(1)).as_const(), Some(7));
});
audit_case!(const_add_06_02, {
    assert_eq!(DepthExpr::Nat(6).seq(DepthExpr::Nat(2)).as_const(), Some(8));
});
audit_case!(const_add_06_03, {
    assert_eq!(DepthExpr::Nat(6).seq(DepthExpr::Nat(3)).as_const(), Some(9));
});
audit_case!(const_add_06_04, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(4)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_06_05, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(5)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_06_06, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(6)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_06_07, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(7)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_06_08, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(8)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_06_09, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(9)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_06_10, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(10)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_06_11, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(11)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_06_12, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(12)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_06_13, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(13)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_06_14, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(14)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_06_15, {
    assert_eq!(
        DepthExpr::Nat(6).seq(DepthExpr::Nat(15)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_07_00, {
    assert_eq!(DepthExpr::Nat(7).seq(DepthExpr::Nat(0)).as_const(), Some(7));
});
audit_case!(const_add_07_01, {
    assert_eq!(DepthExpr::Nat(7).seq(DepthExpr::Nat(1)).as_const(), Some(8));
});
audit_case!(const_add_07_02, {
    assert_eq!(DepthExpr::Nat(7).seq(DepthExpr::Nat(2)).as_const(), Some(9));
});
audit_case!(const_add_07_03, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(3)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_07_04, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(4)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_07_05, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(5)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_07_06, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(6)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_07_07, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(7)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_07_08, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(8)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_07_09, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(9)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_07_10, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(10)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_07_11, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(11)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_07_12, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(12)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_07_13, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(13)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_07_14, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(14)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_07_15, {
    assert_eq!(
        DepthExpr::Nat(7).seq(DepthExpr::Nat(15)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_08_00, {
    assert_eq!(DepthExpr::Nat(8).seq(DepthExpr::Nat(0)).as_const(), Some(8));
});
audit_case!(const_add_08_01, {
    assert_eq!(DepthExpr::Nat(8).seq(DepthExpr::Nat(1)).as_const(), Some(9));
});
audit_case!(const_add_08_02, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(2)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_08_03, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(3)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_08_04, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(4)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_08_05, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(5)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_08_06, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(6)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_08_07, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(7)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_08_08, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(8)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_08_09, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(9)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_08_10, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(10)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_08_11, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(11)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_08_12, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(12)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_08_13, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(13)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_08_14, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(14)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_08_15, {
    assert_eq!(
        DepthExpr::Nat(8).seq(DepthExpr::Nat(15)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_09_00, {
    assert_eq!(DepthExpr::Nat(9).seq(DepthExpr::Nat(0)).as_const(), Some(9));
});
audit_case!(const_add_09_01, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(1)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_09_02, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(2)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_09_03, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(3)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_09_04, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(4)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_09_05, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(5)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_09_06, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(6)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_09_07, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(7)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_09_08, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(8)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_09_09, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(9)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_09_10, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(10)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_09_11, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(11)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_09_12, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(12)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_09_13, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(13)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_09_14, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(14)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_09_15, {
    assert_eq!(
        DepthExpr::Nat(9).seq(DepthExpr::Nat(15)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_10_00, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(0)).as_const(),
        Some(10)
    );
});
audit_case!(const_add_10_01, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(1)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_10_02, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(2)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_10_03, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(3)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_10_04, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(4)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_10_05, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(5)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_10_06, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(6)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_10_07, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(7)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_10_08, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(8)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_10_09, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(9)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_10_10, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(10)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_10_11, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(11)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_10_12, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(12)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_10_13, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(13)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_10_14, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(14)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_10_15, {
    assert_eq!(
        DepthExpr::Nat(10).seq(DepthExpr::Nat(15)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_11_00, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(0)).as_const(),
        Some(11)
    );
});
audit_case!(const_add_11_01, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(1)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_11_02, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(2)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_11_03, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(3)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_11_04, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(4)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_11_05, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(5)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_11_06, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(6)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_11_07, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(7)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_11_08, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(8)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_11_09, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(9)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_11_10, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(10)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_11_11, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(11)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_11_12, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(12)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_11_13, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(13)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_11_14, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(14)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_11_15, {
    assert_eq!(
        DepthExpr::Nat(11).seq(DepthExpr::Nat(15)).as_const(),
        Some(26)
    );
});
audit_case!(const_add_12_00, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(0)).as_const(),
        Some(12)
    );
});
audit_case!(const_add_12_01, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(1)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_12_02, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(2)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_12_03, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(3)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_12_04, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(4)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_12_05, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(5)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_12_06, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(6)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_12_07, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(7)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_12_08, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(8)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_12_09, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(9)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_12_10, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(10)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_12_11, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(11)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_12_12, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(12)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_12_13, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(13)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_12_14, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(14)).as_const(),
        Some(26)
    );
});
audit_case!(const_add_12_15, {
    assert_eq!(
        DepthExpr::Nat(12).seq(DepthExpr::Nat(15)).as_const(),
        Some(27)
    );
});
audit_case!(const_add_13_00, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(0)).as_const(),
        Some(13)
    );
});
audit_case!(const_add_13_01, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(1)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_13_02, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(2)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_13_03, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(3)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_13_04, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(4)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_13_05, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(5)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_13_06, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(6)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_13_07, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(7)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_13_08, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(8)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_13_09, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(9)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_13_10, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(10)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_13_11, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(11)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_13_12, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(12)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_13_13, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(13)).as_const(),
        Some(26)
    );
});
audit_case!(const_add_13_14, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(14)).as_const(),
        Some(27)
    );
});
audit_case!(const_add_13_15, {
    assert_eq!(
        DepthExpr::Nat(13).seq(DepthExpr::Nat(15)).as_const(),
        Some(28)
    );
});
audit_case!(const_add_14_00, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(0)).as_const(),
        Some(14)
    );
});
audit_case!(const_add_14_01, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(1)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_14_02, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(2)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_14_03, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(3)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_14_04, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(4)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_14_05, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(5)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_14_06, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(6)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_14_07, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(7)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_14_08, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(8)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_14_09, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(9)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_14_10, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(10)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_14_11, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(11)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_14_12, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(12)).as_const(),
        Some(26)
    );
});
audit_case!(const_add_14_13, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(13)).as_const(),
        Some(27)
    );
});
audit_case!(const_add_14_14, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(14)).as_const(),
        Some(28)
    );
});
audit_case!(const_add_14_15, {
    assert_eq!(
        DepthExpr::Nat(14).seq(DepthExpr::Nat(15)).as_const(),
        Some(29)
    );
});
audit_case!(const_add_15_00, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(0)).as_const(),
        Some(15)
    );
});
audit_case!(const_add_15_01, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(1)).as_const(),
        Some(16)
    );
});
audit_case!(const_add_15_02, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(2)).as_const(),
        Some(17)
    );
});
audit_case!(const_add_15_03, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(3)).as_const(),
        Some(18)
    );
});
audit_case!(const_add_15_04, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(4)).as_const(),
        Some(19)
    );
});
audit_case!(const_add_15_05, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(5)).as_const(),
        Some(20)
    );
});
audit_case!(const_add_15_06, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(6)).as_const(),
        Some(21)
    );
});
audit_case!(const_add_15_07, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(7)).as_const(),
        Some(22)
    );
});
audit_case!(const_add_15_08, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(8)).as_const(),
        Some(23)
    );
});
audit_case!(const_add_15_09, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(9)).as_const(),
        Some(24)
    );
});
audit_case!(const_add_15_10, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(10)).as_const(),
        Some(25)
    );
});
audit_case!(const_add_15_11, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(11)).as_const(),
        Some(26)
    );
});
audit_case!(const_add_15_12, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(12)).as_const(),
        Some(27)
    );
});
audit_case!(const_add_15_13, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(13)).as_const(),
        Some(28)
    );
});
audit_case!(const_add_15_14, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(14)).as_const(),
        Some(29)
    );
});
audit_case!(const_add_15_15, {
    assert_eq!(
        DepthExpr::Nat(15).seq(DepthExpr::Nat(15)).as_const(),
        Some(30)
    );
});
audit_case!(const_mul_00_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(1)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(2)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(3)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(4)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_00_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(0), DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_01_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_01_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(1)).as_const(),
        Some(1)
    );
});
audit_case!(const_mul_01_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(2)).as_const(),
        Some(2)
    );
});
audit_case!(const_mul_01_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(3)).as_const(),
        Some(3)
    );
});
audit_case!(const_mul_01_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(4)).as_const(),
        Some(4)
    );
});
audit_case!(const_mul_01_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(5)).as_const(),
        Some(5)
    );
});
audit_case!(const_mul_01_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(6)).as_const(),
        Some(6)
    );
});
audit_case!(const_mul_01_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(7)).as_const(),
        Some(7)
    );
});
audit_case!(const_mul_01_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(8)).as_const(),
        Some(8)
    );
});
audit_case!(const_mul_01_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(9)).as_const(),
        Some(9)
    );
});
audit_case!(const_mul_01_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_mul_01_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(1), DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_mul_02_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_02_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(1)).as_const(),
        Some(2)
    );
});
audit_case!(const_mul_02_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(2)).as_const(),
        Some(4)
    );
});
audit_case!(const_mul_02_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(3)).as_const(),
        Some(6)
    );
});
audit_case!(const_mul_02_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(4)).as_const(),
        Some(8)
    );
});
audit_case!(const_mul_02_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(5)).as_const(),
        Some(10)
    );
});
audit_case!(const_mul_02_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(6)).as_const(),
        Some(12)
    );
});
audit_case!(const_mul_02_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(7)).as_const(),
        Some(14)
    );
});
audit_case!(const_mul_02_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(8)).as_const(),
        Some(16)
    );
});
audit_case!(const_mul_02_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(9)).as_const(),
        Some(18)
    );
});
audit_case!(const_mul_02_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(10)).as_const(),
        Some(20)
    );
});
audit_case!(const_mul_02_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(2), DepthExpr::Nat(11)).as_const(),
        Some(22)
    );
});
audit_case!(const_mul_03_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_03_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(1)).as_const(),
        Some(3)
    );
});
audit_case!(const_mul_03_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(2)).as_const(),
        Some(6)
    );
});
audit_case!(const_mul_03_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(3)).as_const(),
        Some(9)
    );
});
audit_case!(const_mul_03_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(4)).as_const(),
        Some(12)
    );
});
audit_case!(const_mul_03_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(5)).as_const(),
        Some(15)
    );
});
audit_case!(const_mul_03_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(6)).as_const(),
        Some(18)
    );
});
audit_case!(const_mul_03_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(7)).as_const(),
        Some(21)
    );
});
audit_case!(const_mul_03_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(8)).as_const(),
        Some(24)
    );
});
audit_case!(const_mul_03_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(9)).as_const(),
        Some(27)
    );
});
audit_case!(const_mul_03_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(10)).as_const(),
        Some(30)
    );
});
audit_case!(const_mul_03_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(3), DepthExpr::Nat(11)).as_const(),
        Some(33)
    );
});
audit_case!(const_mul_04_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_04_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(1)).as_const(),
        Some(4)
    );
});
audit_case!(const_mul_04_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(2)).as_const(),
        Some(8)
    );
});
audit_case!(const_mul_04_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(3)).as_const(),
        Some(12)
    );
});
audit_case!(const_mul_04_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(4)).as_const(),
        Some(16)
    );
});
audit_case!(const_mul_04_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(5)).as_const(),
        Some(20)
    );
});
audit_case!(const_mul_04_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(6)).as_const(),
        Some(24)
    );
});
audit_case!(const_mul_04_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(7)).as_const(),
        Some(28)
    );
});
audit_case!(const_mul_04_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(8)).as_const(),
        Some(32)
    );
});
audit_case!(const_mul_04_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(9)).as_const(),
        Some(36)
    );
});
audit_case!(const_mul_04_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(10)).as_const(),
        Some(40)
    );
});
audit_case!(const_mul_04_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(4), DepthExpr::Nat(11)).as_const(),
        Some(44)
    );
});
audit_case!(const_mul_05_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_05_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(1)).as_const(),
        Some(5)
    );
});
audit_case!(const_mul_05_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(2)).as_const(),
        Some(10)
    );
});
audit_case!(const_mul_05_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(3)).as_const(),
        Some(15)
    );
});
audit_case!(const_mul_05_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(4)).as_const(),
        Some(20)
    );
});
audit_case!(const_mul_05_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(5)).as_const(),
        Some(25)
    );
});
audit_case!(const_mul_05_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(6)).as_const(),
        Some(30)
    );
});
audit_case!(const_mul_05_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(7)).as_const(),
        Some(35)
    );
});
audit_case!(const_mul_05_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(8)).as_const(),
        Some(40)
    );
});
audit_case!(const_mul_05_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(9)).as_const(),
        Some(45)
    );
});
audit_case!(const_mul_05_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(10)).as_const(),
        Some(50)
    );
});
audit_case!(const_mul_05_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(5), DepthExpr::Nat(11)).as_const(),
        Some(55)
    );
});
audit_case!(const_mul_06_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_06_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(1)).as_const(),
        Some(6)
    );
});
audit_case!(const_mul_06_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(2)).as_const(),
        Some(12)
    );
});
audit_case!(const_mul_06_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(3)).as_const(),
        Some(18)
    );
});
audit_case!(const_mul_06_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(4)).as_const(),
        Some(24)
    );
});
audit_case!(const_mul_06_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(5)).as_const(),
        Some(30)
    );
});
audit_case!(const_mul_06_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(6)).as_const(),
        Some(36)
    );
});
audit_case!(const_mul_06_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(7)).as_const(),
        Some(42)
    );
});
audit_case!(const_mul_06_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(8)).as_const(),
        Some(48)
    );
});
audit_case!(const_mul_06_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(9)).as_const(),
        Some(54)
    );
});
audit_case!(const_mul_06_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(10)).as_const(),
        Some(60)
    );
});
audit_case!(const_mul_06_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(6), DepthExpr::Nat(11)).as_const(),
        Some(66)
    );
});
audit_case!(const_mul_07_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_07_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(1)).as_const(),
        Some(7)
    );
});
audit_case!(const_mul_07_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(2)).as_const(),
        Some(14)
    );
});
audit_case!(const_mul_07_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(3)).as_const(),
        Some(21)
    );
});
audit_case!(const_mul_07_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(4)).as_const(),
        Some(28)
    );
});
audit_case!(const_mul_07_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(5)).as_const(),
        Some(35)
    );
});
audit_case!(const_mul_07_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(6)).as_const(),
        Some(42)
    );
});
audit_case!(const_mul_07_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(7)).as_const(),
        Some(49)
    );
});
audit_case!(const_mul_07_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(8)).as_const(),
        Some(56)
    );
});
audit_case!(const_mul_07_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(9)).as_const(),
        Some(63)
    );
});
audit_case!(const_mul_07_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(10)).as_const(),
        Some(70)
    );
});
audit_case!(const_mul_07_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(7), DepthExpr::Nat(11)).as_const(),
        Some(77)
    );
});
audit_case!(const_mul_08_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_08_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(1)).as_const(),
        Some(8)
    );
});
audit_case!(const_mul_08_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(2)).as_const(),
        Some(16)
    );
});
audit_case!(const_mul_08_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(3)).as_const(),
        Some(24)
    );
});
audit_case!(const_mul_08_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(4)).as_const(),
        Some(32)
    );
});
audit_case!(const_mul_08_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(5)).as_const(),
        Some(40)
    );
});
audit_case!(const_mul_08_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(6)).as_const(),
        Some(48)
    );
});
audit_case!(const_mul_08_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(7)).as_const(),
        Some(56)
    );
});
audit_case!(const_mul_08_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(8)).as_const(),
        Some(64)
    );
});
audit_case!(const_mul_08_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(9)).as_const(),
        Some(72)
    );
});
audit_case!(const_mul_08_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(10)).as_const(),
        Some(80)
    );
});
audit_case!(const_mul_08_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(8), DepthExpr::Nat(11)).as_const(),
        Some(88)
    );
});
audit_case!(const_mul_09_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_09_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(1)).as_const(),
        Some(9)
    );
});
audit_case!(const_mul_09_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(2)).as_const(),
        Some(18)
    );
});
audit_case!(const_mul_09_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(3)).as_const(),
        Some(27)
    );
});
audit_case!(const_mul_09_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(4)).as_const(),
        Some(36)
    );
});
audit_case!(const_mul_09_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(5)).as_const(),
        Some(45)
    );
});
audit_case!(const_mul_09_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(6)).as_const(),
        Some(54)
    );
});
audit_case!(const_mul_09_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(7)).as_const(),
        Some(63)
    );
});
audit_case!(const_mul_09_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(8)).as_const(),
        Some(72)
    );
});
audit_case!(const_mul_09_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(9)).as_const(),
        Some(81)
    );
});
audit_case!(const_mul_09_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(10)).as_const(),
        Some(90)
    );
});
audit_case!(const_mul_09_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(9), DepthExpr::Nat(11)).as_const(),
        Some(99)
    );
});
audit_case!(const_mul_10_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_10_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(1)).as_const(),
        Some(10)
    );
});
audit_case!(const_mul_10_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(2)).as_const(),
        Some(20)
    );
});
audit_case!(const_mul_10_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(3)).as_const(),
        Some(30)
    );
});
audit_case!(const_mul_10_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(4)).as_const(),
        Some(40)
    );
});
audit_case!(const_mul_10_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(5)).as_const(),
        Some(50)
    );
});
audit_case!(const_mul_10_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(6)).as_const(),
        Some(60)
    );
});
audit_case!(const_mul_10_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(7)).as_const(),
        Some(70)
    );
});
audit_case!(const_mul_10_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(8)).as_const(),
        Some(80)
    );
});
audit_case!(const_mul_10_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(9)).as_const(),
        Some(90)
    );
});
audit_case!(const_mul_10_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(10)).as_const(),
        Some(100)
    );
});
audit_case!(const_mul_10_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(10), DepthExpr::Nat(11)).as_const(),
        Some(110)
    );
});
audit_case!(const_mul_11_00, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(0)).as_const(),
        Some(0)
    );
});
audit_case!(const_mul_11_01, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(1)).as_const(),
        Some(11)
    );
});
audit_case!(const_mul_11_02, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(2)).as_const(),
        Some(22)
    );
});
audit_case!(const_mul_11_03, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(3)).as_const(),
        Some(33)
    );
});
audit_case!(const_mul_11_04, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(4)).as_const(),
        Some(44)
    );
});
audit_case!(const_mul_11_05, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(5)).as_const(),
        Some(55)
    );
});
audit_case!(const_mul_11_06, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(6)).as_const(),
        Some(66)
    );
});
audit_case!(const_mul_11_07, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(7)).as_const(),
        Some(77)
    );
});
audit_case!(const_mul_11_08, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(8)).as_const(),
        Some(88)
    );
});
audit_case!(const_mul_11_09, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(9)).as_const(),
        Some(99)
    );
});
audit_case!(const_mul_11_10, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(10)).as_const(),
        Some(110)
    );
});
audit_case!(const_mul_11_11, {
    assert_eq!(
        DepthExpr::repeat(DepthExpr::Nat(11), DepthExpr::Nat(11)).as_const(),
        Some(121)
    );
});
audit_case!(const_max_00_00, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(0)).as_const(), Some(0));
});
audit_case!(const_max_00_01, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(1)).as_const(), Some(1));
});
audit_case!(const_max_00_02, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(2)).as_const(), Some(2));
});
audit_case!(const_max_00_03, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(3)).as_const(), Some(3));
});
audit_case!(const_max_00_04, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_max_00_05, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_00_06, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_00_07, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_00_08, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_00_09, {
    assert_eq!(DepthExpr::Nat(0).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_00_10, {
    assert_eq!(
        DepthExpr::Nat(0).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_00_11, {
    assert_eq!(
        DepthExpr::Nat(0).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_01_00, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(0)).as_const(), Some(1));
});
audit_case!(const_max_01_01, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(1)).as_const(), Some(1));
});
audit_case!(const_max_01_02, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(2)).as_const(), Some(2));
});
audit_case!(const_max_01_03, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(3)).as_const(), Some(3));
});
audit_case!(const_max_01_04, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_max_01_05, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_01_06, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_01_07, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_01_08, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_01_09, {
    assert_eq!(DepthExpr::Nat(1).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_01_10, {
    assert_eq!(
        DepthExpr::Nat(1).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_01_11, {
    assert_eq!(
        DepthExpr::Nat(1).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_02_00, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(0)).as_const(), Some(2));
});
audit_case!(const_max_02_01, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(1)).as_const(), Some(2));
});
audit_case!(const_max_02_02, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(2)).as_const(), Some(2));
});
audit_case!(const_max_02_03, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(3)).as_const(), Some(3));
});
audit_case!(const_max_02_04, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_max_02_05, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_02_06, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_02_07, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_02_08, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_02_09, {
    assert_eq!(DepthExpr::Nat(2).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_02_10, {
    assert_eq!(
        DepthExpr::Nat(2).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_02_11, {
    assert_eq!(
        DepthExpr::Nat(2).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_03_00, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(0)).as_const(), Some(3));
});
audit_case!(const_max_03_01, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(1)).as_const(), Some(3));
});
audit_case!(const_max_03_02, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(2)).as_const(), Some(3));
});
audit_case!(const_max_03_03, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(3)).as_const(), Some(3));
});
audit_case!(const_max_03_04, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_max_03_05, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_03_06, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_03_07, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_03_08, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_03_09, {
    assert_eq!(DepthExpr::Nat(3).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_03_10, {
    assert_eq!(
        DepthExpr::Nat(3).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_03_11, {
    assert_eq!(
        DepthExpr::Nat(3).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_04_00, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(0)).as_const(), Some(4));
});
audit_case!(const_max_04_01, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(1)).as_const(), Some(4));
});
audit_case!(const_max_04_02, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(2)).as_const(), Some(4));
});
audit_case!(const_max_04_03, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(3)).as_const(), Some(4));
});
audit_case!(const_max_04_04, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(4)).as_const(), Some(4));
});
audit_case!(const_max_04_05, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_04_06, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_04_07, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_04_08, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_04_09, {
    assert_eq!(DepthExpr::Nat(4).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_04_10, {
    assert_eq!(
        DepthExpr::Nat(4).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_04_11, {
    assert_eq!(
        DepthExpr::Nat(4).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_05_00, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(0)).as_const(), Some(5));
});
audit_case!(const_max_05_01, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(1)).as_const(), Some(5));
});
audit_case!(const_max_05_02, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(2)).as_const(), Some(5));
});
audit_case!(const_max_05_03, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(3)).as_const(), Some(5));
});
audit_case!(const_max_05_04, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(4)).as_const(), Some(5));
});
audit_case!(const_max_05_05, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(5)).as_const(), Some(5));
});
audit_case!(const_max_05_06, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_05_07, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_05_08, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_05_09, {
    assert_eq!(DepthExpr::Nat(5).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_05_10, {
    assert_eq!(
        DepthExpr::Nat(5).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_05_11, {
    assert_eq!(
        DepthExpr::Nat(5).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_06_00, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(0)).as_const(), Some(6));
});
audit_case!(const_max_06_01, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(1)).as_const(), Some(6));
});
audit_case!(const_max_06_02, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(2)).as_const(), Some(6));
});
audit_case!(const_max_06_03, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(3)).as_const(), Some(6));
});
audit_case!(const_max_06_04, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(4)).as_const(), Some(6));
});
audit_case!(const_max_06_05, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(5)).as_const(), Some(6));
});
audit_case!(const_max_06_06, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(6)).as_const(), Some(6));
});
audit_case!(const_max_06_07, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_06_08, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_06_09, {
    assert_eq!(DepthExpr::Nat(6).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_06_10, {
    assert_eq!(
        DepthExpr::Nat(6).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_06_11, {
    assert_eq!(
        DepthExpr::Nat(6).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_07_00, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(0)).as_const(), Some(7));
});
audit_case!(const_max_07_01, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(1)).as_const(), Some(7));
});
audit_case!(const_max_07_02, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(2)).as_const(), Some(7));
});
audit_case!(const_max_07_03, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(3)).as_const(), Some(7));
});
audit_case!(const_max_07_04, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(4)).as_const(), Some(7));
});
audit_case!(const_max_07_05, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(5)).as_const(), Some(7));
});
audit_case!(const_max_07_06, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(6)).as_const(), Some(7));
});
audit_case!(const_max_07_07, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(7)).as_const(), Some(7));
});
audit_case!(const_max_07_08, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_07_09, {
    assert_eq!(DepthExpr::Nat(7).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_07_10, {
    assert_eq!(
        DepthExpr::Nat(7).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_07_11, {
    assert_eq!(
        DepthExpr::Nat(7).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_08_00, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(0)).as_const(), Some(8));
});
audit_case!(const_max_08_01, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(1)).as_const(), Some(8));
});
audit_case!(const_max_08_02, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(2)).as_const(), Some(8));
});
audit_case!(const_max_08_03, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(3)).as_const(), Some(8));
});
audit_case!(const_max_08_04, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(4)).as_const(), Some(8));
});
audit_case!(const_max_08_05, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(5)).as_const(), Some(8));
});
audit_case!(const_max_08_06, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(6)).as_const(), Some(8));
});
audit_case!(const_max_08_07, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(7)).as_const(), Some(8));
});
audit_case!(const_max_08_08, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(8)).as_const(), Some(8));
});
audit_case!(const_max_08_09, {
    assert_eq!(DepthExpr::Nat(8).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_08_10, {
    assert_eq!(
        DepthExpr::Nat(8).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_08_11, {
    assert_eq!(
        DepthExpr::Nat(8).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_09_00, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(0)).as_const(), Some(9));
});
audit_case!(const_max_09_01, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(1)).as_const(), Some(9));
});
audit_case!(const_max_09_02, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(2)).as_const(), Some(9));
});
audit_case!(const_max_09_03, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(3)).as_const(), Some(9));
});
audit_case!(const_max_09_04, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(4)).as_const(), Some(9));
});
audit_case!(const_max_09_05, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(5)).as_const(), Some(9));
});
audit_case!(const_max_09_06, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(6)).as_const(), Some(9));
});
audit_case!(const_max_09_07, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(7)).as_const(), Some(9));
});
audit_case!(const_max_09_08, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(8)).as_const(), Some(9));
});
audit_case!(const_max_09_09, {
    assert_eq!(DepthExpr::Nat(9).par(DepthExpr::Nat(9)).as_const(), Some(9));
});
audit_case!(const_max_09_10, {
    assert_eq!(
        DepthExpr::Nat(9).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_09_11, {
    assert_eq!(
        DepthExpr::Nat(9).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_10_00, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(0)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_01, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(1)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_02, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(2)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_03, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(3)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_04, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(4)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_05, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(5)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_06, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(6)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_07, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(7)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_08, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(8)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_09, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(9)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_10, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(10)).as_const(),
        Some(10)
    );
});
audit_case!(const_max_10_11, {
    assert_eq!(
        DepthExpr::Nat(10).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_00, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(0)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_01, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(1)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_02, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(2)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_03, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(3)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_04, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(4)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_05, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(5)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_06, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(6)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_07, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(7)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_08, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(8)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_09, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(9)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_10, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(10)).as_const(),
        Some(11)
    );
});
audit_case!(const_max_11_11, {
    assert_eq!(
        DepthExpr::Nat(11).par(DepthExpr::Nat(11)).as_const(),
        Some(11)
    );
});
audit_case!(const_div_00_01, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(1)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_02, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(2)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_03, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(3)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_04, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(4)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_05, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_06, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_07, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_08, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_09, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_10, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_00_11, {
    assert_eq!(
        DepthExpr::Nat(0).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_01, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(1)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_01_02, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(2)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_03, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(3)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_04, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(4)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_05, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_06, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_07, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_08, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_09, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_10, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_01_11, {
    assert_eq!(
        DepthExpr::Nat(1).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_01, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(1)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_02_02, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(2)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_02_03, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(3)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_04, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(4)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_05, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_06, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_07, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_08, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_09, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_10, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_02_11, {
    assert_eq!(
        DepthExpr::Nat(2).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_01, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(1)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_03_02, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(2)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_03_03, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(3)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_03_04, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(4)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_05, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_06, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_07, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_08, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_09, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_10, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_03_11, {
    assert_eq!(
        DepthExpr::Nat(3).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_01, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(1)).as_const(),
        Some(4)
    );
});
audit_case!(const_div_04_02, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(2)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_04_03, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(3)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_04_04, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(4)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_04_05, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(5)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_06, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_07, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_08, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_09, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_10, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_04_11, {
    assert_eq!(
        DepthExpr::Nat(4).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_01, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(1)).as_const(),
        Some(5)
    );
});
audit_case!(const_div_05_02, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(2)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_05_03, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(3)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_05_04, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(4)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_05_05, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(5)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_05_06, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(6)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_07, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_08, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_09, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_10, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_05_11, {
    assert_eq!(
        DepthExpr::Nat(5).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_06_01, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(1)).as_const(),
        Some(6)
    );
});
audit_case!(const_div_06_02, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(2)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_06_03, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(3)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_06_04, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(4)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_06_05, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(5)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_06_06, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_06_07, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(7)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_06_08, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_06_09, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_06_10, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_06_11, {
    assert_eq!(
        DepthExpr::Nat(6).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_07_01, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(1)).as_const(),
        Some(7)
    );
});
audit_case!(const_div_07_02, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(2)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_07_03, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(3)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_07_04, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(4)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_07_05, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(5)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_07_06, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_07_07, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(7)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_07_08, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(8)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_07_09, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_07_10, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_07_11, {
    assert_eq!(
        DepthExpr::Nat(7).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_08_01, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(1)).as_const(),
        Some(8)
    );
});
audit_case!(const_div_08_02, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(2)).as_const(),
        Some(4)
    );
});
audit_case!(const_div_08_03, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(3)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_08_04, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(4)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_08_05, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(5)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_08_06, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_08_07, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(7)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_08_08, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(8)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_08_09, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(9)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_08_10, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_08_11, {
    assert_eq!(
        DepthExpr::Nat(8).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_09_01, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(1)).as_const(),
        Some(9)
    );
});
audit_case!(const_div_09_02, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(2)).as_const(),
        Some(4)
    );
});
audit_case!(const_div_09_03, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(3)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_09_04, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(4)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_09_05, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(5)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_09_06, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_09_07, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(7)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_09_08, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(8)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_09_09, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(9)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_09_10, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(10)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_09_11, {
    assert_eq!(
        DepthExpr::Nat(9).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_10_01, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(1)).as_const(),
        Some(10)
    );
});
audit_case!(const_div_10_02, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(2)).as_const(),
        Some(5)
    );
});
audit_case!(const_div_10_03, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(3)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_10_04, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(4)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_10_05, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(5)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_10_06, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_10_07, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(7)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_10_08, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(8)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_10_09, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(9)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_10_10, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(10)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_10_11, {
    assert_eq!(
        DepthExpr::Nat(10).quot(DepthExpr::Nat(11)).as_const(),
        Some(0)
    );
});
audit_case!(const_div_11_01, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(1)).as_const(),
        Some(11)
    );
});
audit_case!(const_div_11_02, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(2)).as_const(),
        Some(5)
    );
});
audit_case!(const_div_11_03, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(3)).as_const(),
        Some(3)
    );
});
audit_case!(const_div_11_04, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(4)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_11_05, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(5)).as_const(),
        Some(2)
    );
});
audit_case!(const_div_11_06, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(6)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_11_07, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(7)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_11_08, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(8)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_11_09, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(9)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_11_10, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(10)).as_const(),
        Some(1)
    );
});
audit_case!(const_div_11_11, {
    assert_eq!(
        DepthExpr::Nat(11).quot(DepthExpr::Nat(11)).as_const(),
        Some(1)
    );
});
audit_case!(var_no_const_n, {
    assert_eq!(DepthExpr::Var("n".into()).as_const(), None);
});
audit_case!(var_no_const_x, {
    assert_eq!(DepthExpr::Var("x".into()).as_const(), None);
});
audit_case!(var_no_const_depth, {
    assert_eq!(DepthExpr::Var("depth".into()).as_const(), None);
});
audit_case!(hole_no_const, {
    assert_eq!(DepthExpr::Hole.as_const(), None);
});
