// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `quon_core` — `linearity`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use quon_core::{
    UseCountViolation, barrier_identity_ok, classify_use_count, if_qubit_threading_ok,
};

audit_case!(cls_0_0_0, {
    assert_eq!(
        classify_use_count(0, false, false),
        Some(UseCountViolation::Unused)
    );
});
audit_case!(cls_0_0_1, {
    assert_eq!(
        classify_use_count(0, false, true),
        Some(UseCountViolation::Unused)
    );
});
audit_case!(cls_0_1_0, {
    assert_eq!(
        classify_use_count(0, true, false),
        Some(UseCountViolation::Unused)
    );
});
audit_case!(cls_0_1_1, {
    assert_eq!(
        classify_use_count(0, true, true),
        Some(UseCountViolation::Unused)
    );
});
audit_case!(cls_1_0_0, {
    assert!(classify_use_count(1, false, false).is_none());
});
audit_case!(cls_1_0_1, {
    assert!(classify_use_count(1, false, true).is_none());
});
audit_case!(cls_1_1_0, {
    assert!(classify_use_count(1, true, false).is_none());
});
audit_case!(cls_1_1_1, {
    assert!(classify_use_count(1, true, true).is_none());
});
audit_case!(cls_2_0_0, {
    assert!(matches!(
        classify_use_count(2, false, false),
        Some(UseCountViolation::MultiUse { count: 2 })
    ));
});
audit_case!(cls_2_0_1, {
    assert!(matches!(
        classify_use_count(2, false, true),
        Some(UseCountViolation::MultiUse { count: 2 })
    ));
});
audit_case!(cls_2_1_0, {
    assert!(matches!(
        classify_use_count(2, true, false),
        Some(UseCountViolation::MultiUse { count: 2 })
    ));
});
audit_case!(cls_2_1_1, {
    assert_eq!(
        classify_use_count(2, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(cls_3_0_0, {
    assert!(matches!(
        classify_use_count(3, false, false),
        Some(UseCountViolation::MultiUse { count: 3 })
    ));
});
audit_case!(cls_3_0_1, {
    assert!(matches!(
        classify_use_count(3, false, true),
        Some(UseCountViolation::MultiUse { count: 3 })
    ));
});
audit_case!(cls_3_1_0, {
    assert!(matches!(
        classify_use_count(3, true, false),
        Some(UseCountViolation::MultiUse { count: 3 })
    ));
});
audit_case!(cls_3_1_1, {
    assert_eq!(
        classify_use_count(3, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(cls_4_0_0, {
    assert!(matches!(
        classify_use_count(4, false, false),
        Some(UseCountViolation::MultiUse { count: 4 })
    ));
});
audit_case!(cls_4_0_1, {
    assert!(matches!(
        classify_use_count(4, false, true),
        Some(UseCountViolation::MultiUse { count: 4 })
    ));
});
audit_case!(cls_4_1_0, {
    assert!(matches!(
        classify_use_count(4, true, false),
        Some(UseCountViolation::MultiUse { count: 4 })
    ));
});
audit_case!(cls_4_1_1, {
    assert_eq!(
        classify_use_count(4, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(cls_5_0_0, {
    assert!(matches!(
        classify_use_count(5, false, false),
        Some(UseCountViolation::MultiUse { count: 5 })
    ));
});
audit_case!(cls_5_0_1, {
    assert!(matches!(
        classify_use_count(5, false, true),
        Some(UseCountViolation::MultiUse { count: 5 })
    ));
});
audit_case!(cls_5_1_0, {
    assert!(matches!(
        classify_use_count(5, true, false),
        Some(UseCountViolation::MultiUse { count: 5 })
    ));
});
audit_case!(cls_5_1_1, {
    assert_eq!(
        classify_use_count(5, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(cls_6_0_0, {
    assert!(matches!(
        classify_use_count(6, false, false),
        Some(UseCountViolation::MultiUse { count: 6 })
    ));
});
audit_case!(cls_6_0_1, {
    assert!(matches!(
        classify_use_count(6, false, true),
        Some(UseCountViolation::MultiUse { count: 6 })
    ));
});
audit_case!(cls_6_1_0, {
    assert!(matches!(
        classify_use_count(6, true, false),
        Some(UseCountViolation::MultiUse { count: 6 })
    ));
});
audit_case!(cls_6_1_1, {
    assert_eq!(
        classify_use_count(6, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(cls_7_0_0, {
    assert!(matches!(
        classify_use_count(7, false, false),
        Some(UseCountViolation::MultiUse { count: 7 })
    ));
});
audit_case!(cls_7_0_1, {
    assert!(matches!(
        classify_use_count(7, false, true),
        Some(UseCountViolation::MultiUse { count: 7 })
    ));
});
audit_case!(cls_7_1_0, {
    assert!(matches!(
        classify_use_count(7, true, false),
        Some(UseCountViolation::MultiUse { count: 7 })
    ));
});
audit_case!(cls_7_1_1, {
    assert_eq!(
        classify_use_count(7, true, true),
        Some(UseCountViolation::ReuseAfterMeasure)
    );
});
audit_case!(barrier_1_1, {
    assert!(barrier_identity_ok(1, 1));
});
audit_case!(barrier_1_2, {
    assert!(!barrier_identity_ok(1, 2));
});
audit_case!(barrier_1_3, {
    assert!(!barrier_identity_ok(1, 3));
});
audit_case!(barrier_1_4, {
    assert!(!barrier_identity_ok(1, 4));
});
audit_case!(barrier_1_5, {
    assert!(!barrier_identity_ok(1, 5));
});
audit_case!(barrier_1_6, {
    assert!(!barrier_identity_ok(1, 6));
});
audit_case!(barrier_1_7, {
    assert!(!barrier_identity_ok(1, 7));
});
audit_case!(barrier_2_1, {
    assert!(!barrier_identity_ok(2, 1));
});
audit_case!(barrier_2_2, {
    assert!(barrier_identity_ok(2, 2));
});
audit_case!(barrier_2_3, {
    assert!(!barrier_identity_ok(2, 3));
});
audit_case!(barrier_2_4, {
    assert!(!barrier_identity_ok(2, 4));
});
audit_case!(barrier_2_5, {
    assert!(!barrier_identity_ok(2, 5));
});
audit_case!(barrier_2_6, {
    assert!(!barrier_identity_ok(2, 6));
});
audit_case!(barrier_2_7, {
    assert!(!barrier_identity_ok(2, 7));
});
audit_case!(barrier_3_1, {
    assert!(!barrier_identity_ok(3, 1));
});
audit_case!(barrier_3_2, {
    assert!(!barrier_identity_ok(3, 2));
});
audit_case!(barrier_3_3, {
    assert!(barrier_identity_ok(3, 3));
});
audit_case!(barrier_3_4, {
    assert!(!barrier_identity_ok(3, 4));
});
audit_case!(barrier_3_5, {
    assert!(!barrier_identity_ok(3, 5));
});
audit_case!(barrier_3_6, {
    assert!(!barrier_identity_ok(3, 6));
});
audit_case!(barrier_3_7, {
    assert!(!barrier_identity_ok(3, 7));
});
audit_case!(barrier_4_1, {
    assert!(!barrier_identity_ok(4, 1));
});
audit_case!(barrier_4_2, {
    assert!(!barrier_identity_ok(4, 2));
});
audit_case!(barrier_4_3, {
    assert!(!barrier_identity_ok(4, 3));
});
audit_case!(barrier_4_4, {
    assert!(barrier_identity_ok(4, 4));
});
audit_case!(barrier_4_5, {
    assert!(!barrier_identity_ok(4, 5));
});
audit_case!(barrier_4_6, {
    assert!(!barrier_identity_ok(4, 6));
});
audit_case!(barrier_4_7, {
    assert!(!barrier_identity_ok(4, 7));
});
audit_case!(barrier_5_1, {
    assert!(!barrier_identity_ok(5, 1));
});
audit_case!(barrier_5_2, {
    assert!(!barrier_identity_ok(5, 2));
});
audit_case!(barrier_5_3, {
    assert!(!barrier_identity_ok(5, 3));
});
audit_case!(barrier_5_4, {
    assert!(!barrier_identity_ok(5, 4));
});
audit_case!(barrier_5_5, {
    assert!(barrier_identity_ok(5, 5));
});
audit_case!(barrier_5_6, {
    assert!(!barrier_identity_ok(5, 6));
});
audit_case!(barrier_5_7, {
    assert!(!barrier_identity_ok(5, 7));
});
audit_case!(barrier_6_1, {
    assert!(!barrier_identity_ok(6, 1));
});
audit_case!(barrier_6_2, {
    assert!(!barrier_identity_ok(6, 2));
});
audit_case!(barrier_6_3, {
    assert!(!barrier_identity_ok(6, 3));
});
audit_case!(barrier_6_4, {
    assert!(!barrier_identity_ok(6, 4));
});
audit_case!(barrier_6_5, {
    assert!(!barrier_identity_ok(6, 5));
});
audit_case!(barrier_6_6, {
    assert!(barrier_identity_ok(6, 6));
});
audit_case!(barrier_6_7, {
    assert!(!barrier_identity_ok(6, 7));
});
audit_case!(barrier_7_1, {
    assert!(!barrier_identity_ok(7, 1));
});
audit_case!(barrier_7_2, {
    assert!(!barrier_identity_ok(7, 2));
});
audit_case!(barrier_7_3, {
    assert!(!barrier_identity_ok(7, 3));
});
audit_case!(barrier_7_4, {
    assert!(!barrier_identity_ok(7, 4));
});
audit_case!(barrier_7_5, {
    assert!(!barrier_identity_ok(7, 5));
});
audit_case!(barrier_7_6, {
    assert!(!barrier_identity_ok(7, 6));
});
audit_case!(barrier_7_7, {
    assert!(barrier_identity_ok(7, 7));
});
audit_case!(if_thread_0_0, {
    assert!(if_qubit_threading_ok(0, 0));
});
audit_case!(if_thread_0_1, {
    assert!(!if_qubit_threading_ok(0, 1));
});
audit_case!(if_thread_0_2, {
    assert!(!if_qubit_threading_ok(0, 2));
});
audit_case!(if_thread_0_3, {
    assert!(!if_qubit_threading_ok(0, 3));
});
audit_case!(if_thread_0_4, {
    assert!(!if_qubit_threading_ok(0, 4));
});
audit_case!(if_thread_0_5, {
    assert!(!if_qubit_threading_ok(0, 5));
});
audit_case!(if_thread_0_6, {
    assert!(!if_qubit_threading_ok(0, 6));
});
audit_case!(if_thread_0_7, {
    assert!(!if_qubit_threading_ok(0, 7));
});
audit_case!(if_thread_1_0, {
    assert!(!if_qubit_threading_ok(1, 0));
});
audit_case!(if_thread_1_1, {
    assert!(if_qubit_threading_ok(1, 1));
});
audit_case!(if_thread_1_2, {
    assert!(!if_qubit_threading_ok(1, 2));
});
audit_case!(if_thread_1_3, {
    assert!(!if_qubit_threading_ok(1, 3));
});
audit_case!(if_thread_1_4, {
    assert!(!if_qubit_threading_ok(1, 4));
});
audit_case!(if_thread_1_5, {
    assert!(!if_qubit_threading_ok(1, 5));
});
audit_case!(if_thread_1_6, {
    assert!(!if_qubit_threading_ok(1, 6));
});
audit_case!(if_thread_1_7, {
    assert!(!if_qubit_threading_ok(1, 7));
});
audit_case!(if_thread_2_0, {
    assert!(!if_qubit_threading_ok(2, 0));
});
audit_case!(if_thread_2_1, {
    assert!(!if_qubit_threading_ok(2, 1));
});
audit_case!(if_thread_2_2, {
    assert!(if_qubit_threading_ok(2, 2));
});
audit_case!(if_thread_2_3, {
    assert!(!if_qubit_threading_ok(2, 3));
});
audit_case!(if_thread_2_4, {
    assert!(!if_qubit_threading_ok(2, 4));
});
audit_case!(if_thread_2_5, {
    assert!(!if_qubit_threading_ok(2, 5));
});
audit_case!(if_thread_2_6, {
    assert!(!if_qubit_threading_ok(2, 6));
});
audit_case!(if_thread_2_7, {
    assert!(!if_qubit_threading_ok(2, 7));
});
audit_case!(if_thread_3_0, {
    assert!(!if_qubit_threading_ok(3, 0));
});
audit_case!(if_thread_3_1, {
    assert!(!if_qubit_threading_ok(3, 1));
});
audit_case!(if_thread_3_2, {
    assert!(!if_qubit_threading_ok(3, 2));
});
audit_case!(if_thread_3_3, {
    assert!(if_qubit_threading_ok(3, 3));
});
audit_case!(if_thread_3_4, {
    assert!(!if_qubit_threading_ok(3, 4));
});
audit_case!(if_thread_3_5, {
    assert!(!if_qubit_threading_ok(3, 5));
});
audit_case!(if_thread_3_6, {
    assert!(!if_qubit_threading_ok(3, 6));
});
audit_case!(if_thread_3_7, {
    assert!(!if_qubit_threading_ok(3, 7));
});
audit_case!(if_thread_4_0, {
    assert!(!if_qubit_threading_ok(4, 0));
});
audit_case!(if_thread_4_1, {
    assert!(!if_qubit_threading_ok(4, 1));
});
audit_case!(if_thread_4_2, {
    assert!(!if_qubit_threading_ok(4, 2));
});
audit_case!(if_thread_4_3, {
    assert!(!if_qubit_threading_ok(4, 3));
});
audit_case!(if_thread_4_4, {
    assert!(if_qubit_threading_ok(4, 4));
});
audit_case!(if_thread_4_5, {
    assert!(!if_qubit_threading_ok(4, 5));
});
audit_case!(if_thread_4_6, {
    assert!(!if_qubit_threading_ok(4, 6));
});
audit_case!(if_thread_4_7, {
    assert!(!if_qubit_threading_ok(4, 7));
});
audit_case!(if_thread_5_0, {
    assert!(!if_qubit_threading_ok(5, 0));
});
audit_case!(if_thread_5_1, {
    assert!(!if_qubit_threading_ok(5, 1));
});
audit_case!(if_thread_5_2, {
    assert!(!if_qubit_threading_ok(5, 2));
});
audit_case!(if_thread_5_3, {
    assert!(!if_qubit_threading_ok(5, 3));
});
audit_case!(if_thread_5_4, {
    assert!(!if_qubit_threading_ok(5, 4));
});
audit_case!(if_thread_5_5, {
    assert!(if_qubit_threading_ok(5, 5));
});
audit_case!(if_thread_5_6, {
    assert!(!if_qubit_threading_ok(5, 6));
});
audit_case!(if_thread_5_7, {
    assert!(!if_qubit_threading_ok(5, 7));
});
audit_case!(if_thread_6_0, {
    assert!(!if_qubit_threading_ok(6, 0));
});
audit_case!(if_thread_6_1, {
    assert!(!if_qubit_threading_ok(6, 1));
});
audit_case!(if_thread_6_2, {
    assert!(!if_qubit_threading_ok(6, 2));
});
audit_case!(if_thread_6_3, {
    assert!(!if_qubit_threading_ok(6, 3));
});
audit_case!(if_thread_6_4, {
    assert!(!if_qubit_threading_ok(6, 4));
});
audit_case!(if_thread_6_5, {
    assert!(!if_qubit_threading_ok(6, 5));
});
audit_case!(if_thread_6_6, {
    assert!(if_qubit_threading_ok(6, 6));
});
audit_case!(if_thread_6_7, {
    assert!(!if_qubit_threading_ok(6, 7));
});
audit_case!(if_thread_7_0, {
    assert!(!if_qubit_threading_ok(7, 0));
});
audit_case!(if_thread_7_1, {
    assert!(!if_qubit_threading_ok(7, 1));
});
audit_case!(if_thread_7_2, {
    assert!(!if_qubit_threading_ok(7, 2));
});
audit_case!(if_thread_7_3, {
    assert!(!if_qubit_threading_ok(7, 3));
});
audit_case!(if_thread_7_4, {
    assert!(!if_qubit_threading_ok(7, 4));
});
audit_case!(if_thread_7_5, {
    assert!(!if_qubit_threading_ok(7, 5));
});
audit_case!(if_thread_7_6, {
    assert!(!if_qubit_threading_ok(7, 6));
});
audit_case!(if_thread_7_7, {
    assert!(if_qubit_threading_ok(7, 7));
});
