// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `quon_core` — `depth subst`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use quon_core::DepthExpr;

audit_case!(subst_nat_0, {
    let env = [("n".into(), DepthExpr::Nat(0))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(0));
});
audit_case!(subst_nat_1, {
    let env = [("n".into(), DepthExpr::Nat(1))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(1));
});
audit_case!(subst_nat_2, {
    let env = [("n".into(), DepthExpr::Nat(2))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(2));
});
audit_case!(subst_nat_3, {
    let env = [("n".into(), DepthExpr::Nat(3))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(3));
});
audit_case!(subst_nat_4, {
    let env = [("n".into(), DepthExpr::Nat(4))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(4));
});
audit_case!(subst_nat_5, {
    let env = [("n".into(), DepthExpr::Nat(5))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(5));
});
audit_case!(subst_nat_6, {
    let env = [("n".into(), DepthExpr::Nat(6))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(6));
});
audit_case!(subst_nat_7, {
    let env = [("n".into(), DepthExpr::Nat(7))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(7));
});
audit_case!(subst_nat_8, {
    let env = [("n".into(), DepthExpr::Nat(8))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(8));
});
audit_case!(subst_nat_9, {
    let env = [("n".into(), DepthExpr::Nat(9))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(9));
});
audit_case!(subst_nat_10, {
    let env = [("n".into(), DepthExpr::Nat(10))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(10));
});
audit_case!(subst_nat_11, {
    let env = [("n".into(), DepthExpr::Nat(11))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(11));
});
audit_case!(subst_nat_12, {
    let env = [("n".into(), DepthExpr::Nat(12))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(12));
});
audit_case!(subst_nat_13, {
    let env = [("n".into(), DepthExpr::Nat(13))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(13));
});
audit_case!(subst_nat_14, {
    let env = [("n".into(), DepthExpr::Nat(14))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(14));
});
audit_case!(subst_nat_15, {
    let env = [("n".into(), DepthExpr::Nat(15))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(15));
});
audit_case!(subst_nat_16, {
    let env = [("n".into(), DepthExpr::Nat(16))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(16));
});
audit_case!(subst_nat_17, {
    let env = [("n".into(), DepthExpr::Nat(17))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(17));
});
audit_case!(subst_nat_18, {
    let env = [("n".into(), DepthExpr::Nat(18))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(18));
});
audit_case!(subst_nat_19, {
    let env = [("n".into(), DepthExpr::Nat(19))].into_iter().collect();
    assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat(19));
});
audit_case!(subst_add_0_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(0));
});
audit_case!(subst_add_0_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(1));
});
audit_case!(subst_add_0_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(2));
});
audit_case!(subst_add_0_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(3));
});
audit_case!(subst_add_0_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(4));
});
audit_case!(subst_add_0_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_0_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_0_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(0)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_1_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(1));
});
audit_case!(subst_add_1_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(2));
});
audit_case!(subst_add_1_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(3));
});
audit_case!(subst_add_1_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(4));
});
audit_case!(subst_add_1_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_1_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_1_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_1_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(1)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_2_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(2));
});
audit_case!(subst_add_2_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(3));
});
audit_case!(subst_add_2_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(4));
});
audit_case!(subst_add_2_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_2_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_2_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_2_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_2_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(2)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_3_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(3));
});
audit_case!(subst_add_3_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(4));
});
audit_case!(subst_add_3_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_3_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_3_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_3_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_3_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_3_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(3)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(10));
});
audit_case!(subst_add_4_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(4));
});
audit_case!(subst_add_4_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_4_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_4_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_4_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_4_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_4_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(10));
});
audit_case!(subst_add_4_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(4)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(11));
});
audit_case!(subst_add_5_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(5));
});
audit_case!(subst_add_5_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_5_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_5_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_5_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_5_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(10));
});
audit_case!(subst_add_5_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(11));
});
audit_case!(subst_add_5_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(5)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(12));
});
audit_case!(subst_add_6_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(6));
});
audit_case!(subst_add_6_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_6_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_6_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_6_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(10));
});
audit_case!(subst_add_6_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(11));
});
audit_case!(subst_add_6_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(12));
});
audit_case!(subst_add_6_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(6)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(13));
});
audit_case!(subst_add_7_0, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(0)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(7));
});
audit_case!(subst_add_7_1, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(1)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(8));
});
audit_case!(subst_add_7_2, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(2)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(9));
});
audit_case!(subst_add_7_3, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(3)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(10));
});
audit_case!(subst_add_7_4, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(4)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(11));
});
audit_case!(subst_add_7_5, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(5)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(12));
});
audit_case!(subst_add_7_6, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(6)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(13));
});
audit_case!(subst_add_7_7, {
    let env = [
        ("x".into(), DepthExpr::Nat(7)),
        ("y".into(), DepthExpr::Nat(7)),
    ]
    .into_iter()
    .collect();
    let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into()));
    assert_eq!(e.subst(&env).as_const(), Some(14));
});
audit_case!(subst_missing_missing, {
    let env = std::collections::HashMap::new();
    assert_eq!(
        DepthExpr::Var("missing".into()).subst(&env),
        DepthExpr::Var("missing".into())
    );
});
audit_case!(subst_missing_unbound, {
    let env = std::collections::HashMap::new();
    assert_eq!(
        DepthExpr::Var("unbound".into()).subst(&env),
        DepthExpr::Var("unbound".into())
    );
});
audit_case!(subst_missing_z, {
    let env = std::collections::HashMap::new();
    assert_eq!(
        DepthExpr::Var("z".into()).subst(&env),
        DepthExpr::Var("z".into())
    );
});
