/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_fn = 2,
  anon_sym_type = 3,
  sym_keyword = 4,
  sym_boolean = 5,
  sym_number = 6,
  sym_operator = 7,
  sym_delimiter = 8,
  sym_punctuation = 9,
  sym_line_comment = 10,
  sym_block_comment = 11,
  sym_source_file = 12,
  sym__node = 13,
  sym_fn_declaration = 14,
  sym_type_declaration = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_fn] = "fn",
  [anon_sym_type] = "type",
  [sym_keyword] = "keyword",
  [sym_boolean] = "boolean",
  [sym_number] = "number",
  [sym_operator] = "operator",
  [sym_delimiter] = "delimiter",
  [sym_punctuation] = "punctuation",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_fn_declaration] = "fn_declaration",
  [sym_type_declaration] = "type_declaration",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_type] = anon_sym_type,
  [sym_keyword] = sym_keyword,
  [sym_boolean] = sym_boolean,
  [sym_number] = sym_number,
  [sym_operator] = sym_operator,
  [sym_delimiter] = sym_delimiter,
  [sym_punctuation] = sym_punctuation,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_fn_declaration] = sym_fn_declaration,
  [sym_type_declaration] = sym_type_declaration,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_fn_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '-', 16,
        '<', 19,
        '=', 17,
        '_', 14,
        '{', 20,
        '|', 17,
        ',', 21,
        '.', 21,
        ':', 21,
        '`', 21,
        '*', 15,
        '+', 15,
        '/', 15,
        '@', 15,
        '^', 15,
        '(', 18,
        ')', 18,
        '>', 18,
        '[', 18,
        ']', 18,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(1);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(3);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '>' ||
          lookahead == 'o') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_delimiter);
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_delimiter);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'e', 4,
        'f', 5,
        'i', 6,
        'l', 7,
        'm', 8,
        'p', 9,
        'r', 10,
        't', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'f' ||
          lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(26);
      if (lookahead == 'r') ADVANCE(27);
      if (lookahead == 'y') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'j') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 45:
      if (lookahead == 'h') ADVANCE(20);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 'w') ADVANCE(20);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym__node] = STATE(2),
    [sym_fn_declaration] = STATE(2),
    [sym_type_declaration] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [sym_keyword] = ACTIONS(5),
    [sym_boolean] = ACTIONS(5),
    [sym_number] = ACTIONS(11),
    [sym_operator] = ACTIONS(5),
    [sym_delimiter] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__node] = STATE(3),
    [sym_fn_declaration] = STATE(3),
    [sym_type_declaration] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [sym_keyword] = ACTIONS(15),
    [sym_boolean] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_operator] = ACTIONS(15),
    [sym_delimiter] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(17),
    [sym_block_comment] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__node] = STATE(3),
    [sym_fn_declaration] = STATE(3),
    [sym_type_declaration] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(24),
    [anon_sym_type] = ACTIONS(27),
    [sym_keyword] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_number] = ACTIONS(30),
    [sym_operator] = ACTIONS(21),
    [sym_delimiter] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(30),
    [sym_block_comment] = ACTIONS(30),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_fn] = ACTIONS(35),
    [anon_sym_type] = ACTIONS(35),
    [sym_keyword] = ACTIONS(35),
    [sym_boolean] = ACTIONS(35),
    [sym_number] = ACTIONS(33),
    [sym_operator] = ACTIONS(35),
    [sym_delimiter] = ACTIONS(35),
    [sym_punctuation] = ACTIONS(35),
    [sym_line_comment] = ACTIONS(33),
    [sym_block_comment] = ACTIONS(33),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_fn] = ACTIONS(39),
    [anon_sym_type] = ACTIONS(39),
    [sym_keyword] = ACTIONS(39),
    [sym_boolean] = ACTIONS(39),
    [sym_number] = ACTIONS(37),
    [sym_operator] = ACTIONS(39),
    [sym_delimiter] = ACTIONS(39),
    [sym_punctuation] = ACTIONS(39),
    [sym_line_comment] = ACTIONS(37),
    [sym_block_comment] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(41), 1,
      sym_identifier,
  [4] = 1,
    ACTIONS(43), 1,
      sym_identifier,
  [8] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 4,
  [SMALL_STATE(8)] = 8,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_declaration, 2, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_declaration, 2, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 2, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 2, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quon",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
