id = "quon"
name = "Quon"
description = "Quon language support — Tree-sitter, quon_lsp, and quonfmt."
version = "0.0.1"
schema_version = 1
authors = ["Arnab Ghosh <arnabcare21@gmail.com>"]
repository = "https://github.com/arniber21/quon"

[language_servers.quon-lsp]
name = "Quon LSP"
languages = ["Quon"]

[language_servers.quon-lsp.language_ids]
"Quon" = "quon"

[grammars.quon]
repository = "https://github.com/arniber21/quon"
rev = "2adf184576c2ccc27443d666e2508f660ac0e32d"
path = "tree-sitter-quon"
