// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `backend` — `keys`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use backend::BackendError;
use backend::keys::{decode_pair, decode_qubit, encode_pair, encode_qubit};

audit_case!(q_round_0_1, {
    assert_eq!(decode_qubit(&encode_qubit(0), 1).unwrap(), 0);
});
audit_case!(q_round_0_2, {
    assert_eq!(decode_qubit(&encode_qubit(0), 2).unwrap(), 0);
});
audit_case!(q_round_0_3, {
    assert_eq!(decode_qubit(&encode_qubit(0), 3).unwrap(), 0);
});
audit_case!(q_round_1_2, {
    assert_eq!(decode_qubit(&encode_qubit(1), 2).unwrap(), 1);
});
audit_case!(q_round_1_3, {
    assert_eq!(decode_qubit(&encode_qubit(1), 3).unwrap(), 1);
});
audit_case!(q_round_1_4, {
    assert_eq!(decode_qubit(&encode_qubit(1), 4).unwrap(), 1);
});
audit_case!(q_round_2_3, {
    assert_eq!(decode_qubit(&encode_qubit(2), 3).unwrap(), 2);
});
audit_case!(q_round_2_4, {
    assert_eq!(decode_qubit(&encode_qubit(2), 4).unwrap(), 2);
});
audit_case!(q_round_2_5, {
    assert_eq!(decode_qubit(&encode_qubit(2), 5).unwrap(), 2);
});
audit_case!(q_round_3_4, {
    assert_eq!(decode_qubit(&encode_qubit(3), 4).unwrap(), 3);
});
audit_case!(q_round_3_5, {
    assert_eq!(decode_qubit(&encode_qubit(3), 5).unwrap(), 3);
});
audit_case!(q_round_3_6, {
    assert_eq!(decode_qubit(&encode_qubit(3), 6).unwrap(), 3);
});
audit_case!(q_round_4_5, {
    assert_eq!(decode_qubit(&encode_qubit(4), 5).unwrap(), 4);
});
audit_case!(q_round_4_6, {
    assert_eq!(decode_qubit(&encode_qubit(4), 6).unwrap(), 4);
});
audit_case!(q_round_4_7, {
    assert_eq!(decode_qubit(&encode_qubit(4), 7).unwrap(), 4);
});
audit_case!(q_round_5_6, {
    assert_eq!(decode_qubit(&encode_qubit(5), 6).unwrap(), 5);
});
audit_case!(q_round_5_7, {
    assert_eq!(decode_qubit(&encode_qubit(5), 7).unwrap(), 5);
});
audit_case!(q_round_5_8, {
    assert_eq!(decode_qubit(&encode_qubit(5), 8).unwrap(), 5);
});
audit_case!(q_round_6_7, {
    assert_eq!(decode_qubit(&encode_qubit(6), 7).unwrap(), 6);
});
audit_case!(q_round_6_8, {
    assert_eq!(decode_qubit(&encode_qubit(6), 8).unwrap(), 6);
});
audit_case!(q_round_6_9, {
    assert_eq!(decode_qubit(&encode_qubit(6), 9).unwrap(), 6);
});
audit_case!(q_round_7_8, {
    assert_eq!(decode_qubit(&encode_qubit(7), 8).unwrap(), 7);
});
audit_case!(q_round_7_9, {
    assert_eq!(decode_qubit(&encode_qubit(7), 9).unwrap(), 7);
});
audit_case!(q_round_7_10, {
    assert_eq!(decode_qubit(&encode_qubit(7), 10).unwrap(), 7);
});
audit_case!(q_round_8_9, {
    assert_eq!(decode_qubit(&encode_qubit(8), 9).unwrap(), 8);
});
audit_case!(q_round_8_10, {
    assert_eq!(decode_qubit(&encode_qubit(8), 10).unwrap(), 8);
});
audit_case!(q_round_8_11, {
    assert_eq!(decode_qubit(&encode_qubit(8), 11).unwrap(), 8);
});
audit_case!(q_round_9_10, {
    assert_eq!(decode_qubit(&encode_qubit(9), 10).unwrap(), 9);
});
audit_case!(q_round_9_11, {
    assert_eq!(decode_qubit(&encode_qubit(9), 11).unwrap(), 9);
});
audit_case!(q_round_9_12, {
    assert_eq!(decode_qubit(&encode_qubit(9), 12).unwrap(), 9);
});
audit_case!(q_round_10_11, {
    assert_eq!(decode_qubit(&encode_qubit(10), 11).unwrap(), 10);
});
audit_case!(q_round_10_12, {
    assert_eq!(decode_qubit(&encode_qubit(10), 12).unwrap(), 10);
});
audit_case!(q_round_10_13, {
    assert_eq!(decode_qubit(&encode_qubit(10), 13).unwrap(), 10);
});
audit_case!(q_round_11_12, {
    assert_eq!(decode_qubit(&encode_qubit(11), 12).unwrap(), 11);
});
audit_case!(q_round_11_13, {
    assert_eq!(decode_qubit(&encode_qubit(11), 13).unwrap(), 11);
});
audit_case!(q_round_11_14, {
    assert_eq!(decode_qubit(&encode_qubit(11), 14).unwrap(), 11);
});
audit_case!(q_round_12_13, {
    assert_eq!(decode_qubit(&encode_qubit(12), 13).unwrap(), 12);
});
audit_case!(q_round_12_14, {
    assert_eq!(decode_qubit(&encode_qubit(12), 14).unwrap(), 12);
});
audit_case!(q_round_12_15, {
    assert_eq!(decode_qubit(&encode_qubit(12), 15).unwrap(), 12);
});
audit_case!(q_round_13_14, {
    assert_eq!(decode_qubit(&encode_qubit(13), 14).unwrap(), 13);
});
audit_case!(q_round_13_15, {
    assert_eq!(decode_qubit(&encode_qubit(13), 15).unwrap(), 13);
});
audit_case!(q_round_13_16, {
    assert_eq!(decode_qubit(&encode_qubit(13), 16).unwrap(), 13);
});
audit_case!(q_round_14_15, {
    assert_eq!(decode_qubit(&encode_qubit(14), 15).unwrap(), 14);
});
audit_case!(q_round_14_16, {
    assert_eq!(decode_qubit(&encode_qubit(14), 16).unwrap(), 14);
});
audit_case!(q_round_14_17, {
    assert_eq!(decode_qubit(&encode_qubit(14), 17).unwrap(), 14);
});
audit_case!(q_round_15_16, {
    assert_eq!(decode_qubit(&encode_qubit(15), 16).unwrap(), 15);
});
audit_case!(q_round_15_17, {
    assert_eq!(decode_qubit(&encode_qubit(15), 17).unwrap(), 15);
});
audit_case!(q_round_15_18, {
    assert_eq!(decode_qubit(&encode_qubit(15), 18).unwrap(), 15);
});
audit_case!(q_round_16_17, {
    assert_eq!(decode_qubit(&encode_qubit(16), 17).unwrap(), 16);
});
audit_case!(q_round_16_18, {
    assert_eq!(decode_qubit(&encode_qubit(16), 18).unwrap(), 16);
});
audit_case!(q_round_16_19, {
    assert_eq!(decode_qubit(&encode_qubit(16), 19).unwrap(), 16);
});
audit_case!(q_round_17_18, {
    assert_eq!(decode_qubit(&encode_qubit(17), 18).unwrap(), 17);
});
audit_case!(q_round_17_19, {
    assert_eq!(decode_qubit(&encode_qubit(17), 19).unwrap(), 17);
});
audit_case!(q_round_17_20, {
    assert_eq!(decode_qubit(&encode_qubit(17), 20).unwrap(), 17);
});
audit_case!(q_round_18_19, {
    assert_eq!(decode_qubit(&encode_qubit(18), 19).unwrap(), 18);
});
audit_case!(q_round_18_20, {
    assert_eq!(decode_qubit(&encode_qubit(18), 20).unwrap(), 18);
});
audit_case!(q_round_18_21, {
    assert_eq!(decode_qubit(&encode_qubit(18), 21).unwrap(), 18);
});
audit_case!(q_round_19_20, {
    assert_eq!(decode_qubit(&encode_qubit(19), 20).unwrap(), 19);
});
audit_case!(q_round_19_21, {
    assert_eq!(decode_qubit(&encode_qubit(19), 21).unwrap(), 19);
});
audit_case!(q_round_19_22, {
    assert_eq!(decode_qubit(&encode_qubit(19), 22).unwrap(), 19);
});
audit_case!(q_round_20_21, {
    assert_eq!(decode_qubit(&encode_qubit(20), 21).unwrap(), 20);
});
audit_case!(q_round_20_22, {
    assert_eq!(decode_qubit(&encode_qubit(20), 22).unwrap(), 20);
});
audit_case!(q_round_20_23, {
    assert_eq!(decode_qubit(&encode_qubit(20), 23).unwrap(), 20);
});
audit_case!(q_round_21_22, {
    assert_eq!(decode_qubit(&encode_qubit(21), 22).unwrap(), 21);
});
audit_case!(q_round_21_23, {
    assert_eq!(decode_qubit(&encode_qubit(21), 23).unwrap(), 21);
});
audit_case!(q_round_21_24, {
    assert_eq!(decode_qubit(&encode_qubit(21), 24).unwrap(), 21);
});
audit_case!(q_round_22_23, {
    assert_eq!(decode_qubit(&encode_qubit(22), 23).unwrap(), 22);
});
audit_case!(q_round_22_24, {
    assert_eq!(decode_qubit(&encode_qubit(22), 24).unwrap(), 22);
});
audit_case!(q_round_22_25, {
    assert_eq!(decode_qubit(&encode_qubit(22), 25).unwrap(), 22);
});
audit_case!(q_round_23_24, {
    assert_eq!(decode_qubit(&encode_qubit(23), 24).unwrap(), 23);
});
audit_case!(q_round_23_25, {
    assert_eq!(decode_qubit(&encode_qubit(23), 25).unwrap(), 23);
});
audit_case!(q_round_23_26, {
    assert_eq!(decode_qubit(&encode_qubit(23), 26).unwrap(), 23);
});
audit_case!(q_round_24_25, {
    assert_eq!(decode_qubit(&encode_qubit(24), 25).unwrap(), 24);
});
audit_case!(q_round_24_26, {
    assert_eq!(decode_qubit(&encode_qubit(24), 26).unwrap(), 24);
});
audit_case!(q_round_24_27, {
    assert_eq!(decode_qubit(&encode_qubit(24), 27).unwrap(), 24);
});
audit_case!(q_round_25_26, {
    assert_eq!(decode_qubit(&encode_qubit(25), 26).unwrap(), 25);
});
audit_case!(q_round_25_27, {
    assert_eq!(decode_qubit(&encode_qubit(25), 27).unwrap(), 25);
});
audit_case!(q_round_25_28, {
    assert_eq!(decode_qubit(&encode_qubit(25), 28).unwrap(), 25);
});
audit_case!(q_round_26_27, {
    assert_eq!(decode_qubit(&encode_qubit(26), 27).unwrap(), 26);
});
audit_case!(q_round_26_28, {
    assert_eq!(decode_qubit(&encode_qubit(26), 28).unwrap(), 26);
});
audit_case!(q_round_26_29, {
    assert_eq!(decode_qubit(&encode_qubit(26), 29).unwrap(), 26);
});
audit_case!(q_round_27_28, {
    assert_eq!(decode_qubit(&encode_qubit(27), 28).unwrap(), 27);
});
audit_case!(q_round_27_29, {
    assert_eq!(decode_qubit(&encode_qubit(27), 29).unwrap(), 27);
});
audit_case!(q_round_27_30, {
    assert_eq!(decode_qubit(&encode_qubit(27), 30).unwrap(), 27);
});
audit_case!(q_round_28_29, {
    assert_eq!(decode_qubit(&encode_qubit(28), 29).unwrap(), 28);
});
audit_case!(q_round_28_30, {
    assert_eq!(decode_qubit(&encode_qubit(28), 30).unwrap(), 28);
});
audit_case!(q_round_28_31, {
    assert_eq!(decode_qubit(&encode_qubit(28), 31).unwrap(), 28);
});
audit_case!(q_round_29_30, {
    assert_eq!(decode_qubit(&encode_qubit(29), 30).unwrap(), 29);
});
audit_case!(q_round_29_31, {
    assert_eq!(decode_qubit(&encode_qubit(29), 31).unwrap(), 29);
});
audit_case!(q_round_29_32, {
    assert_eq!(decode_qubit(&encode_qubit(29), 32).unwrap(), 29);
});
audit_case!(q_round_30_31, {
    assert_eq!(decode_qubit(&encode_qubit(30), 31).unwrap(), 30);
});
audit_case!(q_round_30_32, {
    assert_eq!(decode_qubit(&encode_qubit(30), 32).unwrap(), 30);
});
audit_case!(q_round_30_33, {
    assert_eq!(decode_qubit(&encode_qubit(30), 33).unwrap(), 30);
});
audit_case!(q_round_31_32, {
    assert_eq!(decode_qubit(&encode_qubit(31), 32).unwrap(), 31);
});
audit_case!(q_round_31_33, {
    assert_eq!(decode_qubit(&encode_qubit(31), 33).unwrap(), 31);
});
audit_case!(q_round_31_34, {
    assert_eq!(decode_qubit(&encode_qubit(31), 34).unwrap(), 31);
});
audit_case!(q_oob_0, {
    assert!(matches!(
        decode_qubit(&encode_qubit(0), 0),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_1, {
    assert!(matches!(
        decode_qubit(&encode_qubit(1), 1),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_2, {
    assert!(matches!(
        decode_qubit(&encode_qubit(2), 2),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_3, {
    assert!(matches!(
        decode_qubit(&encode_qubit(3), 3),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_4, {
    assert!(matches!(
        decode_qubit(&encode_qubit(4), 4),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_5, {
    assert!(matches!(
        decode_qubit(&encode_qubit(5), 5),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_6, {
    assert!(matches!(
        decode_qubit(&encode_qubit(6), 6),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_7, {
    assert!(matches!(
        decode_qubit(&encode_qubit(7), 7),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_8, {
    assert!(matches!(
        decode_qubit(&encode_qubit(8), 8),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_9, {
    assert!(matches!(
        decode_qubit(&encode_qubit(9), 9),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_10, {
    assert!(matches!(
        decode_qubit(&encode_qubit(10), 10),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_11, {
    assert!(matches!(
        decode_qubit(&encode_qubit(11), 11),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_12, {
    assert!(matches!(
        decode_qubit(&encode_qubit(12), 12),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_13, {
    assert!(matches!(
        decode_qubit(&encode_qubit(13), 13),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_14, {
    assert!(matches!(
        decode_qubit(&encode_qubit(14), 14),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_15, {
    assert!(matches!(
        decode_qubit(&encode_qubit(15), 15),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_16, {
    assert!(matches!(
        decode_qubit(&encode_qubit(16), 16),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_17, {
    assert!(matches!(
        decode_qubit(&encode_qubit(17), 17),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_18, {
    assert!(matches!(
        decode_qubit(&encode_qubit(18), 18),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_19, {
    assert!(matches!(
        decode_qubit(&encode_qubit(19), 19),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_20, {
    assert!(matches!(
        decode_qubit(&encode_qubit(20), 20),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_21, {
    assert!(matches!(
        decode_qubit(&encode_qubit(21), 21),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_22, {
    assert!(matches!(
        decode_qubit(&encode_qubit(22), 22),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_23, {
    assert!(matches!(
        decode_qubit(&encode_qubit(23), 23),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_24, {
    assert!(matches!(
        decode_qubit(&encode_qubit(24), 24),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_25, {
    assert!(matches!(
        decode_qubit(&encode_qubit(25), 25),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_26, {
    assert!(matches!(
        decode_qubit(&encode_qubit(26), 26),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_27, {
    assert!(matches!(
        decode_qubit(&encode_qubit(27), 27),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_28, {
    assert!(matches!(
        decode_qubit(&encode_qubit(28), 28),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_29, {
    assert!(matches!(
        decode_qubit(&encode_qubit(29), 29),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_30, {
    assert!(matches!(
        decode_qubit(&encode_qubit(30), 30),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(q_oob_31, {
    assert!(matches!(
        decode_qubit(&encode_qubit(31), 31),
        Err(BackendError::QubitOutOfRange { .. })
    ));
});
audit_case!(pair_round_0_0_1, {
    assert_eq!(decode_pair(&encode_pair(0, 0), 1).unwrap(), (0, 0));
});
audit_case!(pair_round_0_0_2, {
    assert_eq!(decode_pair(&encode_pair(0, 0), 2).unwrap(), (0, 0));
});
audit_case!(pair_round_0_0_3, {
    assert_eq!(decode_pair(&encode_pair(0, 0), 3).unwrap(), (0, 0));
});
audit_case!(pair_round_0_1_2, {
    assert_eq!(decode_pair(&encode_pair(0, 1), 2).unwrap(), (0, 1));
});
audit_case!(pair_round_0_1_3, {
    assert_eq!(decode_pair(&encode_pair(0, 1), 3).unwrap(), (0, 1));
});
audit_case!(pair_round_0_1_4, {
    assert_eq!(decode_pair(&encode_pair(0, 1), 4).unwrap(), (0, 1));
});
audit_case!(pair_round_0_2_3, {
    assert_eq!(decode_pair(&encode_pair(0, 2), 3).unwrap(), (0, 2));
});
audit_case!(pair_round_0_2_4, {
    assert_eq!(decode_pair(&encode_pair(0, 2), 4).unwrap(), (0, 2));
});
audit_case!(pair_round_0_2_5, {
    assert_eq!(decode_pair(&encode_pair(0, 2), 5).unwrap(), (0, 2));
});
audit_case!(pair_round_0_3_4, {
    assert_eq!(decode_pair(&encode_pair(0, 3), 4).unwrap(), (0, 3));
});
audit_case!(pair_round_0_3_5, {
    assert_eq!(decode_pair(&encode_pair(0, 3), 5).unwrap(), (0, 3));
});
audit_case!(pair_round_0_3_6, {
    assert_eq!(decode_pair(&encode_pair(0, 3), 6).unwrap(), (0, 3));
});
audit_case!(pair_round_0_4_5, {
    assert_eq!(decode_pair(&encode_pair(0, 4), 5).unwrap(), (0, 4));
});
audit_case!(pair_round_0_4_6, {
    assert_eq!(decode_pair(&encode_pair(0, 4), 6).unwrap(), (0, 4));
});
audit_case!(pair_round_0_4_7, {
    assert_eq!(decode_pair(&encode_pair(0, 4), 7).unwrap(), (0, 4));
});
audit_case!(pair_round_0_5_6, {
    assert_eq!(decode_pair(&encode_pair(0, 5), 6).unwrap(), (0, 5));
});
audit_case!(pair_round_0_5_7, {
    assert_eq!(decode_pair(&encode_pair(0, 5), 7).unwrap(), (0, 5));
});
audit_case!(pair_round_0_5_8, {
    assert_eq!(decode_pair(&encode_pair(0, 5), 8).unwrap(), (0, 5));
});
audit_case!(pair_round_0_6_7, {
    assert_eq!(decode_pair(&encode_pair(0, 6), 7).unwrap(), (0, 6));
});
audit_case!(pair_round_0_6_8, {
    assert_eq!(decode_pair(&encode_pair(0, 6), 8).unwrap(), (0, 6));
});
audit_case!(pair_round_0_6_9, {
    assert_eq!(decode_pair(&encode_pair(0, 6), 9).unwrap(), (0, 6));
});
audit_case!(pair_round_0_7_8, {
    assert_eq!(decode_pair(&encode_pair(0, 7), 8).unwrap(), (0, 7));
});
audit_case!(pair_round_0_7_9, {
    assert_eq!(decode_pair(&encode_pair(0, 7), 9).unwrap(), (0, 7));
});
audit_case!(pair_round_0_7_10, {
    assert_eq!(decode_pair(&encode_pair(0, 7), 10).unwrap(), (0, 7));
});
audit_case!(pair_round_1_0_2, {
    assert_eq!(decode_pair(&encode_pair(1, 0), 2).unwrap(), (1, 0));
});
audit_case!(pair_round_1_0_3, {
    assert_eq!(decode_pair(&encode_pair(1, 0), 3).unwrap(), (1, 0));
});
audit_case!(pair_round_1_0_4, {
    assert_eq!(decode_pair(&encode_pair(1, 0), 4).unwrap(), (1, 0));
});
audit_case!(pair_round_1_1_2, {
    assert_eq!(decode_pair(&encode_pair(1, 1), 2).unwrap(), (1, 1));
});
audit_case!(pair_round_1_1_3, {
    assert_eq!(decode_pair(&encode_pair(1, 1), 3).unwrap(), (1, 1));
});
audit_case!(pair_round_1_1_4, {
    assert_eq!(decode_pair(&encode_pair(1, 1), 4).unwrap(), (1, 1));
});
audit_case!(pair_round_1_2_3, {
    assert_eq!(decode_pair(&encode_pair(1, 2), 3).unwrap(), (1, 2));
});
audit_case!(pair_round_1_2_4, {
    assert_eq!(decode_pair(&encode_pair(1, 2), 4).unwrap(), (1, 2));
});
audit_case!(pair_round_1_2_5, {
    assert_eq!(decode_pair(&encode_pair(1, 2), 5).unwrap(), (1, 2));
});
audit_case!(pair_round_1_3_4, {
    assert_eq!(decode_pair(&encode_pair(1, 3), 4).unwrap(), (1, 3));
});
audit_case!(pair_round_1_3_5, {
    assert_eq!(decode_pair(&encode_pair(1, 3), 5).unwrap(), (1, 3));
});
audit_case!(pair_round_1_3_6, {
    assert_eq!(decode_pair(&encode_pair(1, 3), 6).unwrap(), (1, 3));
});
audit_case!(pair_round_1_4_5, {
    assert_eq!(decode_pair(&encode_pair(1, 4), 5).unwrap(), (1, 4));
});
audit_case!(pair_round_1_4_6, {
    assert_eq!(decode_pair(&encode_pair(1, 4), 6).unwrap(), (1, 4));
});
audit_case!(pair_round_1_4_7, {
    assert_eq!(decode_pair(&encode_pair(1, 4), 7).unwrap(), (1, 4));
});
audit_case!(pair_round_1_5_6, {
    assert_eq!(decode_pair(&encode_pair(1, 5), 6).unwrap(), (1, 5));
});
audit_case!(pair_round_1_5_7, {
    assert_eq!(decode_pair(&encode_pair(1, 5), 7).unwrap(), (1, 5));
});
audit_case!(pair_round_1_5_8, {
    assert_eq!(decode_pair(&encode_pair(1, 5), 8).unwrap(), (1, 5));
});
audit_case!(pair_round_1_6_7, {
    assert_eq!(decode_pair(&encode_pair(1, 6), 7).unwrap(), (1, 6));
});
audit_case!(pair_round_1_6_8, {
    assert_eq!(decode_pair(&encode_pair(1, 6), 8).unwrap(), (1, 6));
});
audit_case!(pair_round_1_6_9, {
    assert_eq!(decode_pair(&encode_pair(1, 6), 9).unwrap(), (1, 6));
});
audit_case!(pair_round_1_7_8, {
    assert_eq!(decode_pair(&encode_pair(1, 7), 8).unwrap(), (1, 7));
});
audit_case!(pair_round_1_7_9, {
    assert_eq!(decode_pair(&encode_pair(1, 7), 9).unwrap(), (1, 7));
});
audit_case!(pair_round_1_7_10, {
    assert_eq!(decode_pair(&encode_pair(1, 7), 10).unwrap(), (1, 7));
});
audit_case!(pair_round_2_0_3, {
    assert_eq!(decode_pair(&encode_pair(2, 0), 3).unwrap(), (2, 0));
});
audit_case!(pair_round_2_0_4, {
    assert_eq!(decode_pair(&encode_pair(2, 0), 4).unwrap(), (2, 0));
});
audit_case!(pair_round_2_0_5, {
    assert_eq!(decode_pair(&encode_pair(2, 0), 5).unwrap(), (2, 0));
});
audit_case!(pair_round_2_1_3, {
    assert_eq!(decode_pair(&encode_pair(2, 1), 3).unwrap(), (2, 1));
});
audit_case!(pair_round_2_1_4, {
    assert_eq!(decode_pair(&encode_pair(2, 1), 4).unwrap(), (2, 1));
});
audit_case!(pair_round_2_1_5, {
    assert_eq!(decode_pair(&encode_pair(2, 1), 5).unwrap(), (2, 1));
});
audit_case!(pair_round_2_2_3, {
    assert_eq!(decode_pair(&encode_pair(2, 2), 3).unwrap(), (2, 2));
});
audit_case!(pair_round_2_2_4, {
    assert_eq!(decode_pair(&encode_pair(2, 2), 4).unwrap(), (2, 2));
});
audit_case!(pair_round_2_2_5, {
    assert_eq!(decode_pair(&encode_pair(2, 2), 5).unwrap(), (2, 2));
});
audit_case!(pair_round_2_3_4, {
    assert_eq!(decode_pair(&encode_pair(2, 3), 4).unwrap(), (2, 3));
});
audit_case!(pair_round_2_3_5, {
    assert_eq!(decode_pair(&encode_pair(2, 3), 5).unwrap(), (2, 3));
});
audit_case!(pair_round_2_3_6, {
    assert_eq!(decode_pair(&encode_pair(2, 3), 6).unwrap(), (2, 3));
});
audit_case!(pair_round_2_4_5, {
    assert_eq!(decode_pair(&encode_pair(2, 4), 5).unwrap(), (2, 4));
});
audit_case!(pair_round_2_4_6, {
    assert_eq!(decode_pair(&encode_pair(2, 4), 6).unwrap(), (2, 4));
});
audit_case!(pair_round_2_4_7, {
    assert_eq!(decode_pair(&encode_pair(2, 4), 7).unwrap(), (2, 4));
});
audit_case!(pair_round_2_5_6, {
    assert_eq!(decode_pair(&encode_pair(2, 5), 6).unwrap(), (2, 5));
});
audit_case!(pair_round_2_5_7, {
    assert_eq!(decode_pair(&encode_pair(2, 5), 7).unwrap(), (2, 5));
});
audit_case!(pair_round_2_5_8, {
    assert_eq!(decode_pair(&encode_pair(2, 5), 8).unwrap(), (2, 5));
});
audit_case!(pair_round_2_6_7, {
    assert_eq!(decode_pair(&encode_pair(2, 6), 7).unwrap(), (2, 6));
});
audit_case!(pair_round_2_6_8, {
    assert_eq!(decode_pair(&encode_pair(2, 6), 8).unwrap(), (2, 6));
});
audit_case!(pair_round_2_6_9, {
    assert_eq!(decode_pair(&encode_pair(2, 6), 9).unwrap(), (2, 6));
});
audit_case!(pair_round_2_7_8, {
    assert_eq!(decode_pair(&encode_pair(2, 7), 8).unwrap(), (2, 7));
});
audit_case!(pair_round_2_7_9, {
    assert_eq!(decode_pair(&encode_pair(2, 7), 9).unwrap(), (2, 7));
});
audit_case!(pair_round_2_7_10, {
    assert_eq!(decode_pair(&encode_pair(2, 7), 10).unwrap(), (2, 7));
});
audit_case!(pair_round_3_0_4, {
    assert_eq!(decode_pair(&encode_pair(3, 0), 4).unwrap(), (3, 0));
});
audit_case!(pair_round_3_0_5, {
    assert_eq!(decode_pair(&encode_pair(3, 0), 5).unwrap(), (3, 0));
});
audit_case!(pair_round_3_0_6, {
    assert_eq!(decode_pair(&encode_pair(3, 0), 6).unwrap(), (3, 0));
});
audit_case!(pair_round_3_1_4, {
    assert_eq!(decode_pair(&encode_pair(3, 1), 4).unwrap(), (3, 1));
});
audit_case!(pair_round_3_1_5, {
    assert_eq!(decode_pair(&encode_pair(3, 1), 5).unwrap(), (3, 1));
});
audit_case!(pair_round_3_1_6, {
    assert_eq!(decode_pair(&encode_pair(3, 1), 6).unwrap(), (3, 1));
});
audit_case!(pair_round_3_2_4, {
    assert_eq!(decode_pair(&encode_pair(3, 2), 4).unwrap(), (3, 2));
});
audit_case!(pair_round_3_2_5, {
    assert_eq!(decode_pair(&encode_pair(3, 2), 5).unwrap(), (3, 2));
});
audit_case!(pair_round_3_2_6, {
    assert_eq!(decode_pair(&encode_pair(3, 2), 6).unwrap(), (3, 2));
});
audit_case!(pair_round_3_3_4, {
    assert_eq!(decode_pair(&encode_pair(3, 3), 4).unwrap(), (3, 3));
});
audit_case!(pair_round_3_3_5, {
    assert_eq!(decode_pair(&encode_pair(3, 3), 5).unwrap(), (3, 3));
});
audit_case!(pair_round_3_3_6, {
    assert_eq!(decode_pair(&encode_pair(3, 3), 6).unwrap(), (3, 3));
});
audit_case!(pair_round_3_4_5, {
    assert_eq!(decode_pair(&encode_pair(3, 4), 5).unwrap(), (3, 4));
});
audit_case!(pair_round_3_4_6, {
    assert_eq!(decode_pair(&encode_pair(3, 4), 6).unwrap(), (3, 4));
});
audit_case!(pair_round_3_4_7, {
    assert_eq!(decode_pair(&encode_pair(3, 4), 7).unwrap(), (3, 4));
});
audit_case!(pair_round_3_5_6, {
    assert_eq!(decode_pair(&encode_pair(3, 5), 6).unwrap(), (3, 5));
});
audit_case!(pair_round_3_5_7, {
    assert_eq!(decode_pair(&encode_pair(3, 5), 7).unwrap(), (3, 5));
});
audit_case!(pair_round_3_5_8, {
    assert_eq!(decode_pair(&encode_pair(3, 5), 8).unwrap(), (3, 5));
});
audit_case!(pair_round_3_6_7, {
    assert_eq!(decode_pair(&encode_pair(3, 6), 7).unwrap(), (3, 6));
});
audit_case!(pair_round_3_6_8, {
    assert_eq!(decode_pair(&encode_pair(3, 6), 8).unwrap(), (3, 6));
});
audit_case!(pair_round_3_6_9, {
    assert_eq!(decode_pair(&encode_pair(3, 6), 9).unwrap(), (3, 6));
});
audit_case!(pair_round_3_7_8, {
    assert_eq!(decode_pair(&encode_pair(3, 7), 8).unwrap(), (3, 7));
});
audit_case!(pair_round_3_7_9, {
    assert_eq!(decode_pair(&encode_pair(3, 7), 9).unwrap(), (3, 7));
});
audit_case!(pair_round_3_7_10, {
    assert_eq!(decode_pair(&encode_pair(3, 7), 10).unwrap(), (3, 7));
});
audit_case!(pair_round_4_0_5, {
    assert_eq!(decode_pair(&encode_pair(4, 0), 5).unwrap(), (4, 0));
});
audit_case!(pair_round_4_0_6, {
    assert_eq!(decode_pair(&encode_pair(4, 0), 6).unwrap(), (4, 0));
});
audit_case!(pair_round_4_0_7, {
    assert_eq!(decode_pair(&encode_pair(4, 0), 7).unwrap(), (4, 0));
});
audit_case!(pair_round_4_1_5, {
    assert_eq!(decode_pair(&encode_pair(4, 1), 5).unwrap(), (4, 1));
});
audit_case!(pair_round_4_1_6, {
    assert_eq!(decode_pair(&encode_pair(4, 1), 6).unwrap(), (4, 1));
});
audit_case!(pair_round_4_1_7, {
    assert_eq!(decode_pair(&encode_pair(4, 1), 7).unwrap(), (4, 1));
});
audit_case!(pair_round_4_2_5, {
    assert_eq!(decode_pair(&encode_pair(4, 2), 5).unwrap(), (4, 2));
});
audit_case!(pair_round_4_2_6, {
    assert_eq!(decode_pair(&encode_pair(4, 2), 6).unwrap(), (4, 2));
});
audit_case!(pair_round_4_2_7, {
    assert_eq!(decode_pair(&encode_pair(4, 2), 7).unwrap(), (4, 2));
});
audit_case!(pair_round_4_3_5, {
    assert_eq!(decode_pair(&encode_pair(4, 3), 5).unwrap(), (4, 3));
});
audit_case!(pair_round_4_3_6, {
    assert_eq!(decode_pair(&encode_pair(4, 3), 6).unwrap(), (4, 3));
});
audit_case!(pair_round_4_3_7, {
    assert_eq!(decode_pair(&encode_pair(4, 3), 7).unwrap(), (4, 3));
});
audit_case!(pair_round_4_4_5, {
    assert_eq!(decode_pair(&encode_pair(4, 4), 5).unwrap(), (4, 4));
});
audit_case!(pair_round_4_4_6, {
    assert_eq!(decode_pair(&encode_pair(4, 4), 6).unwrap(), (4, 4));
});
audit_case!(pair_round_4_4_7, {
    assert_eq!(decode_pair(&encode_pair(4, 4), 7).unwrap(), (4, 4));
});
audit_case!(pair_round_4_5_6, {
    assert_eq!(decode_pair(&encode_pair(4, 5), 6).unwrap(), (4, 5));
});
audit_case!(pair_round_4_5_7, {
    assert_eq!(decode_pair(&encode_pair(4, 5), 7).unwrap(), (4, 5));
});
audit_case!(pair_round_4_5_8, {
    assert_eq!(decode_pair(&encode_pair(4, 5), 8).unwrap(), (4, 5));
});
audit_case!(pair_round_4_6_7, {
    assert_eq!(decode_pair(&encode_pair(4, 6), 7).unwrap(), (4, 6));
});
audit_case!(pair_round_4_6_8, {
    assert_eq!(decode_pair(&encode_pair(4, 6), 8).unwrap(), (4, 6));
});
audit_case!(pair_round_4_6_9, {
    assert_eq!(decode_pair(&encode_pair(4, 6), 9).unwrap(), (4, 6));
});
audit_case!(pair_round_4_7_8, {
    assert_eq!(decode_pair(&encode_pair(4, 7), 8).unwrap(), (4, 7));
});
audit_case!(pair_round_4_7_9, {
    assert_eq!(decode_pair(&encode_pair(4, 7), 9).unwrap(), (4, 7));
});
audit_case!(pair_round_4_7_10, {
    assert_eq!(decode_pair(&encode_pair(4, 7), 10).unwrap(), (4, 7));
});
audit_case!(pair_round_5_0_6, {
    assert_eq!(decode_pair(&encode_pair(5, 0), 6).unwrap(), (5, 0));
});
audit_case!(pair_round_5_0_7, {
    assert_eq!(decode_pair(&encode_pair(5, 0), 7).unwrap(), (5, 0));
});
audit_case!(pair_round_5_0_8, {
    assert_eq!(decode_pair(&encode_pair(5, 0), 8).unwrap(), (5, 0));
});
audit_case!(pair_round_5_1_6, {
    assert_eq!(decode_pair(&encode_pair(5, 1), 6).unwrap(), (5, 1));
});
audit_case!(pair_round_5_1_7, {
    assert_eq!(decode_pair(&encode_pair(5, 1), 7).unwrap(), (5, 1));
});
audit_case!(pair_round_5_1_8, {
    assert_eq!(decode_pair(&encode_pair(5, 1), 8).unwrap(), (5, 1));
});
audit_case!(pair_round_5_2_6, {
    assert_eq!(decode_pair(&encode_pair(5, 2), 6).unwrap(), (5, 2));
});
audit_case!(pair_round_5_2_7, {
    assert_eq!(decode_pair(&encode_pair(5, 2), 7).unwrap(), (5, 2));
});
audit_case!(pair_round_5_2_8, {
    assert_eq!(decode_pair(&encode_pair(5, 2), 8).unwrap(), (5, 2));
});
audit_case!(pair_round_5_3_6, {
    assert_eq!(decode_pair(&encode_pair(5, 3), 6).unwrap(), (5, 3));
});
audit_case!(pair_round_5_3_7, {
    assert_eq!(decode_pair(&encode_pair(5, 3), 7).unwrap(), (5, 3));
});
audit_case!(pair_round_5_3_8, {
    assert_eq!(decode_pair(&encode_pair(5, 3), 8).unwrap(), (5, 3));
});
audit_case!(pair_round_5_4_6, {
    assert_eq!(decode_pair(&encode_pair(5, 4), 6).unwrap(), (5, 4));
});
audit_case!(pair_round_5_4_7, {
    assert_eq!(decode_pair(&encode_pair(5, 4), 7).unwrap(), (5, 4));
});
audit_case!(pair_round_5_4_8, {
    assert_eq!(decode_pair(&encode_pair(5, 4), 8).unwrap(), (5, 4));
});
audit_case!(pair_round_5_5_6, {
    assert_eq!(decode_pair(&encode_pair(5, 5), 6).unwrap(), (5, 5));
});
audit_case!(pair_round_5_5_7, {
    assert_eq!(decode_pair(&encode_pair(5, 5), 7).unwrap(), (5, 5));
});
audit_case!(pair_round_5_5_8, {
    assert_eq!(decode_pair(&encode_pair(5, 5), 8).unwrap(), (5, 5));
});
audit_case!(pair_round_5_6_7, {
    assert_eq!(decode_pair(&encode_pair(5, 6), 7).unwrap(), (5, 6));
});
audit_case!(pair_round_5_6_8, {
    assert_eq!(decode_pair(&encode_pair(5, 6), 8).unwrap(), (5, 6));
});
audit_case!(pair_round_5_6_9, {
    assert_eq!(decode_pair(&encode_pair(5, 6), 9).unwrap(), (5, 6));
});
audit_case!(pair_round_5_7_8, {
    assert_eq!(decode_pair(&encode_pair(5, 7), 8).unwrap(), (5, 7));
});
audit_case!(pair_round_5_7_9, {
    assert_eq!(decode_pair(&encode_pair(5, 7), 9).unwrap(), (5, 7));
});
audit_case!(pair_round_5_7_10, {
    assert_eq!(decode_pair(&encode_pair(5, 7), 10).unwrap(), (5, 7));
});
audit_case!(pair_round_6_0_7, {
    assert_eq!(decode_pair(&encode_pair(6, 0), 7).unwrap(), (6, 0));
});
audit_case!(pair_round_6_0_8, {
    assert_eq!(decode_pair(&encode_pair(6, 0), 8).unwrap(), (6, 0));
});
audit_case!(pair_round_6_0_9, {
    assert_eq!(decode_pair(&encode_pair(6, 0), 9).unwrap(), (6, 0));
});
audit_case!(pair_round_6_1_7, {
    assert_eq!(decode_pair(&encode_pair(6, 1), 7).unwrap(), (6, 1));
});
audit_case!(pair_round_6_1_8, {
    assert_eq!(decode_pair(&encode_pair(6, 1), 8).unwrap(), (6, 1));
});
audit_case!(pair_round_6_1_9, {
    assert_eq!(decode_pair(&encode_pair(6, 1), 9).unwrap(), (6, 1));
});
audit_case!(pair_round_6_2_7, {
    assert_eq!(decode_pair(&encode_pair(6, 2), 7).unwrap(), (6, 2));
});
audit_case!(pair_round_6_2_8, {
    assert_eq!(decode_pair(&encode_pair(6, 2), 8).unwrap(), (6, 2));
});
audit_case!(pair_round_6_2_9, {
    assert_eq!(decode_pair(&encode_pair(6, 2), 9).unwrap(), (6, 2));
});
audit_case!(pair_round_6_3_7, {
    assert_eq!(decode_pair(&encode_pair(6, 3), 7).unwrap(), (6, 3));
});
audit_case!(pair_round_6_3_8, {
    assert_eq!(decode_pair(&encode_pair(6, 3), 8).unwrap(), (6, 3));
});
audit_case!(pair_round_6_3_9, {
    assert_eq!(decode_pair(&encode_pair(6, 3), 9).unwrap(), (6, 3));
});
audit_case!(pair_round_6_4_7, {
    assert_eq!(decode_pair(&encode_pair(6, 4), 7).unwrap(), (6, 4));
});
audit_case!(pair_round_6_4_8, {
    assert_eq!(decode_pair(&encode_pair(6, 4), 8).unwrap(), (6, 4));
});
audit_case!(pair_round_6_4_9, {
    assert_eq!(decode_pair(&encode_pair(6, 4), 9).unwrap(), (6, 4));
});
audit_case!(pair_round_6_5_7, {
    assert_eq!(decode_pair(&encode_pair(6, 5), 7).unwrap(), (6, 5));
});
audit_case!(pair_round_6_5_8, {
    assert_eq!(decode_pair(&encode_pair(6, 5), 8).unwrap(), (6, 5));
});
audit_case!(pair_round_6_5_9, {
    assert_eq!(decode_pair(&encode_pair(6, 5), 9).unwrap(), (6, 5));
});
audit_case!(pair_round_6_6_7, {
    assert_eq!(decode_pair(&encode_pair(6, 6), 7).unwrap(), (6, 6));
});
audit_case!(pair_round_6_6_8, {
    assert_eq!(decode_pair(&encode_pair(6, 6), 8).unwrap(), (6, 6));
});
audit_case!(pair_round_6_6_9, {
    assert_eq!(decode_pair(&encode_pair(6, 6), 9).unwrap(), (6, 6));
});
audit_case!(pair_round_6_7_8, {
    assert_eq!(decode_pair(&encode_pair(6, 7), 8).unwrap(), (6, 7));
});
audit_case!(pair_round_6_7_9, {
    assert_eq!(decode_pair(&encode_pair(6, 7), 9).unwrap(), (6, 7));
});
audit_case!(pair_round_6_7_10, {
    assert_eq!(decode_pair(&encode_pair(6, 7), 10).unwrap(), (6, 7));
});
audit_case!(pair_round_7_0_8, {
    assert_eq!(decode_pair(&encode_pair(7, 0), 8).unwrap(), (7, 0));
});
audit_case!(pair_round_7_0_9, {
    assert_eq!(decode_pair(&encode_pair(7, 0), 9).unwrap(), (7, 0));
});
audit_case!(pair_round_7_0_10, {
    assert_eq!(decode_pair(&encode_pair(7, 0), 10).unwrap(), (7, 0));
});
audit_case!(pair_round_7_1_8, {
    assert_eq!(decode_pair(&encode_pair(7, 1), 8).unwrap(), (7, 1));
});
audit_case!(pair_round_7_1_9, {
    assert_eq!(decode_pair(&encode_pair(7, 1), 9).unwrap(), (7, 1));
});
audit_case!(pair_round_7_1_10, {
    assert_eq!(decode_pair(&encode_pair(7, 1), 10).unwrap(), (7, 1));
});
audit_case!(pair_round_7_2_8, {
    assert_eq!(decode_pair(&encode_pair(7, 2), 8).unwrap(), (7, 2));
});
audit_case!(pair_round_7_2_9, {
    assert_eq!(decode_pair(&encode_pair(7, 2), 9).unwrap(), (7, 2));
});
audit_case!(pair_round_7_2_10, {
    assert_eq!(decode_pair(&encode_pair(7, 2), 10).unwrap(), (7, 2));
});
audit_case!(pair_round_7_3_8, {
    assert_eq!(decode_pair(&encode_pair(7, 3), 8).unwrap(), (7, 3));
});
audit_case!(pair_round_7_3_9, {
    assert_eq!(decode_pair(&encode_pair(7, 3), 9).unwrap(), (7, 3));
});
audit_case!(pair_round_7_3_10, {
    assert_eq!(decode_pair(&encode_pair(7, 3), 10).unwrap(), (7, 3));
});
audit_case!(pair_round_7_4_8, {
    assert_eq!(decode_pair(&encode_pair(7, 4), 8).unwrap(), (7, 4));
});
audit_case!(pair_round_7_4_9, {
    assert_eq!(decode_pair(&encode_pair(7, 4), 9).unwrap(), (7, 4));
});
audit_case!(pair_round_7_4_10, {
    assert_eq!(decode_pair(&encode_pair(7, 4), 10).unwrap(), (7, 4));
});
audit_case!(pair_round_7_5_8, {
    assert_eq!(decode_pair(&encode_pair(7, 5), 8).unwrap(), (7, 5));
});
audit_case!(pair_round_7_5_9, {
    assert_eq!(decode_pair(&encode_pair(7, 5), 9).unwrap(), (7, 5));
});
audit_case!(pair_round_7_5_10, {
    assert_eq!(decode_pair(&encode_pair(7, 5), 10).unwrap(), (7, 5));
});
audit_case!(pair_round_7_6_8, {
    assert_eq!(decode_pair(&encode_pair(7, 6), 8).unwrap(), (7, 6));
});
audit_case!(pair_round_7_6_9, {
    assert_eq!(decode_pair(&encode_pair(7, 6), 9).unwrap(), (7, 6));
});
audit_case!(pair_round_7_6_10, {
    assert_eq!(decode_pair(&encode_pair(7, 6), 10).unwrap(), (7, 6));
});
audit_case!(pair_round_7_7_8, {
    assert_eq!(decode_pair(&encode_pair(7, 7), 8).unwrap(), (7, 7));
});
audit_case!(pair_round_7_7_9, {
    assert_eq!(decode_pair(&encode_pair(7, 7), 9).unwrap(), (7, 7));
});
audit_case!(pair_round_7_7_10, {
    assert_eq!(decode_pair(&encode_pair(7, 7), 10).unwrap(), (7, 7));
});
audit_case!(pair_bad_0, {
    assert!(matches!(
        decode_pair("", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_1, {
    assert!(matches!(
        decode_pair("1", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_2, {
    assert!(matches!(
        decode_pair("a,b", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_3, {
    assert!(matches!(
        decode_pair("1,", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_4, {
    assert!(matches!(
        decode_pair(",2", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_5, {
    assert!(matches!(
        decode_pair("1,2,3", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_6, {
    assert!(matches!(
        decode_pair("1;2", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(pair_bad_7, {
    assert!(matches!(
        decode_pair("1 2", 4),
        Err(BackendError::BadTwoQubitKey(_))
    ));
});
audit_case!(q_bad_0, {
    assert!(matches!(
        decode_qubit("", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
audit_case!(q_bad_1, {
    assert!(matches!(
        decode_qubit("x", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
audit_case!(q_bad_2, {
    assert!(matches!(
        decode_qubit("-1", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
audit_case!(q_bad_3, {
    assert!(matches!(
        decode_qubit("1.5", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
audit_case!(q_bad_4, {
    assert!(matches!(
        decode_qubit("  ", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
audit_case!(q_bad_5, {
    assert!(matches!(
        decode_qubit("00a", 4),
        Err(BackendError::BadQubitKey(_))
    ));
});
