// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `backend` — `descriptor JSON`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

audit_case!(ok_2, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_3, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":3,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_4, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":4,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_5, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":5,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_6, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":6,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_7, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":7,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_8, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":8,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(ok_9, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":9,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_ok());
});
audit_case!(deny_unknown_0, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false,\"typo\":1}").is_err());
});
audit_case!(deny_unknown_1, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false,\"extra_field\":true}").is_err());
});
audit_case!(deny_unknown_2, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false,\"num_qubit\":3}").is_err());
});
audit_case!(bad_gate_0, {
    assert!(matches!(
        backend::json::from_str(
            "{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"not_a_gate\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}"
        ),
        Err(backend::BackendError::UnknownGate(_))
    ));
});
audit_case!(bad_gate_1, {
    assert!(matches!(
        backend::json::from_str(
            "{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"CNOT\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}"
        ),
        Err(backend::BackendError::UnknownGate(_))
    ));
});
audit_case!(bad_gate_2, {
    assert!(matches!(
        backend::json::from_str(
            "{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[]},\"native_gates\":[\"\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}"
        ),
        Err(backend::BackendError::UnknownGate(_))
    ));
});
audit_case!(bad_edge_0, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[[0,0]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_err());
});
audit_case!(bad_edge_1, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":2,\"topology\":{\"edges\":[[0,5]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_err());
});
audit_case!(bad_edge_2, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":3,\"topology\":{\"edges\":[[1,9]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_err());
});
audit_case!(bad_edge_3, {
    assert!(backend::json::from_str("{\"id\":\"t\",\"num_qubits\":1,\"topology\":{\"edges\":[[0,1]]},\"native_gates\":[\"h\"],\"meas_latency_us\":0.0,\"supports_mid_circuit_meas\":false,\"supports_feed_forward\":false}").is_err());
});
audit_case!(bad_json_0, {
    assert!(backend::json::from_str("{").is_err());
});
audit_case!(bad_json_1, {
    assert!(backend::json::from_str("not json").is_err());
});
audit_case!(bad_json_2, {
    assert!(backend::json::from_str("{\"id\":}").is_err());
});
audit_case!(bad_json_3, {
    assert!(backend::json::from_str("[]").is_err());
});
