// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `backend` — `gates`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use backend::BackendError;
use backend::gates::native_gate;

audit_case!(gate_h, {
    let g = native_gate("h").unwrap();
    assert_eq!(g.name, "h");
    assert_eq!(g.num_qubits, 1);
});
audit_case!(gate_x, {
    let g = native_gate("x").unwrap();
    assert_eq!(g.name, "x");
    assert_eq!(g.num_qubits, 1);
});
audit_case!(gate_cx, {
    let g = native_gate("cx").unwrap();
    assert_eq!(g.name, "cx");
    assert_eq!(g.num_qubits, 2);
});
audit_case!(gate_ccx, {
    let g = native_gate("ccx").unwrap();
    assert_eq!(g.name, "ccx");
    assert_eq!(g.num_qubits, 3);
});
audit_case!(gate_swap, {
    let g = native_gate("swap").unwrap();
    assert_eq!(g.name, "swap");
    assert_eq!(g.num_qubits, 2);
});
audit_case!(gate_rz, {
    let g = native_gate("rz").unwrap();
    assert_eq!(g.name, "rz");
    assert_eq!(g.num_qubits, 1);
});
audit_case!(gate_u3, {
    let g = native_gate("u3").unwrap();
    assert_eq!(g.name, "u3");
    assert_eq!(g.num_qubits, 1);
});
audit_case!(unknown_0, {
    assert!(matches!(
        native_gate("H"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_1, {
    assert!(matches!(
        native_gate("CNOT"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_2, {
    assert!(matches!(
        native_gate("totally_fake"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_3, {
    assert!(matches!(native_gate(""), Err(BackendError::UnknownGate(_))));
});
audit_case!(unknown_4, {
    assert!(matches!(
        native_gate("cx "),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_5, {
    assert!(matches!(
        native_gate(" ccx"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_6, {
    assert!(matches!(
        native_gate("hadamard"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_7, {
    assert!(matches!(
        native_gate("cnot"),
        Err(BackendError::UnknownGate(_))
    ));
});
audit_case!(unknown_8, {
    assert!(matches!(
        native_gate("toffoli"),
        Err(BackendError::UnknownGate(_))
    ));
});
