// @generated by scripts/gen_audit_tests.py — do not edit by hand.
#![allow(unused_imports)]
#![allow(non_snake_case)]
//! Audit tests for `frontend` — `lexer`.

macro_rules! audit_case {
    ($name:ident, $body:expr) => {
        mod $name {
            use super::*;
            #[test]
            fn it() {
                $body
            }
        }
    };
}

use frontend::lexer::{Token, lex};

fn toks(src: &str) -> Vec<Token> {
    lex(src).unwrap().into_iter().map(|(t, _)| t).collect()
}
fn tok(src: &str) -> Vec<Token> {
    toks(src)
}

audit_case!(kw_fn, {
    assert_eq!(tok("fn"), vec![Token::Fn]);
});
audit_case!(kw_type, {
    assert_eq!(tok("type"), vec![Token::Type]);
});
audit_case!(kw_let, {
    assert_eq!(tok("let"), vec![Token::Let]);
});
audit_case!(kw_in, {
    assert_eq!(tok("in"), vec![Token::In]);
});
audit_case!(kw_return, {
    assert_eq!(tok("return"), vec![Token::Return]);
});
audit_case!(kw_match, {
    assert_eq!(tok("match"), vec![Token::Match]);
});
audit_case!(kw_circuit, {
    assert_eq!(tok("circuit"), vec![Token::Circuit]);
});
audit_case!(kw_run, {
    assert_eq!(tok("run"), vec![Token::Run]);
});
audit_case!(kw_borrow, {
    assert_eq!(tok("borrow"), vec![Token::Borrow]);
});
audit_case!(kw_for, {
    assert_eq!(tok("for"), vec![Token::For]);
});
audit_case!(kw_if, {
    assert_eq!(tok("if"), vec![Token::If]);
});
audit_case!(kw_then, {
    assert_eq!(tok("then"), vec![Token::Then]);
});
audit_case!(kw_else, {
    assert_eq!(tok("else"), vec![Token::Else]);
});
audit_case!(kw_true, {
    assert_eq!(tok("true"), vec![Token::True]);
});
audit_case!(kw_false, {
    assert_eq!(tok("false"), vec![Token::False]);
});
audit_case!(kw_adjoint, {
    assert_eq!(tok("adjoint"), vec![Token::Adjoint]);
});
audit_case!(kw_controlled, {
    assert_eq!(tok("controlled"), vec![Token::Controlled]);
});
audit_case!(kw_par, {
    assert_eq!(tok("par"), vec![Token::Par]);
});
audit_case!(op_00, {
    assert_eq!(tok("|>"), vec![Token::Pipe]);
});
audit_case!(op_01, {
    assert_eq!(tok("<-"), vec![Token::Bind]);
});
audit_case!(op_02, {
    assert_eq!(tok("->"), vec![Token::Arrow]);
});
audit_case!(op_03, {
    assert_eq!(tok("-o"), vec![Token::LinearArrow]);
});
audit_case!(op_04, {
    assert_eq!(tok("=>"), vec![Token::FatArrow]);
});
audit_case!(op_05, {
    assert_eq!(tok("+"), vec![Token::Plus]);
});
audit_case!(op_06, {
    assert_eq!(tok("-"), vec![Token::Minus]);
});
audit_case!(op_07, {
    assert_eq!(tok("*"), vec![Token::Star]);
});
audit_case!(op_08, {
    assert_eq!(tok("/"), vec![Token::Slash]);
});
audit_case!(op_09, {
    assert_eq!(tok("^"), vec![Token::Caret]);
});
audit_case!(op_10, {
    assert_eq!(tok("="), vec![Token::Eq]);
});
audit_case!(op_11, {
    assert_eq!(tok(":"), vec![Token::Colon]);
});
audit_case!(op_12, {
    assert_eq!(tok(","), vec![Token::Comma]);
});
audit_case!(op_13, {
    assert_eq!(tok("."), vec![Token::Dot]);
});
audit_case!(op_14, {
    assert_eq!(tok("_"), vec![Token::Underscore]);
});
audit_case!(op_15, {
    assert_eq!(tok("`"), vec![Token::Backtick]);
});
audit_case!(op_16, {
    assert_eq!(tok("|"), vec![Token::Bar]);
});
audit_case!(int_neg_16, {
    assert_eq!(tok("-16"), vec![Token::Minus, Token::Int(16)]);
});
audit_case!(int_neg_15, {
    assert_eq!(tok("-15"), vec![Token::Minus, Token::Int(15)]);
});
audit_case!(int_neg_14, {
    assert_eq!(tok("-14"), vec![Token::Minus, Token::Int(14)]);
});
audit_case!(int_neg_13, {
    assert_eq!(tok("-13"), vec![Token::Minus, Token::Int(13)]);
});
audit_case!(int_neg_12, {
    assert_eq!(tok("-12"), vec![Token::Minus, Token::Int(12)]);
});
audit_case!(int_neg_11, {
    assert_eq!(tok("-11"), vec![Token::Minus, Token::Int(11)]);
});
audit_case!(int_neg_10, {
    assert_eq!(tok("-10"), vec![Token::Minus, Token::Int(10)]);
});
audit_case!(int_neg_9, {
    assert_eq!(tok("-9"), vec![Token::Minus, Token::Int(9)]);
});
audit_case!(int_neg_8, {
    assert_eq!(tok("-8"), vec![Token::Minus, Token::Int(8)]);
});
audit_case!(int_neg_7, {
    assert_eq!(tok("-7"), vec![Token::Minus, Token::Int(7)]);
});
audit_case!(int_neg_6, {
    assert_eq!(tok("-6"), vec![Token::Minus, Token::Int(6)]);
});
audit_case!(int_neg_5, {
    assert_eq!(tok("-5"), vec![Token::Minus, Token::Int(5)]);
});
audit_case!(int_neg_4, {
    assert_eq!(tok("-4"), vec![Token::Minus, Token::Int(4)]);
});
audit_case!(int_neg_3, {
    assert_eq!(tok("-3"), vec![Token::Minus, Token::Int(3)]);
});
audit_case!(int_neg_2, {
    assert_eq!(tok("-2"), vec![Token::Minus, Token::Int(2)]);
});
audit_case!(int_neg_1, {
    assert_eq!(tok("-1"), vec![Token::Minus, Token::Int(1)]);
});
audit_case!(int_0, {
    assert_eq!(tok("0"), vec![Token::Int(0)]);
});
audit_case!(int_1, {
    assert_eq!(tok("1"), vec![Token::Int(1)]);
});
audit_case!(int_2, {
    assert_eq!(tok("2"), vec![Token::Int(2)]);
});
audit_case!(int_3, {
    assert_eq!(tok("3"), vec![Token::Int(3)]);
});
audit_case!(int_4, {
    assert_eq!(tok("4"), vec![Token::Int(4)]);
});
audit_case!(int_5, {
    assert_eq!(tok("5"), vec![Token::Int(5)]);
});
audit_case!(int_6, {
    assert_eq!(tok("6"), vec![Token::Int(6)]);
});
audit_case!(int_7, {
    assert_eq!(tok("7"), vec![Token::Int(7)]);
});
audit_case!(int_8, {
    assert_eq!(tok("8"), vec![Token::Int(8)]);
});
audit_case!(int_9, {
    assert_eq!(tok("9"), vec![Token::Int(9)]);
});
audit_case!(int_10, {
    assert_eq!(tok("10"), vec![Token::Int(10)]);
});
audit_case!(int_11, {
    assert_eq!(tok("11"), vec![Token::Int(11)]);
});
audit_case!(int_12, {
    assert_eq!(tok("12"), vec![Token::Int(12)]);
});
audit_case!(int_13, {
    assert_eq!(tok("13"), vec![Token::Int(13)]);
});
audit_case!(int_14, {
    assert_eq!(tok("14"), vec![Token::Int(14)]);
});
audit_case!(int_15, {
    assert_eq!(tok("15"), vec![Token::Int(15)]);
});
audit_case!(float_0, {
    assert_eq!(tok("0.0"), vec![Token::Float(0.0)]);
});
audit_case!(float_1, {
    assert_eq!(tok("1.5"), vec![Token::Float(1.5)]);
});
audit_case!(float_2, {
    assert_eq!(tok("2.75"), vec![Token::Float(2.75)]);
});
audit_case!(float_3, {
    assert_eq!(tok("-2.5"), vec![Token::Minus, Token::Float(2.5)]);
});
audit_case!(float_4, {
    assert_eq!(tok("1.0e3"), vec![Token::Float(1000.0)]);
});
audit_case!(float_5, {
    assert_eq!(tok("1.0e-2"), vec![Token::Float(0.01)]);
});
audit_case!(id_foo, {
    assert_eq!(tok("foo"), vec![Token::Ident("foo".into())]);
});
audit_case!(id_bar_baz, {
    assert_eq!(tok("bar_baz"), vec![Token::Ident("bar_baz".into())]);
});
audit_case!(id_H, {
    assert_eq!(tok("H"), vec![Token::Ident("H".into())]);
});
audit_case!(id_q0, {
    assert_eq!(tok("q0"), vec![Token::Ident("q0".into())]);
});
audit_case!(id__hidden, {
    assert_eq!(tok("_hidden"), vec![Token::Ident("_hidden".into())]);
});
audit_case!(id_QFT, {
    assert_eq!(tok("QFT"), vec![Token::Ident("QFT".into())]);
});
audit_case!(id_measure, {
    assert_eq!(tok("measure"), vec![Token::Ident("measure".into())]);
});
audit_case!(id_letx, {
    assert_eq!(tok("letx"), vec![Token::Ident("letx".into())]);
});
