#!/usr/bin/env python3
"""Generate audit test modules with one #[test] per submodule.

Run from the repo root:
    python3 scripts/gen_audit_tests.py

Each generated file is marked @generated and should not be hand-edited.
"""

from __future__ import annotations

import itertools
import os
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def rust_str(s: str) -> str:
    """Format a Python string as a Rust `&str` literal."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def header(crate: str, module: str) -> str:
    return textwrap.dedent(
        f"""\
        // @generated by scripts/gen_audit_tests.py — do not edit by hand.
        #![allow(unused_imports)]
        #![allow(non_snake_case)]
        //! Audit tests for `{crate}` — `{module}`.

        macro_rules! audit_case {{
            ($name:ident, $body:expr) => {{
                mod $name {{
                    use super::*;
                    #[test]
                    fn it() {{
                        $body
                    }}
                }}
            }};
        }}

        """
    )


def write(path: Path, body: str) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return body.count("audit_case!(")


def gen_depth_parse() -> int:
    cases: list[tuple[str, str]] = []
    # Valid literals and variables
    for n in range(256):
        cases.append((f"depth_nat_{n:04d}", f"assert_eq!(DepthExpr::parse({rust_str(str(n))}).unwrap(), DepthExpr::Nat({n}));"))
    for name in ["n", "m", "k", "depth", "foo", "bar_baz", "x1", "qft_depth"]:
        cases.append(
            (f"depth_var_{name}", f'assert_eq!(DepthExpr::parse({rust_str(name)}).unwrap(), DepthExpr::Var({rust_str(name)}.into()));')
        )
    # Valid binary forms
    ops = [
        ("+", "seq"),
        ("*", "repeat"),
        ("max", "par"),
    ]
    idx = 0
    for a in range(16):
        for b in range(16):
            for op, comb in ops:
                if idx >= 200:
                    break
                lhs, rhs = a, b
                src = f"({op} {lhs} {rhs})"
                if comb == "seq":
                    body = f"let got = DepthExpr::parse({rust_str(src)}).unwrap(); assert!(got.equiv(&DepthExpr::Nat({lhs}).seq(DepthExpr::Nat({rhs}))));"
                elif comb == "repeat":
                    body = f"let got = DepthExpr::parse({rust_str(src)}).unwrap(); assert!(got.equiv(&DepthExpr::repeat(DepthExpr::Nat({lhs}), DepthExpr::Nat({rhs}))));"
                else:
                    body = f"let got = DepthExpr::parse({rust_str(src)}).unwrap(); assert!(got.equiv(&DepthExpr::Nat({lhs}).par(DepthExpr::Nat({rhs}))));"
                cases.append((f"depth_bin_{idx:04d}", body))
                idx += 1
    # Parse errors (inputs must not succeed as a full expression)
    bad_inputs = [
        "",
        " ",
        "(",
        "(+ 1",
        "(+ 1 2 3)",
        "(foo 1 2)",
        "(+ a b) extra",
        "(max)",
        "(+)",
        "(1 2)",
        "(unknown 1 2)",
    ]
    for i, src in enumerate(bad_inputs):
        cases.append((f"depth_err_{i:04d}", f"assert!(DepthExpr::parse({rust_str(src)}).is_err());"))
    # Edge cases that parse successfully but encode non-standard atoms / ops
    cases.append(
        (
            "depth_atom_plus_plus_one",
            f"assert_eq!(DepthExpr::parse({rust_str('++1')}), Ok(DepthExpr::Var({rust_str('++1')}.into())));",
        )
    )
    cases.append(
        (
            "depth_div_by_zero_parses",
            f"assert_eq!(DepthExpr::parse({rust_str('(/ 1 0)')}), Ok(DepthExpr::Nat(1).quot(DepthExpr::Nat(0))));",
        )
    )
    # Trailing tokens
    for i, src in enumerate(["1 2", "n n", "(+ 1 2) 3", "42 junk"]):
        cases.append((f"depth_trail_{i:04d}", f"assert_eq!(DepthExpr::parse({rust_str(src)}), Err(DepthParseError::TrailingTokens));"))

    lines = [header("quon_core", "depth parse"), "use quon_core::{DepthExpr, DepthParseError};\n\n"]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "quon_core/tests/audit_depth_parse.rs", "".join(lines))


def gen_depth_const() -> int:
    cases: list[tuple[str, str]] = []
    for a in range(16):
        for b in range(16):
            cases.append(
                (
                    f"const_add_{a:02d}_{b:02d}",
                    f"assert_eq!(DepthExpr::Nat({a}).seq(DepthExpr::Nat({b})).as_const(), Some({a + b}));",
                )
            )
    for a in range(12):
        for b in range(12):
            cases.append(
                (
                    f"const_mul_{a:02d}_{b:02d}",
                    f"assert_eq!(DepthExpr::repeat(DepthExpr::Nat({a}), DepthExpr::Nat({b})).as_const(), Some({a * b}));",
                )
            )
    for a in range(12):
        for b in range(12):
            cases.append(
                (
                    f"const_max_{a:02d}_{b:02d}",
                    f"assert_eq!(DepthExpr::Nat({a}).par(DepthExpr::Nat({b})).as_const(), Some({max(a, b)}));",
                )
            )
    for a in range(12):
        for b in range(1, 12):
            cases.append(
                (
                    f"const_div_{a:02d}_{b:02d}",
                    f"assert_eq!(DepthExpr::Nat({a}).quot(DepthExpr::Nat({b})).as_const(), Some({a // b}));",
                )
            )
    for v in ["n", "x", "depth"]:
        cases.append((f"var_no_const_{v}", f'assert_eq!(DepthExpr::Var("{v}".into()).as_const(), None);'))
    cases.append(("hole_no_const", "assert_eq!(DepthExpr::Hole.as_const(), None);"))

    lines = [header("quon_core", "depth as_const"), "use quon_core::DepthExpr;\n\n"]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "quon_core/tests/audit_depth_const.rs", "".join(lines))


def gen_linearity() -> int:
    cases: list[tuple[str, str]] = []
    for count in range(8):
        for measure in (False, True):
            for other in (False, True):
                m = str(measure).lower()
                o = str(other).lower()
                name = f"cls_{count}_{int(measure)}_{int(other)}"
                if count == 1:
                    body = (
                        f"assert!(classify_use_count({count}, {m}, {o}).is_none());"
                    )
                elif count == 0:
                    body = (
                        f"assert_eq!(classify_use_count({count}, {m}, {o}), "
                        f"Some(UseCountViolation::Unused));"
                    )
                elif count > 1 and measure and other:
                    body = (
                        f"assert_eq!(classify_use_count({count}, {m}, {o}), "
                        f"Some(UseCountViolation::ReuseAfterMeasure));"
                    )
                else:
                    body = (
                        f"assert!(matches!(classify_use_count({count}, {m}, {o}), "
                        f"Some(UseCountViolation::MultiUse {{ count: {count} }})));"
                    )
                cases.append((name, body))
    for ops in range(1, 8):
        for res in range(1, 8):
            ok = ops == res and ops >= 1
            if ok:
                body = f"assert!(barrier_identity_ok({ops}, {res}));"
            else:
                body = f"assert!(!barrier_identity_ok({ops}, {res}));"
            cases.append((f"barrier_{ops}_{res}", body))
    for a in range(8):
        for b in range(8):
            if a == b:
                body = f"assert!(if_qubit_threading_ok({a}, {b}));"
            else:
                body = f"assert!(!if_qubit_threading_ok({a}, {b}));"
            cases.append((f"if_thread_{a}_{b}", body))
    lines = [
        header("quon_core", "linearity"),
        "use quon_core::{classify_use_count, UseCountViolation, barrier_identity_ok, if_qubit_threading_ok};\n\n",
    ]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "quon_core/tests/audit_linearity.rs", "".join(lines))


def gen_optimization() -> int:
    cases: list[tuple[str, str]] = []
    for cur in range(24):
        for rem in range(24):
            exp = 0 if rem >= cur else cur - rem
            cases.append(
                (
                    f"rem_{cur:02d}_{rem:02d}",
                    f"assert_eq!(depth_after_removal({cur}, {rem}), {exp});",
                )
            )
    for a in range(20):
        for b in range(20):
            cases.append((f"seq_{a:02d}_{b:02d}", f"assert_eq!(seq_depth({a}, {b}), {a + b});"))
            cases.append((f"par_{a:02d}_{b:02d}", f"assert_eq!(par_depth({a}, {b}), {max(a, b)});"))
    for before in range(12):
        for after in range(12):
            if before == after:
                body = f"assert!(arity_preserved({before}, {after}));"
            else:
                body = f"assert!(!arity_preserved({before}, {after}));"
            cases.append((f"arity_{before}_{after}", body))
    for l in range(5):
        for r in range(5):
            if l == 1 and r == 1:
                body = f"assert!(single_qubit_pair({l}, {r}));"
            else:
                body = f"assert!(!single_qubit_pair({l}, {r}));"
            cases.append((f"pair_{l}_{r}", body))
    lines = [
        header("quon_core", "optimization"),
        "use quon_core::optimization::{depth_after_removal, seq_depth, par_depth, arity_preserved, single_qubit_pair};\n\n",
    ]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "quon_core/tests/audit_optimization.rs", "".join(lines))


def gen_backend_keys() -> int:
    cases: list[tuple[str, str]] = []
    for q in range(32):
        for n in range(q + 1, q + 4):
            cases.append(
                (
                    f"q_round_{q}_{n}",
                    f"assert_eq!(decode_qubit(&encode_qubit({q}), {n}).unwrap(), {q});",
                )
            )
    for q in range(32):
        cases.append(
            (
                f"q_oob_{q}",
                f"assert!(matches!(decode_qubit(&encode_qubit({q}), {q}), Err(BackendError::QubitOutOfRange {{ .. }})));",
            )
        )
    for u in range(8):
        for v in range(8):
            for n in range(max(u, v) + 1, max(u, v) + 4):
                cases.append(
                    (
                        f"pair_round_{u}_{v}_{n}",
                        f"assert_eq!(decode_pair(&encode_pair({u}, {v}), {n}).unwrap(), ({u}, {v}));",
                    )
                )
    bad_pairs = ["", "1", "a,b", "1,", ",2", "1,2,3", "1;2", "1 2"]
    for i, key in enumerate(bad_pairs):
        cases.append(
            (
                f"pair_bad_{i}",
                f"assert!(matches!(decode_pair({rust_str(key)}, 4), Err(BackendError::BadTwoQubitKey(_))));",
            )
        )
    bad_qubits = ["", "x", "-1", "1.5", "  ", "00a"]
    for i, key in enumerate(bad_qubits):
        cases.append(
            (
                f"q_bad_{i}",
                f"assert!(matches!(decode_qubit({rust_str(key)}, 4), Err(BackendError::BadQubitKey(_))));",
            )
        )
    lines = [
        header("backend", "keys"),
        "use backend::keys::{decode_pair, decode_qubit, encode_pair, encode_qubit};\n",
        "use backend::BackendError;\n\n",
    ]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "backend/tests/audit_keys.rs", "".join(lines))


def gen_backend_gates() -> int:
    cases: list[tuple[str, str]] = []
    for name, arity in [
        ("h", 1),
        ("x", 1),
        ("cx", 2),
        ("ccx", 3),
        ("swap", 2),
        ("rz", 1),
        ("u3", 1),
    ]:
        cases.append(
            (
                f"gate_{name}",
                f'let g = native_gate({rust_str(name)}).unwrap(); assert_eq!(g.name, {rust_str(name)}); assert_eq!(g.num_qubits, {arity});',
            )
        )
    unknown = ["H", "CNOT", "totally_fake", "", "cx ", " ccx", "hadamard", "cnot", "toffoli"]
    for i, name in enumerate(unknown):
        cases.append(
            (
                f"unknown_{i}",
                f"assert!(matches!(native_gate({rust_str(name)}), Err(BackendError::UnknownGate(_))));",
            )
        )
    lines = [
        header("backend", "gates"),
        "use backend::gates::native_gate;\nuse backend::BackendError;\n\n",
    ]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "backend/tests/audit_gates.rs", "".join(lines))


def gen_backend_descriptor() -> int:
    cases: list[tuple[str, str]] = []
    base = (
        '{{"id":"t","num_qubits":{n},"topology":{{"edges":{edges}}},'
        '"native_gates":{gates},"meas_latency_us":0.0,'
        '"supports_mid_circuit_meas":false,"supports_feed_forward":false}}'
    )
    for n in range(2, 10):
        edges = "[]" if n < 2 else f"[[0,1]]"
        gates = '["h"]'
        src = base.format(n=n, edges=edges, gates=gates)
        cases.append(
            (
                f"ok_{n}",
                f"assert!(backend::json::from_str({rust_str(src)}).is_ok());",
            )
        )
    # Unknown fields rejected
    for i, extra in enumerate(['"typo":1', '"extra_field":true', '"num_qubit":3']):
        src = (
            '{"id":"t","num_qubits":2,"topology":{"edges":[]},'
            f'"native_gates":["h"],"meas_latency_us":0.0,'
            '"supports_mid_circuit_meas":false,"supports_feed_forward":false,'
            f"{extra}}}"
        )
        cases.append((f"deny_unknown_{i}", f"assert!(backend::json::from_str({rust_str(src)}).is_err());"))
    # Bad gates
    for i, gate in enumerate(["not_a_gate", "CNOT", ""]):
        src = base.format(n=2, edges="[]", gates=f'["{gate}"]')
        cases.append(
            (
                f"bad_gate_{i}",
                f"assert!(matches!(backend::json::from_str({rust_str(src)}), Err(backend::BackendError::UnknownGate(_))));",
            )
        )
    # Self-loop and out-of-range edges
    for i, (n, edges) in enumerate(
        [
            (2, "[[0,0]]"),
            (2, "[[0,5]]"),
            (3, "[[1,9]]"),
            (1, "[[0,1]]"),
        ]
    ):
        src = base.format(n=n, edges=edges, gates='["h"]')
        cases.append((f"bad_edge_{i}", f"assert!(backend::json::from_str({rust_str(src)}).is_err());"))
    # Malformed JSON
    for i, src in enumerate(["{", "not json", '{"id":}', "[]"]):
        cases.append((f"bad_json_{i}", f"assert!(backend::json::from_str({rust_str(src)}).is_err());"))
    lines = [header("backend", "descriptor JSON"), "\n"]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "backend/tests/audit_descriptor.rs", "".join(lines))


def gen_frontend_lexer() -> int:
    keywords = [
        "fn",
        "type",
        "let",
        "in",
        "return",
        "match",
        "circuit",
        "run",
        "borrow",
        "for",
        "if",
        "then",
        "else",
        "true",
        "false",
        "adjoint",
        "controlled",
        "par",
    ]
    token_names = {
        "fn": "Fn",
        "type": "Type",
        "let": "Let",
        "in": "In",
        "return": "Return",
        "match": "Match",
        "circuit": "Circuit",
        "run": "Run",
        "borrow": "Borrow",
        "for": "For",
        "if": "If",
        "then": "Then",
        "else": "Else",
        "true": "True",
        "false": "False",
        "adjoint": "Adjoint",
        "controlled": "Controlled",
        "par": "Par",
    }
    cases: list[tuple[str, str]] = []
    for kw in keywords:
        cases.append(
            (
                f"kw_{kw}",
                f'assert_eq!(tok({rust_str(kw)}), vec![Token::{token_names[kw]}]);',
            )
        )
    ops = [
        ("|>", "Pipe"),
        ("<-", "Bind"),
        ("->", "Arrow"),
        ("-o", "LinearArrow"),
        ("=>", "FatArrow"),
        ("+", "Plus"),
        ("-", "Minus"),
        ("*", "Star"),
        ("/", "Slash"),
        ("^", "Caret"),
        ("=", "Eq"),
        (":", "Colon"),
        (",", "Comma"),
        (".", "Dot"),
        ("_", "Underscore"),
        ("`", "Backtick"),
        ("|", "Bar"),
    ]
    for i, (src, tok) in enumerate(ops):
        cases.append((f"op_{i:02d}", f'assert_eq!(tok({rust_str(src)}), vec![Token::{tok}]);'))
    for n in range(-16, 16):
        if n < 0:
            name = f"int_neg_{abs(n)}"
            body = (
                f"assert_eq!(tok({rust_str(str(n))}), "
                f"vec![Token::Minus, Token::Int({abs(n)})]);"
            )
        else:
            name = f"int_{n}"
            body = f"assert_eq!(tok({rust_str(str(n))}), vec![Token::Int({n})]);"
        cases.append((name, body))
    # Lexer requires a decimal point for floats; unary `-` is a separate token.
    floats = [
        ("0.0", "vec![Token::Float(0.0)]"),
        ("1.5", "vec![Token::Float(1.5)]"),
        ("2.75", "vec![Token::Float(2.75)]"),
        ("-2.5", "vec![Token::Minus, Token::Float(2.5)]"),
        ("1.0e3", "vec![Token::Float(1000.0)]"),
        ("1.0e-2", "vec![Token::Float(0.01)]"),
    ]
    for i, (src, expect) in enumerate(floats):
        cases.append(
            (
                f"float_{i}",
                f"assert_eq!(tok({rust_str(src)}), {expect});",
            )
        )
    idents = ["foo", "bar_baz", "H", "q0", "_hidden", "QFT", "measure", "letx"]
    for name in idents:
        cases.append(
            (
                f"id_{name}",
                f'assert_eq!(tok({rust_str(name)}), vec![Token::Ident({rust_str(name)}.into())]);',
            )
        )
    lines = [
        header("frontend", "lexer"),
        "use frontend::lexer::{lex, Token};\n\n",
        "fn toks(src: &str) -> Vec<Token> {\n",
        "    lex(src).unwrap().into_iter().map(|(t, _)| t).collect()\n",
        "}\n",
        "fn tok(src: &str) -> Vec<Token> { toks(src) }\n\n",
    ]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "frontend/tests/audit_lexer.rs", "".join(lines))


def gen_depth_subst() -> int:
    cases: list[tuple[str, str]] = []
    for n in range(20):
        cases.append(
            (
                f"subst_nat_{n}",
                f'let env = [("n".into(), DepthExpr::Nat({n}))].into_iter().collect(); '
                f'assert_eq!(DepthExpr::Var("n".into()).subst(&env), DepthExpr::Nat({n}));',
            )
        )
    for a in range(8):
        for b in range(8):
            cases.append(
                (
                    f"subst_add_{a}_{b}",
                    f'let env = [("x".into(), DepthExpr::Nat({a})), ("y".into(), DepthExpr::Nat({b}))].into_iter().collect(); '
                    f'let e = DepthExpr::Var("x".into()).seq(DepthExpr::Var("y".into())); '
                    f'assert_eq!(e.subst(&env).as_const(), Some({a + b}));',
                )
            )
    for name in ["missing", "unbound", "z"]:
        cases.append(
            (
                f"subst_missing_{name}",
                f'let env = std::collections::HashMap::new(); '
                f'assert_eq!(DepthExpr::Var({rust_str(name)}.into()).subst(&env), DepthExpr::Var({rust_str(name)}.into()));',
            )
        )
    lines = [header("quon_core", "depth subst"), "use quon_core::DepthExpr;\n\n"]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "quon_core/tests/audit_depth_subst.rs", "".join(lines))


def gen_zx() -> int:
    cases: list[tuple[str, str]] = []
    gates = ["h", "x", "z", "cx", "rz", "swap"]
    for name in gates:
        for q in range(8):
            cases.append(
                (
                    f"gate_{name}_{q}",
                    f'let g = GateRef::new("{name}", vec![{q}]); assert_eq!(g.name, "{name}"); assert_eq!(g.qubits, vec![{q}]); assert!(g.angle.is_none());',
                )
            )
    for q in range(16):
        angle = q * 0.1
        cases.append(
            (
                f"rot_{q}",
                f"let g = GateRef::rotation(\"rz\", {q}, {angle}); assert_eq!(g.angle, Some({angle}));",
            )
        )
    lines = [header("zx", "GateRef"), "use zx::GateRef;\n\n"]
    for name, body in cases:
        lines.append(f"audit_case!({name}, {{ {body} }});\n")
    return write(ROOT / "zx/tests/audit_gate.rs", "".join(lines))


def main() -> None:
    os.chdir(ROOT)
    total = 0
    for gen in (
        gen_depth_parse,
        gen_depth_const,
        gen_depth_subst,
        gen_linearity,
        gen_optimization,
        gen_backend_keys,
        gen_backend_gates,
        gen_backend_descriptor,
        gen_frontend_lexer,
        gen_zx,
    ):
        n = gen()
        print(f"  {n:4d}  {gen.__name__}")
        total += n
    print(f"generated {total} audit tests")


if __name__ == "__main__":
    main()
