#!/usr/bin/env bash
# Generate a Homebrew formula with real SHA256s from dist/ archives (issue #235).
# Only emits platform blocks for archives that exist (avoids bogus zero hashes).
# Does not overwrite the placeholder template unless --in-place is passed.
#
# Usage:
#   ./scripts/generate-homebrew-formula.sh
#   ./scripts/generate-homebrew-formula.sh --version 0.1.0 --dist-dir dist
#   ./scripts/generate-homebrew-formula.sh --out dist/quon.rb
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VERSION=""
DIST_DIR="$ROOT/dist"
OUT="$ROOT/dist/quon.rb"
IN_PLACE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      VERSION="${2:?}"
      shift 2
      ;;
    --dist-dir)
      DIST_DIR="$(cd "${2:?}" && pwd)"
      shift 2
      ;;
    --out)
      OUT="${2:?}"
      shift 2
      ;;
    --in-place)
      IN_PLACE=1
      OUT="$ROOT/packaging/homebrew/quon.rb"
      shift
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$VERSION" ]]; then
  VERSION="${QUON_RELEASE_VERSION:-}"
fi
if [[ -z "$VERSION" ]]; then
  if git describe --tags --exact-match HEAD >/dev/null 2>&1; then
    VERSION="$(git describe --tags --exact-match HEAD)"
  else
    VERSION="0.1.0"
  fi
fi
VERSION="${VERSION#v}"

file_sha256() {
  local archive="$1"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$archive" | awk '{print $1}'
  else
    sha256sum "$archive" | awk '{print $1}'
  fi
}

# Collect present archives: triple -> sha256
PRESENT=()
add_if_present() {
  local triple="$1"
  local archive="$DIST_DIR/quon-${VERSION}-${triple}.tar.gz"
  if [[ -f "$archive" ]]; then
    PRESENT+=("${triple}:$(file_sha256 "$archive")")
    echo "generate-homebrew-formula: $triple  $(file_sha256 "$archive")"
  else
    echo "generate-homebrew-formula: skip missing $archive" >&2
  fi
}

add_if_present "aarch64-apple-darwin"
add_if_present "x86_64-apple-darwin"
add_if_present "x86_64-unknown-linux-gnu"
add_if_present "aarch64-unknown-linux-gnu"

if [[ ${#PRESENT[@]} -eq 0 ]]; then
  echo "generate-homebrew-formula: no archives in $DIST_DIR for version $VERSION" >&2
  exit 1
fi

sha_for() {
  local want="$1"
  local entry
  for entry in "${PRESENT[@]}"; do
    if [[ "${entry%%:*}" == "$want" ]]; then
      echo "${entry#*:}"
      return 0
    fi
  done
  return 1
}

has_macos=0
has_linux=0
if sha_for "aarch64-apple-darwin" >/dev/null || sha_for "x86_64-apple-darwin" >/dev/null; then
  has_macos=1
fi
if sha_for "x86_64-unknown-linux-gnu" >/dev/null || sha_for "aarch64-unknown-linux-gnu" >/dev/null; then
  has_linux=1
fi

mkdir -p "$(dirname "$OUT")"
{
  cat <<EOF
# frozen_string_literal: true

# Generated by scripts/generate-homebrew-formula.sh for Quon v${VERSION}.
# Do not add depends_on "llvm@22" or "z3" — release binaries are self-contained.
# Publish to arniber21/homebrew-quon (see packaging/homebrew/README.md).

class Quon < Formula
  desc "MLIR-based optimizing compiler for quantum programs"
  homepage "https://github.com/arniber21/quon"
  license "Apache-2.0"
  version "${VERSION}"

EOF

  if [[ "$has_macos" -eq 1 ]]; then
    echo "  on_macos do"
    if sha="$(sha_for "aarch64-apple-darwin")"; then
      cat <<EOF
    on_arm do
      url "https://github.com/arniber21/quon/releases/download/v#{version}/quon-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${sha}"
    end
EOF
    fi
    if sha="$(sha_for "x86_64-apple-darwin")"; then
      cat <<EOF
    on_intel do
      url "https://github.com/arniber21/quon/releases/download/v#{version}/quon-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${sha}"
    end
EOF
    fi
    echo "  end"
    echo
  fi

  if [[ "$has_linux" -eq 1 ]]; then
    echo "  on_linux do"
    if sha="$(sha_for "x86_64-unknown-linux-gnu")"; then
      cat <<EOF
    on_intel do
      url "https://github.com/arniber21/quon/releases/download/v#{version}/quon-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${sha}"
    end
EOF
    fi
    if sha="$(sha_for "aarch64-unknown-linux-gnu")"; then
      cat <<EOF
    on_arm do
      url "https://github.com/arniber21/quon/releases/download/v#{version}/quon-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${sha}"
    end
EOF
    fi
    echo "  end"
    echo
  fi

  cat <<'EOF'
  # Runtime: none beyond the OS. Do not add llvm@22 / z3 / mlir here.

  def install
    bin.install "quonc", "quonfmt", "quon_lsp", "quonlint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quonc --version")
    assert_match version.to_s, shell_output("#{bin}/quonfmt --version")
  end
end
EOF
} >"${OUT}.new"
mv "${OUT}.new" "$OUT"

if [[ "$IN_PLACE" -eq 1 ]]; then
  echo "generate-homebrew-formula: wrote $OUT (in-place; placeholder template replaced)"
else
  echo "generate-homebrew-formula: wrote $OUT (placeholder template unchanged)"
fi
