//! Depth-bounded `Unstructured` AST generator — the single source of truth for both the
//! cargo-fuzz targets and the in-tree proptest (`frontend/tests/roundtrip_props.rs` includes
//! this file via `#[path]` and drives it with proptest-generated bytes), so the two never
//! drift. Every node carries a `0..0` span; identifiers avoid keywords and type names avoid
//! built-ins, so `pretty(gen)` is always valid source.

use arbitrary::{Result, Unstructured};
use frontend::ast::*;
use frontend::lexer::{SimpleSpan, Sp};

fn sp<T>(t: T) -> Sp<T> {
    (t, SimpleSpan::from(0..0))
}

fn b<T>(t: T) -> Box<T> {
    Box::new(t)
}

// Includes operator-collision-prone names (e.g. `o`, `o1` would form `-o` after a unary minus)
// so the printer's token-adjacency handling stays covered.
const IDENTS: &[&str] = &[
    "a", "b", "c", "f", "g", "h", "q", "x", "y", "z", "gate", "reg", "n", "o", "o1", "ox",
];
const TYPE_NAMES: &[&str] = &["Alias", "Oracle", "Bvk", "Bellx", "Foo", "Reg"];

fn ident(u: &mut Unstructured) -> Result<String> {
    Ok((*u.choose(IDENTS)?).to_string())
}

fn sp_ident(u: &mut Unstructured) -> Result<Sp<Name>> {
    Ok(sp(ident(u)?))
}

fn type_name(u: &mut Unstructured) -> Result<String> {
    Ok((*u.choose(TYPE_NAMES)?).to_string())
}

fn float_lit(u: &mut Unstructured) -> Result<f64> {
    // Quarter steps always print with a `.` and round-trip exactly.
    Ok(u8::arbitrary(u)? as f64 / 4.0)
}

use arbitrary::Arbitrary;

pub fn nat(u: &mut Unstructured, depth: u32) -> Result<Sp<NatExpr>> {
    if depth == 0 || u.is_empty() {
        return Ok(sp(match u.int_in_range(0..=2)? {
            0 => NatExpr::Lit(u16::arbitrary(u)? as u64),
            1 => NatExpr::Var(ident(u)?),
            _ => NatExpr::Hole,
        }));
    }
    Ok(sp(match u.int_in_range(0..=7)? {
        0 => NatExpr::Lit(u16::arbitrary(u)? as u64),
        1 => NatExpr::Var(ident(u)?),
        2 => NatExpr::Add(b(nat(u, depth - 1)?), b(nat(u, depth - 1)?)),
        3 => NatExpr::Sub(b(nat(u, depth - 1)?), b(nat(u, depth - 1)?)),
        4 => NatExpr::Mul(b(nat(u, depth - 1)?), b(nat(u, depth - 1)?)),
        5 => NatExpr::Div(b(nat(u, depth - 1)?), b(nat(u, depth - 1)?)),
        6 => NatExpr::Exp(b(nat(u, depth - 1)?), b(nat(u, depth - 1)?)),
        _ => NatExpr::Hole,
    }))
}

fn class(u: &mut Unstructured) -> Result<CliffordClass> {
    Ok(if bool::arbitrary(u)? {
        CliffordClass::Clifford
    } else {
        CliffordClass::Universal
    })
}

pub fn ty(u: &mut Unstructured, depth: u32) -> Result<Sp<Type>> {
    if depth == 0 || u.is_empty() {
        return Ok(sp(match u.int_in_range(0..=7)? {
            0 => Type::Qubit,
            1 => Type::Bit,
            2 => Type::Bool,
            3 => Type::Int,
            4 => Type::Float,
            5 => Type::Unit,
            6 => Type::Nat,
            // A bare non-builtin name is a type variable / alias reference.
            _ => Type::Var(type_name(u)?),
        }));
    }
    Ok(sp(match u.int_in_range(0..=8)? {
        0 => Type::QReg(nat(u, 2)?),
        1 => Type::Q(b(ty(u, depth - 1)?)),
        2 => Type::List(b(ty(u, depth - 1)?)),
        3 => Type::Matrix(nat(u, 2)?, nat(u, 2)?, b(ty(u, depth - 1)?)),
        4 => Type::Circuit {
            n: nat(u, 2)?,
            m: nat(u, 2)?,
            d: nat(u, 2)?,
            c: class(u)?,
        },
        5 => Type::Fn(b(ty(u, depth - 1)?), b(ty(u, depth - 1)?)),
        6 => Type::Linear(b(ty(u, depth - 1)?), b(ty(u, depth - 1)?)),
        7 => {
            let n = u.int_in_range(2..=3)?;
            let mut ts = Vec::new();
            for _ in 0..n {
                ts.push(ty(u, depth - 1)?);
            }
            Type::Tuple(ts)
        }
        _ => {
            let n = u.int_in_range(1..=2)?;
            let mut args = Vec::new();
            for _ in 0..n {
                args.push(nat(u, 2)?);
            }
            Type::Named {
                name: type_name(u)?,
                args,
            }
        }
    }))
}

pub fn pat(u: &mut Unstructured, depth: u32) -> Result<Sp<Pat>> {
    if depth == 0 || u.is_empty() {
        return Ok(sp(match u.int_in_range(0..=3)? {
            0 => Pat::Wildcard,
            1 => Pat::Var(ident(u)?),
            2 => Pat::Lit(LitPat::Int(u8::arbitrary(u)? as i64)),
            _ => Pat::Lit(LitPat::Bool(bool::arbitrary(u)?)),
        }));
    }
    if u.int_in_range(0..=2)? == 0 {
        let n = u.int_in_range(2..=3)?;
        let mut ps = Vec::new();
        for _ in 0..n {
            ps.push(pat(u, depth - 1)?);
        }
        Ok(sp(Pat::Tuple(ps)))
    } else {
        pat(u, 0)
    }
}

fn stmt(u: &mut Unstructured, depth: u32) -> Result<Sp<Stmt>> {
    Ok(sp(match u.int_in_range(0..=2)? {
        0 => Stmt::Bind {
            pat: pat(u, 1)?,
            rhs: expr(u, depth)?,
        },
        1 => Stmt::Let {
            pat: pat(u, 1)?,
            rhs: expr(u, depth)?,
        },
        _ => Stmt::Expr(expr(u, depth)?),
    }))
}

fn stmts(u: &mut Unstructured, depth: u32) -> Result<Vec<Sp<Stmt>>> {
    let n = u.int_in_range(1..=3)?;
    let mut v = Vec::new();
    for _ in 0..n {
        v.push(stmt(u, depth)?);
    }
    Ok(v)
}

fn binop(u: &mut Unstructured) -> Result<BinOp> {
    Ok(match u.int_in_range(0..=4)? {
        0 => BinOp::Add,
        1 => BinOp::Sub,
        2 => BinOp::Mul,
        3 => BinOp::Div,
        _ => BinOp::Pow,
    })
}

pub fn expr(u: &mut Unstructured, depth: u32) -> Result<Sp<Expr>> {
    if depth == 0 || u.is_empty() {
        return Ok(sp(match u.int_in_range(0..=4)? {
            0 => Expr::Int(u16::arbitrary(u)? as i64),
            1 => Expr::Float(float_lit(u)?),
            2 => Expr::Bool(bool::arbitrary(u)?),
            3 => Expr::Unit,
            _ => Expr::Var(ident(u)?),
        }));
    }
    let d = depth - 1;
    Ok(sp(match u.int_in_range(0..=20)? {
        0 => Expr::App(b(expr(u, d)?), b(expr(u, d)?)),
        1 => Expr::BinOp {
            op: binop(u)?,
            lhs: b(expr(u, d)?),
            rhs: b(expr(u, d)?),
        },
        2 => Expr::Neg(b(expr(u, d)?)),
        3 => Expr::Compose(b(expr(u, d)?), b(expr(u, d)?)),
        4 => Expr::GateApp {
            gate: b(expr(u, d)?),
            qubits: b(expr(u, d)?),
        },
        5 => Expr::Adjoint(b(expr(u, d)?)),
        6 => Expr::Controlled(b(expr(u, d)?)),
        7 => Expr::Return(b(expr(u, d)?)),
        8 => Expr::Ascribe(b(expr(u, d)?), ty(u, 2)?),
        9 => {
            let n = u.int_in_range(2..=3)?;
            let mut es = Vec::new();
            for _ in 0..n {
                es.push(expr(u, d)?);
            }
            Expr::Tuple(es)
        }
        10 => {
            let n = u.int_in_range(0..=3)?;
            let mut es = Vec::new();
            for _ in 0..n {
                es.push(expr(u, d)?);
            }
            Expr::List(es)
        }
        11 => {
            let n = u.int_in_range(1..=2)?;
            let mut params = Vec::new();
            for _ in 0..n {
                let t = if bool::arbitrary(u)? {
                    Some(ty(u, 1)?)
                } else {
                    None
                };
                params.push((pat(u, 1)?, t));
            }
            Expr::Lam {
                params,
                body: b(expr(u, d)?),
            }
        }
        12 => Expr::Let {
            pat: pat(u, 1)?,
            rhs: b(expr(u, d)?),
            body: b(expr(u, d)?),
        },
        13 => Expr::If {
            cond: b(expr(u, d)?),
            then: b(expr(u, d)?),
            else_: b(expr(u, d)?),
        },
        14 => {
            let n = u.int_in_range(1..=2)?;
            let mut arms = Vec::new();
            for _ in 0..n {
                arms.push((pat(u, 1)?, expr(u, d)?));
            }
            Expr::Match {
                scrutinee: b(expr(u, d)?),
                arms,
            }
        }
        15 => Expr::For {
            pat: pat(u, 1)?,
            iter: b(expr(u, d)?),
            body: b(expr(u, d)?),
        },
        16 => Expr::Par(b(expr(u, d)?), b(expr(u, d)?)),
        17 => Expr::CircuitBlock(stmts(u, d)?),
        18 => Expr::RunBlock(stmts(u, d)?),
        19 => {
            let n = u.int_in_range(1..=2)?;
            let mut bindings = Vec::new();
            for _ in 0..n {
                bindings.push((sp_ident(u)?, ty(u, 1)?));
            }
            Expr::Borrow {
                bindings,
                body: stmts(u, d)?,
            }
        }
        _ => Expr::Var(ident(u)?),
    }))
}

fn decl(u: &mut Unstructured, depth: u32) -> Result<Sp<Decl>> {
    Ok(sp(if bool::arbitrary(u)? {
        let np = u.int_in_range(0..=2)?;
        let mut params = Vec::new();
        for _ in 0..np {
            params.push((sp_ident(u)?, ty(u, 2)?));
        }
        Decl::Fn {
            name: sp_ident(u)?,
            type_params: Vec::new(),
            params,
            ret: ty(u, 2)?,
            body: expr(u, depth)?,
        }
    } else {
        let np = u.int_in_range(0..=2)?;
        let mut params = Vec::new();
        for _ in 0..np {
            params.push(TypeParam {
                name: sp_ident(u)?,
                kind: None,
            });
        }
        Decl::TypeAlias {
            name: sp(type_name(u)?),
            params,
            ty: ty(u, 3)?,
        }
    }))
}

/// Generate a small program (1–2 declarations).
pub fn arb_program(u: &mut Unstructured) -> Result<Vec<Sp<Decl>>> {
    let n = u.int_in_range(1..=2)?;
    let mut decls = Vec::new();
    for _ in 0..n {
        decls.push(decl(u, 4)?);
    }
    Ok(decls)
}
